/*
**
** The C code is generated by [ATS/Postiats-0-3-0]
** The starting compilation time is: 2017-1-26:  1h:33m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/root/ATS-Postiats/prelude/DATS/basics.dats: 1534(line=44, offs=1) -- 1573(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 1637(line=51, offs=1) -- 1676(line=51, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 15413(line=857, offs=1) -- 15450(line=858, offs=30)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/root/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0int_lt_int)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_extfun(ASSIGN00__isTriangle, (atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_bool)) ;
ATSdyncst_mac(atspre_neg_bool0)
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_g0int_gte_int)
ATSdyncst_mac(atspre_g0int_sub_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_extfun(ASSIGN00__fib_trec, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_print_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ASSIGN00__isTriangle(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
ASSIGN00__fib_trec(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
trec_helper_9(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__10(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__10__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
__patsfun_14(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__15(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__15__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/tmp/assigns/00/MySolution/assign00_sol.dats: 294(line=23, offs=11) -- 374(line=26, offs=13)
*/
/*
local: 
global: isTriangle$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
ASSIGN00__isTriangle(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 284(line=23, offs=1) -- 374(line=26, offs=13)
*/
ATSINSflab(__patsflab_isTriangle):
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp8, atspre_g0int_add_int(arg0, arg1)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp3, ATSLIB_056_prelude__gt_g0int_int__1__1(tmp8, arg2)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSif(
tmp3
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp11, atspre_g0int_add_int(arg0, arg2)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__gt_g0int_int__1__2(tmp11, arg1)) ;

} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp2, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp14, atspre_g0int_add_int(arg2, arg1)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp1, ATSLIB_056_prelude__gt_g0int_int__1__3(tmp14, arg0)) ;

} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 311(line=24, offs=5) -- 347(line=24, offs=41)
*/
ATSINSmove(tmp1, ATSPMVbool_false()) ;
} /* ATSendif */
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 308(line=24, offs=2) -- 374(line=26, offs=13)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 356(line=25, offs=8) -- 360(line=25, offs=12)
*/
ATSINSmove(tmpret0, ATSPMVbool_true()) ;
} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 369(line=26, offs=8) -- 374(line=26, offs=13)
*/
ATSINSmove(tmpret0, ATSPMVbool_false()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [ASSIGN00__isTriangle] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4627)
tmparg = S2Evar(tk(4627))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4627))>)(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4, PMVtmpltcst(g0int_gt<S2Evar(tk(4627))>)(arg0, tmp5)) ;

ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4627)
tmparg = S2Evar(tk(4627))
tmpsub = Some(tk(4627) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4__1, atspre_g0int_gt_int(arg0, tmp5__1)) ;

ATSfunbody_end()
ATSreturn(tmpret4__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1__1] */

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4627)
tmparg = S2Evar(tk(4627))
tmpsub = Some(tk(4627) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4__2, atspre_g0int_gt_int(arg0, tmp5__2)) ;

ATSfunbody_end()
ATSreturn(tmpret4__2) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1__2] */

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11672(line=592, offs=3) -- 11711(line=592, offs=42)
*/
/*
local: 
global: gt_g0int_int$1$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4627)
tmparg = S2Evar(tk(4627))
tmpsub = Some(tk(4627) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__1__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp5__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11657(line=591, offs=1) -- 11711(line=592, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11698(line=592, offs=29) -- 11709(line=592, offs=40)
*/
ATSINSmove(tmp5__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11681(line=592, offs=12) -- 11711(line=592, offs=42)
*/
ATSINSmove(tmpret4__3, atspre_g0int_gt_int(arg0, tmp5__3)) ;

ATSfunbody_end()
ATSreturn(tmpret4__3) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__1__3] */

/*
/tmp/assigns/00/MySolution/assign00_sol.dats: 466(line=32, offs=19) -- 620(line=41, offs=4)
*/
/*
local: 
global: fib_trec$8$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
ASSIGN00__fib_trec(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret15, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 458(line=32, offs=11) -- 620(line=41, offs=4)
*/
ATSINSflab(__patsflab_fib_trec):
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 472(line=32, offs=25) -- 620(line=41, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 595(line=40, offs=3) -- 616(line=40, offs=24)
*/
ATSINSmove(tmpret15, trec_helper_9(arg0, ATSPMVi0nt(0), ATSPMVi0nt(0), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 472(line=32, offs=25) -- 620(line=41, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret15) ;
} /* end of [ASSIGN00__fib_trec] */

/*
/tmp/assigns/00/MySolution/assign00_sol.dats: 483(line=34, offs=5) -- 586(line=37, offs=10)
*/
/*
local: trec_helper_9$0(level=1)
global: trec_helper_9$0(level=1)
local: n$4494(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
global: n$4494(1)(HSEapp(HSEcst(atstkind_t0ype); HSEs2exp(S2Eextkind(atstype_int))))
*/
ATSstatic()
atstkind_t0ype(atstype_int)
trec_helper_9(atstkind_t0ype(atstype_int) env0, atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 483(line=34, offs=5) -- 586(line=37, offs=10)
*/
ATSINSflab(__patsflab_trec_helper_9):
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 533(line=35, offs=5) -- 538(line=35, offs=10)
*/
ATSINSmove(tmp17, ATSLIB_056_prelude__lt_g0int_int__10__1(arg0, env0)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 530(line=35, offs=2) -- 586(line=37, offs=10)
*/
ATSif(
tmp17
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 560(line=36, offs=21) -- 563(line=36, offs=24)
*/
ATSINSmove(tmp22, atspre_g0int_add_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 569(line=36, offs=30) -- 574(line=36, offs=35)
*/
ATSINSmove(tmp23, atspre_g0int_add_int(arg1, arg2)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 547(line=36, offs=8) -- 575(line=36, offs=36)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp22) ;
ATSINSmove_tlcal(apy1, arg2) ;
ATSINSmove_tlcal(apy2, tmp23) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_trec_helper_9) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 584(line=37, offs=8) -- 586(line=37, offs=10)
*/
ATSINSmove(tmpret16, arg1) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [trec_helper_9] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4625)
tmparg = S2Evar(tk(4625))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__10(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp19, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4625))>)(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret18, PMVtmpltcst(g0int_lt<S2Evar(tk(4625))>)(arg0, tmp19)) ;

ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__10] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11513(line=583, offs=3) -- 11552(line=583, offs=42)
*/
/*
local: 
global: lt_g0int_int$10$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4625)
tmparg = S2Evar(tk(4625))
tmpsub = Some(tk(4625) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__lt_g0int_int__10__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp19__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11498(line=582, offs=1) -- 11552(line=583, offs=42)
*/
ATSINSflab(__patsflab_lt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11539(line=583, offs=29) -- 11550(line=583, offs=40)
*/
ATSINSmove(tmp19__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11522(line=583, offs=12) -- 11552(line=583, offs=42)
*/
ATSINSmove(tmpret18__1, atspre_g0int_lt_int(arg0, tmp19__1)) ;

ATSfunbody_end()
ATSreturn(tmpret18__1) ;
} /* end of [ATSLIB_056_prelude__lt_g0int_int__10__1] */

/*
/tmp/assigns/00/MySolution/assign00_sol.dats: 776(line=57, offs=6) -- 1453(line=88, offs=2)
*/
/*
local: 
global: mainats_void_0$13$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret24) ;
// ATStmpdec_void(tmp25) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp27) ;
ATStmpdec(tmp28, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp29) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp32) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp35) ;
// ATStmpdec_void(tmp36) ;
ATStmpdec(tmp47, atstype_funptr) ;
// ATStmpdec_void(tmp48) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp56) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp60, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp61, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp62) ;
ATStmpdec(tmp63, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp66, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp67, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp68) ;
// ATStmpdec_void(tmp69) ;
ATStmpdec(tmp70, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp71) ;
// ATStmpdec_void(tmp72) ;
// ATStmpdec_void(tmp73) ;
ATStmpdec(tmp74, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp75) ;
// ATStmpdec_void(tmp76) ;
// ATStmpdec_void(tmp77) ;
ATStmpdec(tmp78, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp79) ;
// ATStmpdec_void(tmp80) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 771(line=57, offs=1) -- 1453(line=88, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 781(line=57, offs=11) -- 1453(line=88, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 804(line=61, offs=1) -- 832(line=61, offs=29)
*/
ATSINSmove(tmp26, ASSIGN00__isTriangle(ATSPMVi0nt(3), ATSPMVi0nt(4), ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 804(line=61, offs=1) -- 832(line=61, offs=29)
*/
ATSINSmove_void(tmp25, atspre_assert_errmsg_bool0(tmp26, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 804(line=61, offs=1) -- 832(line=61, offs=29)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 842(line=63, offs=1) -- 870(line=63, offs=29)
*/
ATSINSmove(tmp28, ASSIGN00__isTriangle(ATSPMVi0nt(5), ATSPMVi0nt(4), ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 842(line=63, offs=1) -- 870(line=63, offs=29)
*/
ATSINSmove_void(tmp27, atspre_assert_errmsg_bool0(tmp28, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 842(line=63, offs=1) -- 870(line=63, offs=29)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 880(line=65, offs=1) -- 909(line=65, offs=30)
*/
ATSINSmove(tmp31, ASSIGN00__isTriangle(ATSPMVi0nt(1), ATSPMVi0nt(2), ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 880(line=65, offs=1) -- 909(line=65, offs=30)
*/
ATSINSmove(tmp30, atspre_neg_bool0(tmp31)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 880(line=65, offs=1) -- 909(line=65, offs=30)
*/
ATSINSmove_void(tmp29, atspre_assert_errmsg_bool0(tmp30, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 880(line=65, offs=1) -- 909(line=65, offs=30)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 919(line=67, offs=1) -- 948(line=67, offs=30)
*/
ATSINSmove(tmp34, ASSIGN00__isTriangle(ATSPMVi0nt(3), ATSPMVi0nt(2), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 919(line=67, offs=1) -- 948(line=67, offs=30)
*/
ATSINSmove(tmp33, atspre_neg_bool0(tmp34)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 919(line=67, offs=1) -- 948(line=67, offs=30)
*/
ATSINSmove_void(tmp32, atspre_assert_errmsg_bool0(tmp33, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 919(line=67, offs=1) -- 948(line=67, offs=30)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 961(line=70, offs=1) -- 1019(line=71, offs=50)
*/
ATSINSmove_void(tmp35, atspre_print_string(ATSPMVstring("Testing of [isTriangle] is done successfully!"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 961(line=70, offs=1) -- 1019(line=71, offs=50)
*/
ATSINSmove_void(tmp36, atspre_print_newline()) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1027(line=73, offs=5) -- 1030(line=73, offs=8)
*/
ATSINSmove(tmp47, ATSPMVfunlab(__patsfun_14)) ;
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1105(line=77, offs=10) -- 1136(line=77, offs=41)
*/
ATSINSmove(tmp54, ATSfunclo_fun(tmp47, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int))(ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1105(line=77, offs=10) -- 1136(line=77, offs=41)
*/
ATSINSmove(tmp55, ASSIGN00__fib_trec(ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1105(line=77, offs=10) -- 1136(line=77, offs=41)
*/
ATSINSmove(tmp49, ATSLIB_056_prelude__eq_g0int_int__19__1(tmp54, tmp55)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1105(line=77, offs=10) -- 1136(line=77, offs=41)
*/
ATSINSmove_void(tmp48, atspre_assert_errmsg_bool0(tmp49, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 1105(line=77, offs=10) -- 1136(line=77, offs=41)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1146(line=78, offs=10) -- 1179(line=78, offs=43)
*/
ATSINSmove(tmp60, ATSfunclo_fun(tmp47, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int))(ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1146(line=78, offs=10) -- 1179(line=78, offs=43)
*/
ATSINSmove(tmp61, ASSIGN00__fib_trec(ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1146(line=78, offs=10) -- 1179(line=78, offs=43)
*/
ATSINSmove(tmp57, ATSLIB_056_prelude__eq_g0int_int__19__2(tmp60, tmp61)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1146(line=78, offs=10) -- 1179(line=78, offs=43)
*/
ATSINSmove_void(tmp56, atspre_assert_errmsg_bool0(tmp57, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 1146(line=78, offs=10) -- 1179(line=78, offs=43)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1189(line=79, offs=10) -- 1222(line=79, offs=43)
*/
ATSINSmove(tmp66, ATSfunclo_fun(tmp47, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int))(ATSPMVi0nt(20))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1189(line=79, offs=10) -- 1222(line=79, offs=43)
*/
ATSINSmove(tmp67, ASSIGN00__fib_trec(ATSPMVi0nt(20))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1189(line=79, offs=10) -- 1222(line=79, offs=43)
*/
ATSINSmove(tmp63, ATSLIB_056_prelude__eq_g0int_int__19__3(tmp66, tmp67)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1189(line=79, offs=10) -- 1222(line=79, offs=43)
*/
ATSINSmove_void(tmp62, atspre_assert_errmsg_bool0(tmp63, ATSCSTSPmyloc("/tmp/assigns/00/MySolution/assign00_sol.dats: 1189(line=79, offs=10) -- 1222(line=79, offs=43)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1235(line=81, offs=10) -- 1275(line=81, offs=50)
*/
ATSINSmove_void(tmp68, atspre_print_string(ATSPMVstring("fib_trec(5) = "))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1263(line=81, offs=38) -- 1274(line=81, offs=49)
*/
ATSINSmove(tmp70, ASSIGN00__fib_trec(ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1235(line=81, offs=10) -- 1275(line=81, offs=50)
*/
ATSINSmove_void(tmp69, atspre_print_int(tmp70)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1235(line=81, offs=10) -- 1275(line=81, offs=50)
*/
ATSINSmove_void(tmp71, atspre_print_newline()) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1285(line=82, offs=10) -- 1327(line=82, offs=52)
*/
ATSINSmove_void(tmp72, atspre_print_string(ATSPMVstring("fib_trec(10) = "))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1314(line=82, offs=39) -- 1326(line=82, offs=51)
*/
ATSINSmove(tmp74, ASSIGN00__fib_trec(ATSPMVi0nt(10))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1285(line=82, offs=10) -- 1327(line=82, offs=52)
*/
ATSINSmove_void(tmp73, atspre_print_int(tmp74)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1285(line=82, offs=10) -- 1327(line=82, offs=52)
*/
ATSINSmove_void(tmp75, atspre_print_newline()) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1337(line=83, offs=10) -- 1379(line=83, offs=52)
*/
ATSINSmove_void(tmp76, atspre_print_string(ATSPMVstring("fib_trec(20) = "))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1366(line=83, offs=39) -- 1378(line=83, offs=51)
*/
ATSINSmove(tmp78, ASSIGN00__fib_trec(ATSPMVi0nt(20))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1337(line=83, offs=10) -- 1379(line=83, offs=52)
*/
ATSINSmove_void(tmp77, atspre_print_int(tmp78)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1337(line=83, offs=10) -- 1379(line=83, offs=52)
*/
ATSINSmove_void(tmp79, atspre_print_newline()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1392(line=86, offs=1) -- 1448(line=86, offs=57)
*/
ATSINSmove_void(tmp80, atspre_print_string(ATSPMVstring("Testing of [fib_trec] is done successfully!"))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1392(line=86, offs=1) -- 1448(line=86, offs=57)
*/
ATSINSmove_void(tmpret24, atspre_print_newline()) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 781(line=57, offs=11) -- 1453(line=88, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret24) ;
} /* end of [mainats_void_0] */

/*
/tmp/assigns/00/MySolution/assign00_sol.dats: 1033(line=74, offs=1) -- 1092(line=75, offs=38)
*/
/*
local: __patsfun_14$0(level=1)
global: __patsfun_14$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
__patsfun_14(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret37, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp45, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1033(line=74, offs=1) -- 1092(line=75, offs=38)
*/
ATSINSflab(__patsflab___patsfun_14):
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1060(line=75, offs=6) -- 1066(line=75, offs=12)
*/
ATSINSmove(tmp38, ATSLIB_056_prelude__gte_g0int_int__15__1(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1057(line=75, offs=3) -- 1092(line=75, offs=38)
*/
ATSif(
tmp38
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1074(line=75, offs=20) -- 1077(line=75, offs=23)
*/
ATSINSmove(tmp44, atspre_g0int_sub_int(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1072(line=75, offs=18) -- 1078(line=75, offs=24)
*/
ATSINSmove(tmp43, __patsfun_14(tmp44)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1081(line=75, offs=27) -- 1084(line=75, offs=30)
*/
ATSINSmove(tmp46, atspre_g0int_sub_int(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1079(line=75, offs=25) -- 1085(line=75, offs=31)
*/
ATSINSmove(tmp45, __patsfun_14(tmp46)) ;

/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1072(line=75, offs=18) -- 1085(line=75, offs=31)
*/
ATSINSmove(tmpret37, atspre_g0int_add_int(tmp43, tmp45)) ;

} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/00/MySolution/assign00_sol.dats: 1091(line=75, offs=37) -- 1092(line=75, offs=38)
*/
ATSINSmove(tmpret37, arg0) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret37) ;
} /* end of [__patsfun_14] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11750(line=596, offs=3) -- 11790(line=596, offs=43)
*/
/*
local: 
global: gte_g0int_int$15$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4628)
tmparg = S2Evar(tk(4628))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__15(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret39, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11734(line=595, offs=1) -- 11790(line=596, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11777(line=596, offs=30) -- 11788(line=596, offs=41)
*/
ATSINSmove(tmp40, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4628))>)(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11759(line=596, offs=12) -- 11790(line=596, offs=43)
*/
ATSINSmove(tmpret39, PMVtmpltcst(g0int_gte<S2Evar(tk(4628))>)(arg0, tmp40)) ;

ATSfunbody_end()
ATSreturn(tmpret39) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__15] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11750(line=596, offs=3) -- 11790(line=596, offs=43)
*/
/*
local: 
global: gte_g0int_int$15$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4628)
tmparg = S2Evar(tk(4628))
tmpsub = Some(tk(4628) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__15__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret39__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11734(line=595, offs=1) -- 11790(line=596, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11777(line=596, offs=30) -- 11788(line=596, offs=41)
*/
ATSINSmove(tmp40__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11759(line=596, offs=12) -- 11790(line=596, offs=43)
*/
ATSINSmove(tmpret39__1, atspre_g0int_gte_int(arg0, tmp40__1)) ;

ATSfunbody_end()
ATSreturn(tmpret39__1) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__15__1] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$19$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4629)
tmparg = S2Evar(tk(4629))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp51, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4629))>)(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret50, PMVtmpltcst(g0int_eq<S2Evar(tk(4629))>)(arg0, tmp51)) ;

ATSfunbody_end()
ATSreturn(tmpret50) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__19] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$19$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4629)
tmparg = S2Evar(tk(4629))
tmpsub = Some(tk(4629) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp51__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret50__1, atspre_g0int_eq_int(arg0, tmp51__1)) ;

ATSfunbody_end()
ATSreturn(tmpret50__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__19__1] */

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$19$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4629)
tmparg = S2Evar(tk(4629))
tmpsub = Some(tk(4629) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp51__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret50__2, atspre_g0int_eq_int(arg0, tmp51__2)) ;

ATSfunbody_end()
ATSreturn(tmpret50__2) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__19__2] */

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11831(line=601, offs=3) -- 11870(line=601, offs=42)
*/
/*
local: 
global: eq_g0int_int$19$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4629)
tmparg = S2Evar(tk(4629))
tmpsub = Some(tk(4629) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp51__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11816(line=600, offs=1) -- 11870(line=601, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11857(line=601, offs=29) -- 11868(line=601, offs=40)
*/
ATSINSmove(tmp51__3, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11840(line=601, offs=12) -- 11870(line=601, offs=42)
*/
ATSINSmove(tmpret50__3, atspre_g0int_eq_int(arg0, tmp51__3)) ;

ATSfunbody_end()
ATSreturn(tmpret50__3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__19__3] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_tmp_057_assigns_057_00_057_MySolution_057_assign00_sol_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_00_057_MySolution_057_assign00_sol_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_tmp_057_assigns_057_00_057_MySolution_057_assign00_sol_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_tmp_057_assigns_057_00_057_MySolution_057_assign00_sol_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_tmp_057_assigns_057_00_057_MySolution_057_assign00_sol_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_tmp_057_assigns_057_00_057_MySolution_057_assign00_sol_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
