/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-4-7: 18h: 5m
**
*/

function
__patsfun_16__16__1__closurerize(env0)
{
  return [function(cenv) { return __patsfun_16__16__1(cenv[1]); }, env0];
}


function
__patsfun_20__20__1__closurerize()
{
  return [function(cenv) { return __patsfun_20__20__1(); }];
}


function
__patsfun_27__27__1__closurerize()
{
  return [function(cenv, arg0) { return __patsfun_27__27__1(arg0); }];
}


function
__patsfun_34__34__1__closurerize(env0, env1)
{
  return [function(cenv) { return __patsfun_34__34__1(cenv[1], cenv[2]); }, env0, env1];
}


function
QueenPuzzle()
{
//
// knd = 0
  var tmpret22
  var tmp87
  var tmplab, tmplab_js
//
  // __patsflab_QueenPuzzle
  tmp87 = null;
  tmpret22 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__7__1(tmp87);
  return tmpret22;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__7__1(arg0)
{
//
// knd = 0
  var tmpret23__1
  var tmp24__1
  var tmp25__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__solve
  tmp24__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__memo_get__9__1(arg0);
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab4
      if(ATSCKptrisnull(tmp24__1)) { tmplab_js = 4; break; }
      case 2: // __atstmplab5
      tmp25__1 = tmp24__1[0];
      // ATSINSfreecon(tmp24__1);
      tmpret23__1 = tmp25__1;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab6
      case 4: // __atstmplab7
      tmpret23__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__eval__11__1(arg0);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret23__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__memo_get__9__1(arg0)
{
//
// knd = 0
  var tmpret29__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__solve__memo_get
  tmpret29__1 = null;
  return tmpret29__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__eval__11__1(arg0)
{
//
// knd = 0
  var tmpret31__1
  var tmp32__1
  var tmp33__1
  var tmp34__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__solve__eval
  tmp32__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__base_test__0__1(arg0);
  if(tmp32__1) {
    tmpret31__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__base_solve__1__1(arg0);
  } else {
    tmp33__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__divide__2__1(arg0);
    tmp34__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__conquer__26__1(arg0, tmp33__1);
    _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__eval__memo_set__37__1(arg0, tmp34__1);
    tmpret31__1 = tmp34__1;
  } // endif
  return tmpret31__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__base_test__0__1(arg0)
{
//
// knd = 0
  var tmpret0__1
  var tmp1__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__base_test
  tmp1__1 = ats2jspre_ML_list0_length(arg0);
  tmpret0__1 = ats2jspre_eq_int1_int1(tmp1__1, 8);
  return tmpret0__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__base_solve__1__1(arg0)
{
//
// knd = 0
  var tmpret2__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__base_solve
  tmpret2__1 = ats2jspre_stream_make_sing__15__1(arg0);
  return tmpret2__1;
} // end-of-function


function
ats2jspre_stream_make_sing__15__1(arg0)
{
//
// knd = 0
  var tmpret44__1
  var tmplab, tmplab_js
//
  // __patsflab_stream_make_sing
  tmpret44__1 = ATSPMVlazyval(__patsfun_16__16__1__closurerize(arg0));
  return tmpret44__1;
} // end-of-function


function
__patsfun_16__16__1(env0)
{
//
// knd = 0
  var tmpret45__1
  var tmp46__1
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_16
  tmp46__1 = ats2jspre_stream_make_nil__19__1();
  tmpret45__1 = [env0, tmp46__1];
  return tmpret45__1;
} // end-of-function


function
ats2jspre_stream_make_nil__19__1()
{
//
// knd = 0
  var tmpret50__1
  var tmplab, tmplab_js
//
  // __patsflab_stream_make_nil
  tmpret50__1 = ATSPMVlazyval(__patsfun_20__20__1__closurerize());
  return tmpret50__1;
} // end-of-function


function
__patsfun_20__20__1()
{
//
// knd = 0
  var tmpret51__1
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_20
  tmpret51__1 = null;
  return tmpret51__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__divide__2__1(arg0)
{
//
// knd = 0
  var tmpret3__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__divide
  tmpret3__1 = aux_3__3__1(arg0, 0);
  return tmpret3__1;
} // end-of-function


function
aux_3__3__1(env0, arg0)
{
//
// knd = 1
  var apy0
  var tmpret4__1
  var tmp13__1
  var tmp14__1
  var tmp15__1
  var tmp16__1
  var tmp17__1
  var tmp18__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_aux_3
    tmp13__1 = ats2jspre_lt_int0_int0(arg0, 8);
    if(tmp13__1) {
      tmp14__1 = test_4__4__1(arg0, env0, 1);
      if(tmp14__1) {
        tmp15__1 = [arg0, env0];
        tmp17__1 = ats2jspre_add_int0_int0(arg0, 1);
        tmp16__1 = aux_3__3__1(env0, tmp17__1);
        tmpret4__1 = [tmp15__1, tmp16__1];
      } else {
        tmp18__1 = ats2jspre_add_int0_int0(arg0, 1);
        // ATStailcalseq_beg
        apy0 = tmp18__1;
        arg0 = apy0;
        funlab_js = 1; // __patsflab_aux_3
        // ATStailcalseq_end
      } // endif
    } else {
      tmpret4__1 = null;
    } // endif
    if (funlab_js > 0) continue; else return tmpret4__1;
  } // endwhile-fun
} // end-of-function


function
test_4__4__1(env0, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret5__1
  var tmp6__1
  var tmp7__1
  var tmp8__1
  var tmp9__1
  var tmp10__1
  var tmp11__1
  var tmp12__1
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_test_4
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab0
        if(ATSCKptriscons(arg0)) { tmplab_js = 4; break; }
        case 2: // __atstmplab1
        tmpret5__1 = true;
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab2
        case 4: // __atstmplab3
        tmp6__1 = arg0[0];
        tmp7__1 = arg0[1];
        tmp9__1 = ats2jspre_neq_int0_int0(tmp6__1, env0);
        if(tmp9__1) {
          tmp11__1 = ats2jspre_sub_int0_int0(tmp6__1, env0);
          tmp10__1 = ats2jspre_abs_int0(tmp11__1);
          tmp8__1 = ats2jspre_neq_int0_int0(tmp10__1, arg1);
        } else {
          tmp8__1 = false;
        } // endif
        if(tmp8__1) {
          tmp12__1 = ats2jspre_add_int0_int0(arg1, 1);
          // ATStailcalseq_beg
          apy0 = tmp7__1;
          apy1 = tmp12__1;
          arg0 = apy0;
          arg1 = apy1;
          funlab_js = 1; // __patsflab_test_4
          // ATStailcalseq_end
        } else {
          tmpret5__1 = false;
        } // endif
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return tmpret5__1;
  } // endwhile-fun
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__conquer__26__1(arg0, arg1)
{
//
// knd = 0
  var tmpret70__1
  var tmp71__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__conquer
  tmp71__1 = ats2jspre_ML_list0_map(arg1, __patsfun_27__27__1__closurerize());
  tmpret70__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__conquer__combine__5__1(arg0, tmp71__1);
  return tmpret70__1;
} // end-of-function


function
__patsfun_27__27__1(arg0)
{
//
// knd = 0
  var tmpret72__1
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_27
  tmpret72__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve_rec__30__1(arg0);
  return tmpret72__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve_rec__30__1(arg0)
{
//
// knd = 0
  var tmpret76__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__solve_rec
  tmpret76__1 = _057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__7__1(arg0);
  return tmpret76__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__conquer__combine__5__1(arg0, arg1)
{
//
// knd = 0
  var tmpret19__1
  var tmp20__1
  var tmp21__1
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__conquer__combine
  tmp20__1 = ats2jspre_stream_make_list0(arg1);
  tmp21__1 = ats2jspre_stream_concat(tmp20__1);
  tmpret19__1 = ats2jspre_stream_make_cons__33__1(arg0, tmp21__1);
  return tmpret19__1;
} // end-of-function


function
ats2jspre_stream_make_cons__33__1(arg0, arg1)
{
//
// knd = 0
  var tmpret81__1
  var tmplab, tmplab_js
//
  // __patsflab_stream_make_cons
  tmpret81__1 = ATSPMVlazyval(__patsfun_34__34__1__closurerize(arg0, arg1));
  return tmpret81__1;
} // end-of-function


function
__patsfun_34__34__1(env0, env1)
{
//
// knd = 0
  var tmpret82__1
  var tmplab, tmplab_js
//
  // __patsflab___patsfun_34
  tmpret82__1 = [env0, env1];
  return tmpret82__1;
} // end-of-function


function
_057_root_057_ATS_055_Postiats_057_contrib_057_libatscc2js_057_BUCS320_057_DivideConquer_057_DATS_057_DivideConquer_056_dats__DivideConquer__solve__eval__memo_set__37__1(arg0, arg1)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_DivideConquer__solve__eval__memo_set
  // ATSINSmove_void
  return/*_void*/;
} // end-of-function


/* ****** ****** */

/* end-of-compilation-unit */
