/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-4-7: 18h: 5m
**
*/

/* ATSextcode_beg() */
//
var
theCanvas =
document.getElementById
("theShowStream-canvas");
var
theCanvas_ctx2d = theCanvas.getContext('2d');
//
var _ = theCanvas_ctx2d.font = "40px Georgia";
//
function
theCanvas_get() { return theCanvas; };
function
theCanvas_ctx2d_get() { return theCanvas_ctx2d; };
//
/* ATSextcode_end() */

var theCounter3_baconjs_statmp0

var theCounter3_baconjs_statmp1

var theCounter3_baconjs_statmp8

var theCounter3_baconjs_statmp9

var theCounter3_baconjs_statmp10

var theCounter3_baconjs_statmp11

var theCounter3_baconjs_statmp12

var theCounter3_baconjs_statmp121

var theCounter3_baconjs_statmp122

var theCounter3_baconjs_statmp123

var theCounter3_baconjs_statmp124

var theCounter3_baconjs_statmp125

var theCounter3_baconjs_statmp126

var theCounter3_baconjs_statmp127

var theCounter3_baconjs_statmp128

var theCounter3_baconjs_statmp130

var theCounter3_baconjs_statmp131

var theCounter3_baconjs_statmp132

var theCounter3_baconjs_statmp134

var theCounter3_baconjs_statmp135

var theCounter3_baconjs_statmp136

var theCounter3_baconjs_statmp138

var theCounter3_baconjs_statmp139

var theCounter3_baconjs_statmp140

var theCounter3_baconjs_statmp142

var theCounter3_baconjs_statmp143

var theCounter3_baconjs_statmp144

var theCounter3_baconjs_statmp146

var theCounter3_baconjs_statmp147

var theCounter3_baconjs_statmp148

var theCounter3_baconjs_statmp150

var theCounter3_baconjs_statmp151

var theCounter3_baconjs_statmp152

var theCounter3_baconjs_statmp154

var theCounter3_baconjs_statmp155

var theCounter3_baconjs_statmp156

var theCounter3_baconjs_statmp159

var theCounter3_baconjs_statmp161

var theCounter3_baconjs_statmp163

var theCounter3_baconjs_statmp164

var theCounter3_baconjs_statmp165

var theCounter3_baconjs_statmp166

var theCounter3_baconjs_statmp167

var theCounter3_baconjs_statmp168

var theCounter3_baconjs_statmp170

var theCounter3_baconjs_statmp171

var theCounter3_baconjs_statmp172

var theCounter3_baconjs_statmp174

var theCounter3_baconjs_statmp175

var theCounter3_baconjs_statmp176

var theCounter3_baconjs_statmp178

var theCounter3_baconjs_statmp179

var theCounter3_baconjs_statmp192

function
theCounter3_baconjs_patsfun_18__closurerize(env0, env1)
{
  return [function(cenv) { return theCounter3_baconjs_patsfun_18(cenv[1], cenv[2]); }, env0, env1];
}


function
theCounter3_baconjs_patsfun_19__closurerize(env0, env1)
{
  return [function(cenv) { return theCounter3_baconjs_patsfun_19(cenv[1], cenv[2]); }, env0, env1];
}


function
theCounter3_baconjs_patsfun_20__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_20(arg0); }];
}


function
theCounter3_baconjs_patsfun_21__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_21(arg0); }];
}


function
theCounter3_baconjs_patsfun_22__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_22(arg0); }];
}


function
theCounter3_baconjs_patsfun_23__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_23(arg0); }];
}


function
theCounter3_baconjs_patsfun_24__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_24(arg0); }];
}


function
theCounter3_baconjs_patsfun_25__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_25(arg0); }];
}


function
theCounter3_baconjs_patsfun_26__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_26(arg0); }];
}


function
theCounter3_baconjs_patsfun_27__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_27(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_28__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_28(arg0); }];
}


function
theCounter3_baconjs_patsfun_29__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_29(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_30__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_30(arg0); }];
}


function
theCounter3_baconjs_patsfun_31__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_31(arg0); }];
}


function
theCounter3_baconjs_patsfun_32__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_32(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_33__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_33(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_34__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_34(arg0); }];
}


function
theShow_count_get()
{
//
// knd = 0
  var tmpret2
  var tmplab, tmplab_js
//
  // __patsflab_theShow_count_get
  tmpret2 = ats2jspre_ref_get_elt(theCounter3_baconjs_statmp0);
  return tmpret2;
} // end-of-function


function
theShow_count_set(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theShow_count_set
  ats2jspre_ref_set_elt(theCounter3_baconjs_statmp0, arg0);
  return/*_void*/;
} // end-of-function


function
theShow_update(arg0)
{
//
// knd = 0
  var tmp5
  var tmp6
  var tmplab, tmplab_js
//
  // __patsflab_theShow_update
  tmp5 = theShow_count_get();
  tmp6 = ats2jspre_neq_int0_int0(tmp5, arg0);
  if(tmp6) {
    theShow_count_set(arg0);
    theShow_update_do(arg0);
  } else {
    // ATSINSmove_void
  } // endif
  return/*_void*/;
} // end-of-function


function
theStateStream_show()
{
//
// knd = 0
  var tmp14
  var tmp15
  var tmp16
  var tmp17
  var tmp18
  var tmp20
  var tmplab, tmplab_js
//
  // __patsflab_theStateStream_show
  tmp14 = ats2jspre_ref_get_elt(theCounter3_baconjs_statmp12);
  tmp15 = ATSPMVlazyval_eval(tmp14); 
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab0
      if(ATSCKptriscons(tmp15)) { tmplab_js = 4; break; }
      case 2: // __atstmplab1
      // ATSINSmove_void
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab2
      case 4: // __atstmplab3
      tmp16 = tmp15[0];
      tmp17 = tmp15[1];
      tmp18 = ats2jspre_ref_get_elt(theCounter3_baconjs_statmp10);
      tmp20 = ats2jspre_add_int0_int0(tmp18, 1);
      ats2jspre_ref_set_elt(theCounter3_baconjs_statmp10, tmp20);
      ats2jspre_ref_set_elt(theCounter3_baconjs_statmp12, tmp17);
      theState_show(tmp16);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
theStateStream_get_at(arg0)
{
//
// knd = 0
  var tmp29
  var tmp30
  var tmp31
  var tmp32
  var tmp33
  var tmplab, tmplab_js
//
  // __patsflab_theStateStream_get_at
  tmp29 = ats2jspre_ref_get_elt(theCounter3_baconjs_statmp10);
  tmp30 = ats2jspre_neq_int0_int0(tmp29, arg0);
  if(tmp30) {
    tmp31 = ats2jspre_ref_get_elt(theCounter3_baconjs_statmp8);
    tmp33 = ats2jspre_gte_int1_int1(arg0, 0);
    if(tmp33) {
      tmp32 = theCounter3_baconjs_loop_5(tmp31, arg0);
    } else {
      tmp32 = tmp31;
    } // endif
    ats2jspre_ref_set_elt(theCounter3_baconjs_statmp10, arg0);
    ats2jspre_ref_set_elt(theCounter3_baconjs_statmp12, tmp32);
  } else {
    // ATSINSmove_void
  } // endif
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_loop_5(arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmpret23
  var tmp24
  var tmp25
  var tmp27
  var tmp28
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_theCounter3_baconjs_loop_5
    tmp24 = ats2jspre_gt_int1_int1(arg1, 0);
    if(tmp24) {
      tmp25 = ATSPMVlazyval_eval(arg0); 
      // ATScaseofseq_beg
      tmplab_js = 1;
      while(true) {
        tmplab = tmplab_js; tmplab_js = 0;
        switch(tmplab) {
          // ATSbranchseq_beg
          case 1: // __atstmplab4
          if(ATSCKptriscons(tmp25)) { tmplab_js = 4; break; }
          case 2: // __atstmplab5
          tmpret23 = arg0;
          break;
          // ATSbranchseq_end
          // ATSbranchseq_beg
          case 3: // __atstmplab6
          case 4: // __atstmplab7
          tmp27 = tmp25[1];
          tmp28 = ats2jspre_sub_int1_int1(arg1, 1);
          // ATStailcalseq_beg
          apy0 = tmp27;
          apy1 = tmp28;
          arg0 = apy0;
          arg1 = apy1;
          funlab_js = 1; // __patsflab_theCounter3_baconjs_loop_5
          // ATStailcalseq_end
          break;
          // ATSbranchseq_end
        } // end-of-switch
        if (tmplab_js === 0) break;
      } // endwhile
      // ATScaseofseq_end
    } else {
      tmpret23 = arg0;
    } // endif
    if (funlab_js > 0) continue; else return tmpret23;
  } // endwhile-fun
} // end-of-function


function
theShow_update_do(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theShow_update_do
  theStateStream_get_at(arg0);
  theStateStream_show();
  return/*_void*/;
} // end-of-function


function
_057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theShow_update_056_dats__draw_board(arg0)
{
//
// knd = 0
  var tmp41
  var tmp42
  var tmp43
  var tmp44
  var tmp45
  var tmp46
  var tmp47
  var tmp48
  var tmplab, tmplab_js
//
  // __patsflab_draw_board
  tmp42 = ats2jspre_mul_double_int(1.0, 400);
  tmp41 = ats2jspre_div_double_int(tmp42, 8);
  tmp45 = ats2jspre_sub_int1_int1(600, 400);
  tmp44 = ats2jspre_mul_double_int(1.0, tmp45);
  tmp43 = ats2jspre_div_double_int(tmp44, 2);
  tmp48 = ats2jspre_sub_int1_int1(420, 400);
  tmp47 = ats2jspre_mul_double_int(1.0, tmp48);
  tmp46 = ats2jspre_div_double_int(tmp47, 2);
  theCounter3_baconjs_auxrows_11(arg0, tmp41, tmp43, tmp46, 0, "#7f7f7f", "#efefef");
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_auxrow_10(env0, env1, env2, env3, arg0, arg1, arg2, arg3)
{
//
// knd = 1
  var apy0
  var apy1
  var apy2
  var apy3
  var tmp50
  var tmp54
  var tmp55
  var tmp56
  var tmp57
  var tmp60
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_theCounter3_baconjs_auxrow_10
    tmp50 = ats2jspre_lt_int0_int0(arg0, 8);
    if(tmp50) {
      ats2js_HTML5_canvas2d_set_fillStyle_string(env0, arg2);
      ats2js_HTML5_canvas2d_beginPath(env0);
      tmp55 = ats2jspre_mul_int_double(arg0, env1);
      tmp54 = ats2jspre_add_double_double(env2, tmp55);
      tmp57 = ats2jspre_mul_int_double(arg1, env1);
      tmp56 = ats2jspre_add_double_double(env3, tmp57);
      ats2js_HTML5_canvas2d_rect(env0, tmp54, tmp56, env1, env1);
      ats2js_HTML5_canvas2d_closePath(env0);
      ats2js_HTML5_canvas2d_fill(env0);
      tmp60 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp60;
      apy1 = arg1;
      apy2 = arg3;
      apy3 = arg2;
      arg0 = apy0;
      arg1 = apy1;
      arg2 = apy2;
      arg3 = apy3;
      funlab_js = 1; // __patsflab_theCounter3_baconjs_auxrow_10
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // endif
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
theCounter3_baconjs_auxrows_11(env0, env1, env2, env3, arg0, arg1, arg2)
{
//
// knd = 1
  var apy0
  var apy1
  var apy2
  var tmp62
  var tmp64
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_theCounter3_baconjs_auxrows_11
    tmp62 = ats2jspre_lt_int0_int0(arg0, 8);
    if(tmp62) {
      theCounter3_baconjs_auxrow_10(env0, env1, env2, env3, 0, arg0, arg1, arg2);
      tmp64 = ats2jspre_add_int0_int0(arg0, 1);
      // ATStailcalseq_beg
      apy0 = tmp64;
      apy1 = arg2;
      apy2 = arg1;
      arg0 = apy0;
      arg1 = apy1;
      arg2 = apy2;
      funlab_js = 1; // __patsflab_theCounter3_baconjs_auxrows_11
      // ATStailcalseq_end
    } else {
      // ATSINSmove_void
    } // endif
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
_057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theShow_update_056_dats__draw_queen(arg0, arg1, arg2)
{
//
// knd = 0
  var tmp66
  var tmp67
  var tmp68
  var tmp69
  var tmp70
  var tmp71
  var tmp72
  var tmp73
  var tmp74
  var tmp75
  var tmp76
  var tmp77
  var tmp78
  var tmp82
  var tmplab, tmplab_js
//
  // __patsflab_draw_queen
  tmp67 = ats2jspre_mul_double_int(1.0, 400);
  tmp66 = ats2jspre_div_double_int(tmp67, 8);
  tmp70 = ats2jspre_sub_int1_int1(600, 400);
  tmp69 = ats2jspre_mul_double_int(1.0, tmp70);
  tmp68 = ats2jspre_div_double_int(tmp69, 2);
  tmp72 = ats2jspre_div_double_int(tmp66, 2);
  tmp71 = ats2jspre_add_double_double(arg1, tmp72);
  tmp75 = ats2jspre_mul_int_double(arg2, tmp66);
  tmp74 = ats2jspre_add_double_double(tmp68, tmp75);
  tmp76 = ats2jspre_div_double_int(tmp66, 2);
  tmp73 = ats2jspre_add_double_double(tmp74, tmp76);
  tmp78 = ats2jspre_mul_double_double(0.90, tmp66);
  tmp77 = ats2jspre_div_double_int(tmp78, 2);
  ats2js_HTML5_canvas2d_set_fillStyle_string(arg0, "#000000");
  ats2js_HTML5_canvas2d_beginPath(arg0);
  tmp82 = ats2jspre_mul_int_double(2, 3.141592653589800221);
  ats2js_HTML5_canvas2d_arc(arg0, tmp73, tmp71, tmp77, 0.0, tmp82, true);
  ats2js_HTML5_canvas2d_closePath(arg0);
  ats2js_HTML5_canvas2d_fill(arg0);
  return/*_void*/;
} // end-of-function


function
_057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theShow_update_056_dats__draw_queens(arg0, arg1)
{
//
// knd = 0
  var tmp85
  var tmp86
  var tmp87
  var tmp88
  var tmp89
  var tmplab, tmplab_js
//
  // __patsflab_draw_queens
  tmp86 = ats2jspre_mul_double_int(1.0, 400);
  tmp85 = ats2jspre_div_double_int(tmp86, 8);
  tmp89 = ats2jspre_sub_int1_int1(420, 400);
  tmp88 = ats2jspre_mul_double_int(1.0, tmp89);
  tmp87 = ats2jspre_div_double_int(tmp88, 2);
  theCounter3_baconjs_auxlst_14(arg0, tmp85, tmp87, arg1);
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_auxlst_14(env0, env1, arg0, arg1)
{
//
// knd = 1
  var apy0
  var apy1
  var tmp91
  var tmp92
  var tmp94
  var funlab_js
  var tmplab, tmplab_js
//
  while(true) {
    funlab_js = 0;
    // __patsflab_theCounter3_baconjs_auxlst_14
    // ATScaseofseq_beg
    tmplab_js = 1;
    while(true) {
      tmplab = tmplab_js; tmplab_js = 0;
      switch(tmplab) {
        // ATSbranchseq_beg
        case 1: // __atstmplab8
        if(ATSCKptriscons(arg1)) { tmplab_js = 4; break; }
        case 2: // __atstmplab9
        // ATSINSmove_void
        break;
        // ATSbranchseq_end
        // ATSbranchseq_beg
        case 3: // __atstmplab10
        case 4: // __atstmplab11
        tmp91 = arg1[0];
        tmp92 = arg1[1];
        _057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theShow_update_056_dats__draw_queen(env0, arg0, tmp91);
        tmp94 = ats2jspre_add_double_double(arg0, env1);
        // ATStailcalseq_beg
        apy0 = tmp94;
        apy1 = tmp92;
        arg0 = apy0;
        arg1 = apy1;
        funlab_js = 1; // __patsflab_theCounter3_baconjs_auxlst_14
        // ATStailcalseq_end
        break;
        // ATSbranchseq_end
      } // end-of-switch
      if (tmplab_js === 0) break;
    } // endwhile
    // ATScaseofseq_end
    if (funlab_js > 0) continue; else return/*_void*/;
  } // endwhile-fun
} // end-of-function


function
theState_show(arg0)
{
//
// knd = 0
  var tmp96
  var tmp97
  var tmp98
  var tmp99
  var tmp100
  var tmp103
  var tmplab, tmplab_js
//
  // __patsflab_theState_show
  tmp96 = theCanvas_ctx2d_get();
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab12
      if(!ATSCKpat_con1(arg0, 0)) { tmplab_js = 4; break; }
      case 2: // __atstmplab13
      tmp97 = arg0[1];
      tmp100 = ats2jspre_String(tmp97);
      tmp99 = ats2jspre_string_append("solution #", tmp100);
      ats2jspre_alert(tmp99);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab14
      case 4: // __atstmplab15
      tmp98 = arg0[1];
      ats2js_HTML5_canvas2d_clearRect(tmp96, 0, 0, 600, 420);
      _057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theShow_update_056_dats__draw_board(tmp96);
      tmp103 = ats2jspre_ML_list0_reverse(tmp98);
      _057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theShow_update_056_dats__draw_queens(tmp96, tmp103);
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
theStateStream_gen()
{
//
// knd = 0
  var tmpret104
  var tmp120
  var tmplab, tmplab_js
//
  // __patsflab_theStateStream_gen
  tmp120 = QueenPuzzle();
  tmpret104 = theCounter3_baconjs_aux_17(tmp120, 1);
  return tmpret104;
} // end-of-function


function
theCounter3_baconjs_aux_17(arg0, arg1)
{
//
// knd = 0
  var tmpret105
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_aux_17
  tmpret105 = ATSPMVlazyval(theCounter3_baconjs_patsfun_18__closurerize(arg0, arg1));
  return tmpret105;
} // end-of-function


function
theCounter3_baconjs_patsfun_18(env0, env1)
{
//
// knd = 0
  var tmpret106
  var tmp107
  var tmp108
  var tmp109
  var tmp110
  var tmp111
  var tmp112
  var tmp113
  var tmp118
  var tmp119
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_18
  tmp107 = ATSPMVlazyval_eval(env0); 
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab16
      if(ATSCKptriscons(tmp107)) { tmplab_js = 4; break; }
      case 2: // __atstmplab17
      tmpret106 = null;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab18
      case 4: // __atstmplab19
      tmp108 = tmp107[0];
      tmp109 = tmp107[1];
      tmp111 = ats2jspre_ML_list0_length(tmp108);
      tmp110 = ats2jspre_eq_int1_int1(tmp111, 8);
      if(tmp110) {
        tmp112 = [1, tmp108];
        tmp113 = ATSPMVlazyval(theCounter3_baconjs_patsfun_19__closurerize(env1, tmp109));
        tmpret106 = [tmp112, tmp113];
      } else {
        tmp118 = [1, tmp108];
        tmp119 = theCounter3_baconjs_aux_17(tmp109, env1);
        tmpret106 = [tmp118, tmp119];
      } // endif
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret106;
} // end-of-function


function
theCounter3_baconjs_patsfun_19(env0, env1)
{
//
// knd = 0
  var tmpret114
  var tmp115
  var tmp116
  var tmp117
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_19
  tmp115 = [0, env0];
  tmp117 = ats2jspre_add_int0_int0(env0, 1);
  tmp116 = theCounter3_baconjs_aux_17(env1, tmp117);
  tmpret114 = [tmp115, tmp116];
  return tmpret114;
} // end-of-function


function
theCounter3_baconjs_patsfun_20(arg0)
{
//
// knd = 0
  var tmpret129
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_20
  tmpret129 = 0;
  return tmpret129;
} // end-of-function


function
theCounter3_baconjs_patsfun_21(arg0)
{
//
// knd = 0
  var tmpret133
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_21
  tmpret133 = 1;
  return tmpret133;
} // end-of-function


function
theCounter3_baconjs_patsfun_22(arg0)
{
//
// knd = 0
  var tmpret137
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_22
  tmpret137 = 3;
  return tmpret137;
} // end-of-function


function
theCounter3_baconjs_patsfun_23(arg0)
{
//
// knd = 0
  var tmpret141
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_23
  tmpret141 = 5;
  return tmpret141;
} // end-of-function


function
theCounter3_baconjs_patsfun_24(arg0)
{
//
// knd = 0
  var tmpret145
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_24
  tmpret145 = 6;
  return tmpret145;
} // end-of-function


function
theCounter3_baconjs_patsfun_25(arg0)
{
//
// knd = 0
  var tmpret149
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_25
  tmpret149 = 5;
  return tmpret149;
} // end-of-function


function
theCounter3_baconjs_patsfun_26(arg0)
{
//
// knd = 0
  var tmpret153
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_26
  tmpret153 = 6;
  return tmpret153;
} // end-of-function


function
theCounter3_baconjs_patsfun_27(arg0, arg1)
{
//
// knd = 0
  var tmpret157
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_27
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab20
      if(!ATSCKpat_con0(arg1, 0)) { tmplab_js = 3; break; }
      case 2: // __atstmplab21
      tmpret157 = ats2jspre_neg_bool0(arg0);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab22
      tmpret157 = false;
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret157;
} // end-of-function


function
theCounter3_baconjs_patsfun_28(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_28
  if(arg0) {
    $("#theAuto_btn").addClass("btn-primary");
  } else {
    $("#theAuto_btn").removeClass("btn-primary");
  } // endif
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_patsfun_29(arg0, arg1)
{
//
// knd = 0
  var tmpret162
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_29
  if(arg0) {
    tmpret162 = 7;
  } else {
    tmpret162 = arg1;
  } // endif
  return tmpret162;
} // end-of-function


function
theCounter3_baconjs_patsfun_30(arg0)
{
//
// knd = 0
  var tmpret169
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_30
  tmpret169 = 7;
  return tmpret169;
} // end-of-function


function
theCounter3_baconjs_patsfun_31(arg0)
{
//
// knd = 0
  var tmpret173
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_31
  tmpret173 = 7;
  return tmpret173;
} // end-of-function


function
theCounter3_baconjs_patsfun_32(arg0, arg1)
{
//
// knd = 0
  var tmpret177
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_32
  if(arg1) {
    tmpret177 = arg0;
  } else {
    tmpret177 = 7;
  } // endif
  return tmpret177;
} // end-of-function


function
theCounter3_baconjs_patsfun_33(arg0, arg1)
{
//
// knd = 0
  var tmpret180
  var tmp181
  var tmp182
  var tmp183
  var tmp184
  var tmp185
  var tmp186
  var tmp187
  var tmp188
  var tmp189
  var tmp190
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_33
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab23
      if(!ATSCKpat_con0(arg1, 1)) { tmplab_js = 3; break; }
      case 2: // __atstmplab24
      tmp181 = ats2jspre_add_int0_int0(arg0, 1);
      tmp182 = ats2jspre_gte_int0_int0(tmp181, 1000000);
      if(tmp182) {
        tmpret180 = ats2jspre_sub_int0_int0(tmp181, 1000000);
      } else {
        tmpret180 = tmp181;
      } // endif
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab25
      if(!ATSCKpat_con0(arg1, 2)) { tmplab_js = 5; break; }
      case 4: // __atstmplab26
      tmp183 = ats2jspre_add_int0_int0(arg0, 5);
      tmp184 = ats2jspre_gte_int0_int0(tmp183, 1000000);
      if(tmp184) {
        tmpret180 = ats2jspre_sub_int0_int0(tmp183, 1000000);
      } else {
        tmpret180 = tmp183;
      } // endif
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab27
      if(!ATSCKpat_con0(arg1, 3)) { tmplab_js = 7; break; }
      case 6: // __atstmplab28
      tmp185 = ats2jspre_sub_int0_int0(arg0, 1);
      tmp186 = ats2jspre_gte_int0_int0(tmp185, 0);
      if(tmp186) {
        tmpret180 = tmp185;
      } else {
        tmpret180 = ats2jspre_add_int0_int0(1000000, tmp185);
      } // endif
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab29
      if(!ATSCKpat_con0(arg1, 4)) { tmplab_js = 9; break; }
      case 8: // __atstmplab30
      tmp187 = ats2jspre_sub_int0_int0(arg0, 5);
      tmp188 = ats2jspre_gte_int0_int0(tmp187, 0);
      if(tmp188) {
        tmpret180 = tmp187;
      } else {
        tmpret180 = ats2jspre_add_int0_int0(1000000, tmp187);
      } // endif
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9: // __atstmplab31
      if(!ATSCKpat_con0(arg1, 5)) { tmplab_js = 11; break; }
      case 10: // __atstmplab32
      tmp190 = ats2jspre_JSmath_random();
      tmp189 = ats2jspre_mul_int_double(1000000, tmp190);
      tmpret180 = ats2jspre_double2int(tmp189);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 11: // __atstmplab33
      if(!ATSCKpat_con0(arg1, 0)) { tmplab_js = 13; break; }
      case 12: // __atstmplab34
      tmpret180 = arg0;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 13: // __atstmplab35
      if(!ATSCKpat_con0(arg1, 6)) { tmplab_js = 15; break; }
      case 14: // __atstmplab36
      tmpret180 = 0;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 15: // __atstmplab37
      case 16: // __atstmplab38
      tmpret180 = arg0;
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret180;
} // end-of-function


function
theCounter3_baconjs_patsfun_34(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_34
  theShow_update(arg0);
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag = 0;

function
_057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag(383))
  if(ATSCKiseqz(_057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag)) {
    _057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag = 1 ; // flag is set
    theCounter3_baconjs_statmp1 = ats2jspre_neg_int1(1);
    theCounter3_baconjs_statmp0 = ats2jspre_ref(theCounter3_baconjs_statmp1);
    theCounter3_baconjs_statmp9 = theStateStream_gen();
    theCounter3_baconjs_statmp8 = ats2jspre_ref(theCounter3_baconjs_statmp9);
    theCounter3_baconjs_statmp10 = ats2jspre_ref(0);
    theCounter3_baconjs_statmp11 = ats2jspre_ref_get_elt(theCounter3_baconjs_statmp8);
    theCounter3_baconjs_statmp12 = ats2jspre_ref(theCounter3_baconjs_statmp11);
    theCounter3_baconjs_statmp121 = $("#theAuto_btn").asEventStream("click");
    theCounter3_baconjs_statmp122 = $("#theNext_btn").asEventStream("click");
    theCounter3_baconjs_statmp123 = $("#thePrev_btn").asEventStream("click");
    theCounter3_baconjs_statmp124 = $("#theRand_btn").asEventStream("click");
    theCounter3_baconjs_statmp125 = $("#theReset_btn").asEventStream("click");
    theCounter3_baconjs_statmp128 = 0;
    theCounter3_baconjs_statmp127 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp121, theCounter3_baconjs_statmp128);
    theCounter3_baconjs_statmp126 = theCounter3_baconjs_statmp127[0](theCounter3_baconjs_statmp127, theCounter3_baconjs_patsfun_20__closurerize());
    theCounter3_baconjs_statmp132 = 0;
    theCounter3_baconjs_statmp131 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp122, theCounter3_baconjs_statmp132);
    theCounter3_baconjs_statmp130 = theCounter3_baconjs_statmp131[0](theCounter3_baconjs_statmp131, theCounter3_baconjs_patsfun_21__closurerize());
    theCounter3_baconjs_statmp136 = 0;
    theCounter3_baconjs_statmp135 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp123, theCounter3_baconjs_statmp136);
    theCounter3_baconjs_statmp134 = theCounter3_baconjs_statmp135[0](theCounter3_baconjs_statmp135, theCounter3_baconjs_patsfun_22__closurerize());
    theCounter3_baconjs_statmp140 = 0;
    theCounter3_baconjs_statmp139 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp124, theCounter3_baconjs_statmp140);
    theCounter3_baconjs_statmp138 = theCounter3_baconjs_statmp139[0](theCounter3_baconjs_statmp139, theCounter3_baconjs_patsfun_23__closurerize());
    theCounter3_baconjs_statmp144 = 0;
    theCounter3_baconjs_statmp143 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp125, theCounter3_baconjs_statmp144);
    theCounter3_baconjs_statmp142 = theCounter3_baconjs_statmp143[0](theCounter3_baconjs_statmp143, theCounter3_baconjs_patsfun_24__closurerize());
    theCounter3_baconjs_statmp148 = 0;
    theCounter3_baconjs_statmp147 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp138, theCounter3_baconjs_statmp148);
    theCounter3_baconjs_statmp146 = theCounter3_baconjs_statmp147[0](theCounter3_baconjs_statmp147, theCounter3_baconjs_patsfun_25__closurerize());
    theCounter3_baconjs_statmp152 = 0;
    theCounter3_baconjs_statmp151 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp142, theCounter3_baconjs_statmp152);
    theCounter3_baconjs_statmp150 = theCounter3_baconjs_statmp151[0](theCounter3_baconjs_statmp151, theCounter3_baconjs_patsfun_26__closurerize());
    theCounter3_baconjs_statmp154 = ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp130, theCounter3_baconjs_statmp134, theCounter3_baconjs_statmp146);
    theCounter3_baconjs_statmp156 = ats2js_bacon_EStream_merge2(theCounter3_baconjs_statmp126, theCounter3_baconjs_statmp150);
    theCounter3_baconjs_statmp155 = ats2js_bacon_EStream_scan(theCounter3_baconjs_statmp156, false, theCounter3_baconjs_patsfun_27__closurerize());
    theCounter3_baconjs_statmp159 = ats2js_bacon_Property_onValue_method(theCounter3_baconjs_statmp155);
    theCounter3_baconjs_statmp159[0](theCounter3_baconjs_statmp159, theCounter3_baconjs_patsfun_28__closurerize());
    theCounter3_baconjs_statmp161 = ats2js_bacon_Property_sampledBy_estream_cfun(theCounter3_baconjs_statmp155, theCounter3_baconjs_statmp154, theCounter3_baconjs_patsfun_29__closurerize());
    theCounter3_baconjs_statmp164 = ats2js_bacon_Bacon_interval(1500, 0);
    theCounter3_baconjs_statmp163 = ats2js_bacon_Property_sampledBy_estream(theCounter3_baconjs_statmp155, theCounter3_baconjs_statmp164);
    theCounter3_baconjs_statmp168 = 0;
    theCounter3_baconjs_statmp167 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp126, theCounter3_baconjs_statmp168);
    theCounter3_baconjs_statmp166 = theCounter3_baconjs_statmp167[0](theCounter3_baconjs_statmp167, theCounter3_baconjs_patsfun_30__closurerize());
    theCounter3_baconjs_statmp172 = 0;
    theCounter3_baconjs_statmp171 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp150, theCounter3_baconjs_statmp172);
    theCounter3_baconjs_statmp170 = theCounter3_baconjs_statmp171[0](theCounter3_baconjs_statmp171, theCounter3_baconjs_patsfun_31__closurerize());
    theCounter3_baconjs_statmp165 = ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp154, theCounter3_baconjs_statmp166, theCounter3_baconjs_statmp170);
    theCounter3_baconjs_statmp175 = 7;
    theCounter3_baconjs_statmp174 = ats2js_bacon_EStream_toProperty_init(theCounter3_baconjs_statmp165, theCounter3_baconjs_statmp175);
    theCounter3_baconjs_statmp176 = ats2js_bacon_Property_sampledBy_estream_cfun(theCounter3_baconjs_statmp174, theCounter3_baconjs_statmp163, theCounter3_baconjs_patsfun_32__closurerize());
    theCounter3_baconjs_statmp179 = ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp150, theCounter3_baconjs_statmp161, theCounter3_baconjs_statmp176);
    theCounter3_baconjs_statmp178 = ats2js_bacon_EStream_scan(theCounter3_baconjs_statmp179, 0, theCounter3_baconjs_patsfun_33__closurerize());
    theCounter3_baconjs_statmp192 = ats2js_bacon_Property_onValue_method(theCounter3_baconjs_statmp178);
    theCounter3_baconjs_statmp192[0](theCounter3_baconjs_statmp192, theCounter3_baconjs_patsfun_34__closurerize());
  } // endif
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_start()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_tmp_057_assigns_057_08_057_QueenPuzzle_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
theCounter3_baconjs_start();
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
