/*
**
** The C code is generated by [ATS/Postiats-0-3-4]
** The starting compilation time is: 2017-4-20: 21h: 4m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/basics.dats: 392(line=29, offs=1) -- 422(line=29, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/basics.dats: 449(line=33, offs=1) -- 482(line=33, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/basics.dats: 486(line=35, offs=1) -- 516(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/basics.dats: 517(line=36, offs=1) -- 548(line=36, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/basics.dats: 549(line=37, offs=1) -- 581(line=37, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/string.sats: 202(line=16, offs=1) -- 232(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/string.sats: 202(line=16, offs=1) -- 232(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/gvalue.sats: 272(line=20, offs=1) -- 302(line=20, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/gprint.sats: 272(line=20, offs=1) -- 302(line=20, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/gprint.dats: 390(line=29, offs=1) -- 422(line=29, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/gprint.sats: 272(line=20, offs=1) -- 302(line=20, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 390(line=29, offs=1) -- 430(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 455(line=35, offs=1) -- 485(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 510(line=39, offs=1) -- 543(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 570(line=43, offs=1) -- 601(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 602(line=44, offs=1) -- 635(line=44, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/filebas.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 662(line=48, offs=1) -- 692(line=48, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 719(line=52, offs=1) -- 751(line=52, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 752(line=53, offs=1) -- 788(line=53, offs=37)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 392(line=29, offs=1) -- 432(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 459(line=35, offs=1) -- 489(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 516(line=39, offs=1) -- 549(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 576(line=43, offs=1) -- 607(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 634(line=47, offs=1) -- 664(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 665(line=48, offs=1) -- 700(line=48, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 725(line=52, offs=1) -- 757(line=52, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 792(line=55, offs=1) -- 827(line=55, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 828(line=56, offs=1) -- 867(line=56, offs=40)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 395(line=29, offs=1) -- 435(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 462(line=35, offs=1) -- 492(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 519(line=39, offs=1) -- 552(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 579(line=43, offs=1) -- 610(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 637(line=47, offs=1) -- 667(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 668(line=48, offs=1) -- 701(line=48, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 705(line=50, offs=1) -- 740(line=50, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 765(line=54, offs=1) -- 797(line=54, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 798(line=55, offs=1) -- 833(line=55, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 894(line=60, offs=1) -- 927(line=60, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSarray.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list_vt.dats: 390(line=29, offs=1) -- 430(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list_vt.dats: 455(line=35, offs=1) -- 485(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list_vt.dats: 510(line=39, offs=1) -- 543(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list_vt.dats: 570(line=43, offs=1) -- 600(line=43, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list_vt.dats: 601(line=44, offs=1) -- 634(line=44, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/option.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/option.dats: 392(line=29, offs=1) -- 432(line=30, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/option.dats: 459(line=34, offs=1) -- 492(line=34, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/option.dats: 519(line=38, offs=1) -- 551(line=38, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/option.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 392(line=29, offs=1) -- 432(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 459(line=35, offs=1) -- 489(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 516(line=39, offs=1) -- 549(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 576(line=43, offs=1) -- 607(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 634(line=47, offs=1) -- 664(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 665(line=48, offs=1) -- 700(line=48, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 725(line=52, offs=1) -- 757(line=52, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 395(line=29, offs=1) -- 435(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 462(line=35, offs=1) -- 492(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 519(line=39, offs=1) -- 552(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 579(line=43, offs=1) -- 610(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 637(line=47, offs=1) -- 667(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 668(line=48, offs=1) -- 701(line=48, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 705(line=50, offs=1) -- 740(line=50, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 765(line=54, offs=1) -- 797(line=54, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 798(line=55, offs=1) -- 833(line=55, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/intrange.sats: 272(line=20, offs=1) -- 302(line=20, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/arrayref.sats: 272(line=20, offs=1) -- 302(line=20, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/matrixref.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSmath.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/JSmath.dats: 297(line=22, offs=1) -- 337(line=23, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/JSmath.dats: 364(line=27, offs=1) -- 394(line=27, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/JSmath.dats: 395(line=28, offs=1) -- 426(line=28, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/JSmath.dats: 427(line=29, offs=1) -- 460(line=29, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/JSmath.dats: 487(line=33, offs=1) -- 519(line=33, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSmath.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSdate.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSarray.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSglobal.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/slistref.sats: 318(line=25, offs=1) -- 348(line=25, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/qlistref.sats: 315(line=24, offs=1) -- 345(line=24, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/ML/list0.sats: 277(line=21, offs=1) -- 310(line=21, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 400(line=30, offs=1) -- 440(line=31, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 467(line=35, offs=1) -- 500(line=35, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 527(line=39, offs=1) -- 563(line=39, offs=37)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 590(line=43, offs=1) -- 624(line=43, offs=35)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 625(line=44, offs=1) -- 661(line=44, offs=37)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/filebas.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 688(line=48, offs=1) -- 721(line=48, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 748(line=52, offs=1) -- 783(line=52, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 787(line=54, offs=1) -- 825(line=54, offs=39)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 826(line=55, offs=1) -- 868(line=55, offs=43)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 395(line=29, offs=1) -- 435(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 462(line=35, offs=1) -- 492(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 519(line=39, offs=1) -- 552(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 579(line=43, offs=1) -- 610(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 637(line=47, offs=1) -- 667(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 668(line=48, offs=1) -- 701(line=48, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 705(line=50, offs=1) -- 740(line=50, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 765(line=54, offs=1) -- 797(line=54, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 798(line=55, offs=1) -- 833(line=55, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 895(line=59, offs=1) -- 932(line=59, offs=38)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/ML/list0.sats: 277(line=21, offs=1) -- 310(line=21, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/list0.dats: 1036(line=69, offs=1) -- 1061(line=69, offs=26)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 390(line=29, offs=1) -- 430(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 455(line=35, offs=1) -- 485(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 510(line=39, offs=1) -- 543(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 570(line=43, offs=1) -- 601(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 602(line=44, offs=1) -- 635(line=44, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/filebas.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 662(line=48, offs=1) -- 692(line=48, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 719(line=52, offs=1) -- 751(line=52, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 752(line=53, offs=1) -- 788(line=53, offs=37)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 392(line=29, offs=1) -- 432(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 459(line=35, offs=1) -- 489(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 516(line=39, offs=1) -- 549(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 576(line=43, offs=1) -- 607(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 634(line=47, offs=1) -- 664(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 665(line=48, offs=1) -- 700(line=48, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream.dats: 725(line=52, offs=1) -- 757(line=52, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 792(line=55, offs=1) -- 827(line=55, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 828(line=56, offs=1) -- 867(line=56, offs=40)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 395(line=29, offs=1) -- 435(line=31, offs=27)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 462(line=35, offs=1) -- 492(line=35, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 519(line=39, offs=1) -- 552(line=39, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 579(line=43, offs=1) -- 610(line=43, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 637(line=47, offs=1) -- 667(line=47, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list.sats: 293(line=21, offs=1) -- 323(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 668(line=48, offs=1) -- 701(line=48, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/list_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 705(line=50, offs=1) -- 740(line=50, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/reference.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 765(line=54, offs=1) -- 797(line=54, offs=33)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/stream_vt.dats: 798(line=55, offs=1) -- 833(line=55, offs=36)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/stream_vt.sats: 274(line=21, offs=1) -- 304(line=21, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/list.dats: 894(line=60, offs=1) -- 927(line=60, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/JSarray.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/ML/array0.sats: 277(line=21, offs=1) -- 310(line=21, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 402(line=30, offs=1) -- 442(line=31, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 469(line=35, offs=1) -- 502(line=35, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 529(line=39, offs=1) -- 565(line=39, offs=37)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 592(line=43, offs=1) -- 626(line=43, offs=35)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 627(line=44, offs=1) -- 663(line=44, offs=37)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/filebas.sats: 200(line=16, offs=1) -- 230(line=16, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 690(line=48, offs=1) -- 727(line=48, offs=38)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/arrayref.sats: 272(line=20, offs=1) -- 302(line=20, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/ML/array0.dats: 728(line=49, offs=1) -- 766(line=49, offs=39)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/ML/array0.sats: 277(line=21, offs=1) -- 310(line=21, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/print.dats: 296(line=22, offs=1) -- 326(line=22, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/print.dats: 330(line=24, offs=1) -- 361(line=24, offs=32)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/print.sats: 192(line=18, offs=1) -- 222(line=18, offs=31)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/DATS/print.dats: 365(line=26, offs=1) -- 399(line=26, offs=35)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/ML/list0.sats: 277(line=21, offs=1) -- 310(line=21, offs=34)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/Bacon.js/baconjs.sats: 1110(line=39, offs=1) -- 1142(line=40, offs=25)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/Bacon.js/baconjs_ext.sats: 1116(line=39, offs=1) -- 1148(line=40, offs=25)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/Bacon.js/baconjs_ext.sats: 1175(line=44, offs=1) -- 1199(line=44, offs=25)
*/
/*
/root/ATS-Postiats/contrib/libatscc2js/ATS2-0.3.2/SATS/Bacon.js/baconjs.sats: 1110(line=39, offs=1) -- 1142(line=40, offs=25)
*/
/*
staload-prologues(end)
*/
/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4343(line=245, offs=1) -- 4632(line=261, offs=3)
*/
ATSextcode_beg()
//
var
theCanvas =
document.getElementById
("theShowStream-canvas");
var
theCanvas_ctx2d = theCanvas.getContext('2d');
//
var _ = theCanvas_ctx2d.font = "40px Georgia";
//
function
theCanvas_get() { return theCanvas; };
function
theCanvas_ctx2d_get() { return theCanvas_ctx2d; };
//
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(ats2js_bacon_EStream_map_method)
ATSdyncst_mac(ats2js_bacon_EStream_map)
ATSdyncst_mac(ats2js_bacon_ext_EStream_singpair_trans)
ATSdyncst_mac(ats2js_bacon_EStream_merge3)
ATSdyncst_mac(ats2js_bacon_EStream_scan)
ATSdyncst_mac(ats2js_bacon_EStream_merge2)
ATSdyncst_mac(ats2jspre_neg_bool0)
ATSdyncst_mac(ats2js_bacon_Property_onValue_method)
ATSdyncst_mac(ats2js_bacon_Property_sampledBy_estream_cfun)
ATSdyncst_mac(ats2js_bacon_Property_sampledBy_estream)
ATSdyncst_mac(ats2js_bacon_Bacon_interval)
ATSdyncst_mac(ats2js_bacon_EStream_toProperty_init)
ATSdyncst_mac(theAllAct_Next_do)
ATSdyncst_mac(theAllAct_Prev_do)
ATSdyncst_mac(theAllAct_Next2_do)
ATSdyncst_mac(theAllAct_Prev2_do)
ATSdyncst_mac(theAllAct_Search_do)
ATSdyncst_mac(theAllAct_Reset_do)
ATSdyncst_mac(ats2js_bacon_EStream_onValue_method)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(theCounter3_baconjs_statmp0, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp1, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp2, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp3, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp4, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp5, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp6, atstype_cloptr) ;
ATSstatmpdec(theCounter3_baconjs_statmp7, atstype_boxed) ;
ATSstatmpdec(theCounter3_baconjs_statmp9, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp10, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp12, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp13, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp15, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp16, atstype_cloptr) ;
ATSstatmpdec(theCounter3_baconjs_statmp17, atstype_boxed) ;
ATSstatmpdec(theCounter3_baconjs_statmp19, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp20, atstype_cloptr) ;
ATSstatmpdec(theCounter3_baconjs_statmp21, atstype_boxed) ;
ATSstatmpdec(theCounter3_baconjs_statmp23, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp24, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp25, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(theCounter3_baconjs_statmp27) ;
ATSstatmpdec(theCounter3_baconjs_statmp28, atstype_cloptr) ;
ATSstatmpdec(theCounter3_baconjs_statmp30, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp32, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp33, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp34, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp35, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp36, atstype_cloptr) ;
ATSstatmpdec(theCounter3_baconjs_statmp37, atstype_boxed) ;
ATSstatmpdec(theCounter3_baconjs_statmp39, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp40, atstype_cloptr) ;
ATSstatmpdec(theCounter3_baconjs_statmp41, atstype_boxed) ;
ATSstatmpdec(theCounter3_baconjs_statmp43, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp44, atstype_boxed) ;
ATSstatmpdec(theCounter3_baconjs_statmp45, atstkind_type(atstype_ptrk)) ;
ATSstatmpdec(theCounter3_baconjs_statmp48, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(theCounter3_baconjs_statmp49) ;
ATSstatmpdec(theCounter3_baconjs_statmp50, atstype_cloptr) ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_0(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_1(atstype_boxed) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_2(atstype_boxed) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_3(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_4(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
theCounter3_baconjs_patsfun_5(atstkind_t0ype(atstype_bool), atstype_boxed) ;

ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_patsfun_6(atstkind_t0ype(atstype_bool)) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_7(atstkind_t0ype(atstype_bool), atstype_boxed) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_8(atstype_boxed) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_9(atstype_boxed) ;

ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_10(atstype_boxed, atstkind_t0ype(atstype_bool)) ;

ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_theAllAct_do_11(atstype_boxed) ;

ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_patsfun_12(atstype_boxed) ;

#if(0)
ATSextern()
atsvoid_t0ype
theCounter3_baconjs_start() ;
#endif // end of [QUALIFIED]

ATSclosurerize_beg(theCounter3_baconjs_patsfun_0, (), (atstkind_type(atstype_ptrk)), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_0__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_0__cfun
(
theCounter3_baconjs_patsfun_0__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_0(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_0__closureinit
(
theCounter3_baconjs_patsfun_0__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_0__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_0__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_0__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_0__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_1, (), (atstype_boxed), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_1__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_1__cfun
(
theCounter3_baconjs_patsfun_1__closure_t0ype *p_cenv, atstype_boxed arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_1(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_1__closureinit
(
theCounter3_baconjs_patsfun_1__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_1__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_1__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_1__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_1__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_2, (), (atstype_boxed), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_2__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_2__cfun
(
theCounter3_baconjs_patsfun_2__closure_t0ype *p_cenv, atstype_boxed arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_2(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_2__closureinit
(
theCounter3_baconjs_patsfun_2__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_2__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_2__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_2__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_2__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_3, (), (atstkind_type(atstype_ptrk)), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_3__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_3__cfun
(
theCounter3_baconjs_patsfun_3__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_3(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_3__closureinit
(
theCounter3_baconjs_patsfun_3__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_3__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_3__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_3__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_3__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_4, (), (atstkind_type(atstype_ptrk)), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_4__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_4__cfun
(
theCounter3_baconjs_patsfun_4__closure_t0ype *p_cenv, atstkind_type(atstype_ptrk) arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_4(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_4__closureinit
(
theCounter3_baconjs_patsfun_4__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_4__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_4__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_4__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_4__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_5, (), (atstkind_t0ype(atstype_bool), atstype_boxed), atstkind_t0ype(atstype_bool))
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_5__closure_t0ype ;
ATSstatic()
atstkind_t0ype(atstype_bool)
theCounter3_baconjs_patsfun_5__cfun
(
theCounter3_baconjs_patsfun_5__closure_t0ype *p_cenv, atstkind_t0ype(atstype_bool) arg0, atstype_boxed arg1
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_5(arg0, arg1)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_5__closureinit
(
theCounter3_baconjs_patsfun_5__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_5__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_5__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_5__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_5__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_6, (), (atstkind_t0ype(atstype_bool)), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_6__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_patsfun_6__cfun
(
theCounter3_baconjs_patsfun_6__closure_t0ype *p_cenv, atstkind_t0ype(atstype_bool) arg0
)
{
ATSFCreturn_void(theCounter3_baconjs_patsfun_6(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_6__closureinit
(
theCounter3_baconjs_patsfun_6__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_6__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_6__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_6__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_6__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_7, (), (atstkind_t0ype(atstype_bool), atstype_boxed), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_7__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_7__cfun
(
theCounter3_baconjs_patsfun_7__closure_t0ype *p_cenv, atstkind_t0ype(atstype_bool) arg0, atstype_boxed arg1
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_7(arg0, arg1)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_7__closureinit
(
theCounter3_baconjs_patsfun_7__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_7__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_7__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_7__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_7__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_8, (), (atstype_boxed), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_8__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_8__cfun
(
theCounter3_baconjs_patsfun_8__closure_t0ype *p_cenv, atstype_boxed arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_8(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_8__closureinit
(
theCounter3_baconjs_patsfun_8__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_8__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_8__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_8__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_8__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_9, (), (atstype_boxed), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_9__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_9__cfun
(
theCounter3_baconjs_patsfun_9__closure_t0ype *p_cenv, atstype_boxed arg0
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_9(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_9__closureinit
(
theCounter3_baconjs_patsfun_9__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_9__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_9__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_9__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_9__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_10, (), (atstype_boxed, atstkind_t0ype(atstype_bool)), atstype_boxed)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_10__closure_t0ype ;
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_10__cfun
(
theCounter3_baconjs_patsfun_10__closure_t0ype *p_cenv, atstype_boxed arg0, atstkind_t0ype(atstype_bool) arg1
)
{
ATSFCreturn(theCounter3_baconjs_patsfun_10(arg0, arg1)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_10__closureinit
(
theCounter3_baconjs_patsfun_10__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_10__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_10__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_10__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_10__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
ATSclosurerize_beg(theCounter3_baconjs_patsfun_12, (), (atstype_boxed), atsvoid_t0ype)
typedef
ATSstruct {
atstype_funptr cfun ;
} theCounter3_baconjs_patsfun_12__closure_t0ype ;
ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_patsfun_12__cfun
(
theCounter3_baconjs_patsfun_12__closure_t0ype *p_cenv, atstype_boxed arg0
)
{
ATSFCreturn_void(theCounter3_baconjs_patsfun_12(arg0)) ;
} /* end of [cfun] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_12__closureinit
(
theCounter3_baconjs_patsfun_12__closure_t0ype *p_cenv
)
{
p_cenv->cfun = theCounter3_baconjs_patsfun_12__cfun ;
return p_cenv ;
} /* end of [closureinit] */
ATSstatic()
atstype_cloptr
theCounter3_baconjs_patsfun_12__closurerize
(
// argumentless
)
{
return theCounter3_baconjs_patsfun_12__closureinit(ATS_MALLOC(sizeof(theCounter3_baconjs_patsfun_12__closure_t0ype))) ;
} /* end of [closurerize] */
ATSclosurerize_end()
/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2078(line=130, offs=31) -- 2093(line=130, offs=46)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_0(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret8, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2078(line=130, offs=31) -- 2093(line=130, offs=46)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_0):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2087(line=130, offs=40) -- 2093(line=130, offs=46)
*/

ATSINSmove_con0(tmpret8, 0) ;

ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [theCounter3_baconjs_patsfun_0] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2202(line=137, offs=3) -- 2259(line=137, offs=60)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_1$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_1(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2202(line=137, offs=3) -- 2259(line=137, offs=60)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_1):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2212(line=137, offs=13) -- 2259(line=137, offs=60)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2223(line=137, offs=24) -- 2229(line=137, offs=30)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2206(line=137, offs=7) -- 2207(line=137, offs=8)
*/
ATSifnthen(ATSCKpat_con1(arg0, 0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2229(line=137, offs=30) -- 2229(line=137, offs=30)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2233(line=137, offs=34) -- 2239(line=137, offs=40)
*/

ATSINSmove_con0(tmpret11, 1) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2242(line=137, offs=43) -- 2248(line=137, offs=49)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2206(line=137, offs=7) -- 2207(line=137, offs=8)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg0, 1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2248(line=137, offs=49) -- 2248(line=137, offs=49)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2252(line=137, offs=53) -- 2259(line=137, offs=60)
*/

ATSINSmove_con0(tmpret11, 2) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [theCounter3_baconjs_patsfun_1] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2366(line=144, offs=3) -- 2423(line=144, offs=60)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_2$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_2(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2366(line=144, offs=3) -- 2423(line=144, offs=60)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_2):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2376(line=144, offs=13) -- 2423(line=144, offs=60)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2387(line=144, offs=24) -- 2393(line=144, offs=30)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2370(line=144, offs=7) -- 2371(line=144, offs=8)
*/
ATSifnthen(ATSCKpat_con1(arg0, 0)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2393(line=144, offs=30) -- 2393(line=144, offs=30)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2397(line=144, offs=34) -- 2403(line=144, offs=40)
*/

ATSINSmove_con0(tmpret14, 3) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2406(line=144, offs=43) -- 2412(line=144, offs=49)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2370(line=144, offs=7) -- 2371(line=144, offs=8)
*/
#if(0)
ATSifnthen(ATSCKpat_con1(arg0, 1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2412(line=144, offs=49) -- 2412(line=144, offs=49)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2416(line=144, offs=53) -- 2423(line=144, offs=60)
*/

ATSINSmove_con0(tmpret14, 4) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret14) ;
} /* end of [theCounter3_baconjs_patsfun_2] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2480(line=148, offs=48) -- 2495(line=148, offs=63)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_3$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_3(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2480(line=148, offs=48) -- 2495(line=148, offs=63)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_3):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2489(line=148, offs=57) -- 2495(line=148, offs=63)
*/

ATSINSmove_con0(tmpret18, 5) ;

ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [theCounter3_baconjs_patsfun_3] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2553(line=151, offs=50) -- 2569(line=151, offs=66)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_4$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_4(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2553(line=151, offs=50) -- 2569(line=151, offs=66)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_4):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2562(line=151, offs=59) -- 2569(line=151, offs=66)
*/

ATSINSmove_con0(tmpret22, 6) ;

ATSfunbody_end()
ATSreturn(tmpret22) ;
} /* end of [theCounter3_baconjs_patsfun_4] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2796(line=168, offs=3) -- 2853(line=168, offs=60)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_5$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
theCounter3_baconjs_patsfun_5(atstkind_t0ype(atstype_bool) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret26, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2796(line=168, offs=3) -- 2853(line=168, offs=60)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_5):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2813(line=168, offs=20) -- 2853(line=168, offs=60)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2826(line=168, offs=33) -- 2832(line=168, offs=39)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2805(line=168, offs=12) -- 2808(line=168, offs=15)
*/
ATSifnthen(ATSCKpat_con0(arg1, 0)) { ATSINSgoto(__atstmplab10) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2832(line=168, offs=39) -- 2832(line=168, offs=39)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2836(line=168, offs=43) -- 2840(line=168, offs=47)
*/
ATSINSmove(tmpret26, ats2jspre_neg_bool0(arg0)) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2844(line=168, offs=51) -- 2844(line=168, offs=51)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2848(line=168, offs=55) -- 2853(line=168, offs=60)
*/
ATSINSmove(tmpret26, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret26) ;
} /* end of [theCounter3_baconjs_patsfun_5] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2896(line=174, offs=1) -- 3037(line=177, offs=64)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_6$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_patsfun_6(atstkind_t0ype(atstype_bool) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret29) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2896(line=174, offs=1) -- 3037(line=177, offs=64)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_6):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2907(line=175, offs=1) -- 3037(line=177, offs=64)
*/
ATSif(
arg0
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2918(line=176, offs=6) -- 2973(line=176, offs=61)
*/
ATSINSmove_void(tmpret29, ATSextmcall(ATSPMVextval($("#theAuto_btn")), addClass, (ATSPMVstring("btn-primary")))) ;
} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2979(line=177, offs=6) -- 3037(line=177, offs=64)
*/
ATSINSmove_void(tmpret29, ATSextmcall(ATSPMVextval($("#theAuto_btn")), removeClass, (ATSPMVstring("btn-primary")))) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret29) ;
} /* end of [theCounter3_baconjs_patsfun_6] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3140(line=182, offs=39) -- 3174(line=182, offs=73)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_7$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_7(atstkind_t0ype(atstype_bool) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret31, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3140(line=182, offs=39) -- 3174(line=182, offs=73)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_7):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3153(line=182, offs=52) -- 3174(line=182, offs=73)
*/
ATSif(
arg0
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3163(line=182, offs=62) -- 3167(line=182, offs=66)
*/

ATSINSmove_con0(tmpret31, 7) ;

} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3173(line=182, offs=72) -- 3174(line=182, offs=73)
*/
ATSINSmove(tmpret31, arg1) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret31) ;
} /* end of [theCounter3_baconjs_patsfun_7] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3376(line=192, offs=35) -- 3389(line=192, offs=48)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_8$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_8(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3376(line=192, offs=35) -- 3389(line=192, offs=48)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_8):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3385(line=192, offs=44) -- 3389(line=192, offs=48)
*/

ATSINSmove_con0(tmpret38, 7) ;

ATSfunbody_end()
ATSreturn(tmpret38) ;
} /* end of [theCounter3_baconjs_patsfun_8] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3426(line=193, offs=36) -- 3439(line=193, offs=49)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_9$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_9(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret42, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3426(line=193, offs=36) -- 3439(line=193, offs=49)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_9):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3435(line=193, offs=45) -- 3439(line=193, offs=49)
*/

ATSINSmove_con0(tmpret42, 7) ;

ATSfunbody_end()
ATSreturn(tmpret42) ;
} /* end of [theCounter3_baconjs_patsfun_9] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3619(line=199, offs=41) -- 3653(line=199, offs=75)
*/
/*
local: 
global: theCounter3_baconjs_patsfun_10$0(level=0)
local: 
global: 
*/
ATSstatic()
atstype_boxed
theCounter3_baconjs_patsfun_10(atstype_boxed arg0, atstkind_t0ype(atstype_bool) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret46, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3619(line=199, offs=41) -- 3653(line=199, offs=75)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_10):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3632(line=199, offs=54) -- 3653(line=199, offs=75)
*/
ATSif(
arg1
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3642(line=199, offs=64) -- 3643(line=199, offs=65)
*/
ATSINSmove(tmpret46, arg0) ;
} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3649(line=199, offs=71) -- 3653(line=199, offs=75)
*/

ATSINSmove_con0(tmpret46, 7) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret46) ;
} /* end of [theCounter3_baconjs_patsfun_10] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3727(line=208, offs=1) -- 4022(line=225, offs=2)
*/
/*
local: 
global: theCounter3_baconjs_theAllAct_do_11$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_theAllAct_do_11(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret47) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3727(line=208, offs=1) -- 4022(line=225, offs=2)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_theAllAct_do_11):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3766(line=212, offs=1) -- 4017(line=223, offs=34)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3781(line=213, offs=3) -- 3787(line=213, offs=9)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 0)) { ATSINSgoto(__atstmplab13) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3787(line=213, offs=9) -- 3787(line=213, offs=9)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3791(line=213, offs=13) -- 3793(line=213, offs=15)
*/
ATSINSmove_void(tmpret47, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3796(line=214, offs=3) -- 3802(line=214, offs=9)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 7)) { ATSINSgoto(__atstmplab15) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3802(line=214, offs=9) -- 3802(line=214, offs=9)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3806(line=214, offs=13) -- 3808(line=214, offs=15)
*/
ATSINSmove_void(tmpret47, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3814(line=216, offs=3) -- 3820(line=216, offs=9)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 1)) { ATSINSgoto(__atstmplab17) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3820(line=216, offs=9) -- 3820(line=216, offs=9)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3824(line=216, offs=13) -- 3843(line=216, offs=32)
*/
ATSINSmove_void(tmpret47, theAllAct_Next_do()) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3846(line=217, offs=3) -- 3852(line=217, offs=9)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 3)) { ATSINSgoto(__atstmplab19) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3852(line=217, offs=9) -- 3852(line=217, offs=9)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3856(line=217, offs=13) -- 3875(line=217, offs=32)
*/
ATSINSmove_void(tmpret47, theAllAct_Prev_do()) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3878(line=218, offs=3) -- 3885(line=218, offs=10)
*/
ATSINSlab(__atstmplab19):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 2)) { ATSINSgoto(__atstmplab21) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3885(line=218, offs=10) -- 3885(line=218, offs=10)
*/
ATSINSlab(__atstmplab20):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3889(line=218, offs=14) -- 3909(line=218, offs=34)
*/
ATSINSmove_void(tmpret47, theAllAct_Next2_do()) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3912(line=219, offs=3) -- 3919(line=219, offs=10)
*/
ATSINSlab(__atstmplab21):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 4)) { ATSINSgoto(__atstmplab23) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3919(line=219, offs=10) -- 3919(line=219, offs=10)
*/
ATSINSlab(__atstmplab22):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3923(line=219, offs=14) -- 3943(line=219, offs=34)
*/
ATSINSmove_void(tmpret47, theAllAct_Prev2_do()) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3949(line=221, offs=3) -- 3955(line=221, offs=9)
*/
ATSINSlab(__atstmplab23):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
ATSifnthen(ATSCKpat_con0(arg0, 5)) { ATSINSgoto(__atstmplab25) ; } ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3955(line=221, offs=9) -- 3955(line=221, offs=9)
*/
ATSINSlab(__atstmplab24):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3959(line=221, offs=13) -- 3980(line=221, offs=34)
*/
ATSINSmove_void(tmpret47, theAllAct_Search_do()) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3986(line=223, offs=3) -- 3993(line=223, offs=10)
*/
ATSINSlab(__atstmplab25):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3743(line=209, offs=4) -- 3746(line=209, offs=7)
*/
#if(0)
ATSifnthen(ATSCKpat_con0(arg0, 6)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3993(line=223, offs=10) -- 3993(line=223, offs=10)
*/
ATSINSlab(__atstmplab26):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3997(line=223, offs=14) -- 4017(line=223, offs=34)
*/
ATSINSmove_void(tmpret47, theAllAct_Reset_do()) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret47) ;
} /* end of [theCounter3_baconjs_theAllAct_do_11] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4265(line=239, offs=37) -- 4294(line=239, offs=66)
*/
/*
local: theCounter3_baconjs_theAllAct_do_11$0(level=0)
global: theCounter3_baconjs_theAllAct_do_11$0(level=0), theCounter3_baconjs_patsfun_12$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
theCounter3_baconjs_patsfun_12(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret51) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4265(line=239, offs=37) -- 4294(line=239, offs=66)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_patsfun_12):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4277(line=239, offs=49) -- 4293(line=239, offs=65)
*/
ATSINSmove_void(tmpret51, theCounter3_baconjs_theAllAct_do_11(arg0)) ;

ATSfunbody_end()
ATSreturn_void(tmpret51) ;
} /* end of [theCounter3_baconjs_patsfun_12] */

/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4779(line=271, offs=26) -- 4906(line=281, offs=2)
*/
/*
local: 
global: theCounter3_baconjs_start$13$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
theCounter3_baconjs_start()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret52) ;
// ATStmpdec_void(tmp53) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4754(line=271, offs=1) -- 4906(line=281, offs=2)
*/
ATSINSflab(__patsflab_theCounter3_baconjs_start):
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4784(line=272, offs=1) -- 4906(line=281, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4795(line=274, offs=1) -- 4847(line=278, offs=2)
*/
ATSINSmove_void(tmp53, ATSextfcall(theCounter3_baconjs_initize, ())) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4884(line=280, offs=18) -- 4904(line=280, offs=38)
*/
ATSINSmove_void(tmpret52, theAllAct_Reset_do()) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4784(line=272, offs=1) -- 4906(line=281, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret52) ;
} /* end of [theCounter3_baconjs_start] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_tmp_057_assigns_057_09_057_Wormlike_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_09_057_Wormlike_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_tmp_057_assigns_057_09_057_Wormlike_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_tmp_057_assigns_057_09_057_Wormlike_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_tmp_057_assigns_057_09_057_Wormlike_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 1370(line=96, offs=1) -- 1432(line=96, offs=63)
*/
ATSINSmove(theCounter3_baconjs_statmp0, ATSextmcall(ATSPMVextval($("#theAuto_btn")), asEventStream, (ATSPMVstring("click")))) ;
/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 1511(line=103, offs=1) -- 1573(line=103, offs=63)
*/
ATSINSmove(theCounter3_baconjs_statmp1, ATSextmcall(ATSPMVextval($("#theNext_btn")), asEventStream, (ATSPMVstring("click")))) ;
/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 1652(line=110, offs=1) -- 1714(line=110, offs=63)
*/
ATSINSmove(theCounter3_baconjs_statmp2, ATSextmcall(ATSPMVextval($("#thePrev_btn")), asEventStream, (ATSPMVstring("click")))) ;
/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 1793(line=117, offs=1) -- 1855(line=117, offs=63)
*/
ATSINSmove(theCounter3_baconjs_statmp3, ATSextmcall(ATSPMVextval($("#theSrch_btn")), asEventStream, (ATSPMVstring("click")))) ;
/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 1937(line=124, offs=1) -- 2000(line=124, offs=64)
*/
ATSINSmove(theCounter3_baconjs_statmp4, ATSextmcall(ATSPMVextval($("#theReset_btn")), asEventStream, (ATSPMVstring("click")))) ;
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2067(line=130, offs=20) -- 2076(line=130, offs=29)
*/

ATSINSmove_con0(theCounter3_baconjs_statmp7, 0) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2048(line=130, offs=1) -- 2094(line=130, offs=47)
*/
ATSINSmove(theCounter3_baconjs_statmp6, ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp0, theCounter3_baconjs_statmp7)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2048(line=130, offs=1) -- 2094(line=130, offs=47)
*/
ATSINSmove(theCounter3_baconjs_statmp5, ATSfunclo_clo(theCounter3_baconjs_statmp6, (atstype_cloptr, atstype_cloptr), atstkind_type(atstype_ptrk))(theCounter3_baconjs_statmp6, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_0, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2156(line=136, offs=3) -- 2199(line=136, offs=46)
*/
ATSINSmove(theCounter3_baconjs_statmp10, ats2js_bacon_ext_EStream_singpair_trans(theCounter3_baconjs_statmp1, ATSPMVi0nt(200))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2120(line=134, offs=1) -- 2261(line=138, offs=2)
*/
ATSINSmove(theCounter3_baconjs_statmp9, ats2js_bacon_EStream_map(theCounter3_baconjs_statmp10, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_1, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2320(line=143, offs=3) -- 2363(line=143, offs=46)
*/
ATSINSmove(theCounter3_baconjs_statmp13, ats2js_bacon_ext_EStream_singpair_trans(theCounter3_baconjs_statmp2, ATSPMVi0nt(200))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2284(line=141, offs=1) -- 2425(line=145, offs=2)
*/
ATSINSmove(theCounter3_baconjs_statmp12, ats2js_bacon_EStream_map(theCounter3_baconjs_statmp13, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_2, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2469(line=148, offs=37) -- 2478(line=148, offs=46)
*/

ATSINSmove_con0(theCounter3_baconjs_statmp17, 0) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2450(line=148, offs=18) -- 2496(line=148, offs=64)
*/
ATSINSmove(theCounter3_baconjs_statmp16, ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp3, theCounter3_baconjs_statmp17)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2450(line=148, offs=18) -- 2496(line=148, offs=64)
*/
ATSINSmove(theCounter3_baconjs_statmp15, ATSfunclo_clo(theCounter3_baconjs_statmp16, (atstype_cloptr, atstype_cloptr), atstkind_type(atstype_ptrk))(theCounter3_baconjs_statmp16, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_3, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2542(line=151, offs=39) -- 2551(line=151, offs=48)
*/

ATSINSmove_con0(theCounter3_baconjs_statmp21, 0) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2522(line=151, offs=19) -- 2570(line=151, offs=67)
*/
ATSINSmove(theCounter3_baconjs_statmp20, ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp4, theCounter3_baconjs_statmp21)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2522(line=151, offs=19) -- 2570(line=151, offs=67)
*/
ATSINSmove(theCounter3_baconjs_statmp19, ATSfunclo_clo(theCounter3_baconjs_statmp20, (atstype_cloptr, atstype_cloptr), atstkind_type(atstype_ptrk))(theCounter3_baconjs_statmp20, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_4, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2618(line=157, offs=1) -- 2671(line=157, offs=54)
*/
ATSINSmove(theCounter3_baconjs_statmp23, ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp9, theCounter3_baconjs_statmp12, theCounter3_baconjs_statmp15)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2725(line=163, offs=3) -- 2774(line=166, offs=4)
*/
ATSINSmove(theCounter3_baconjs_statmp25, ats2js_bacon_EStream_merge2(theCounter3_baconjs_statmp5, theCounter3_baconjs_statmp19)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2697(line=161, offs=1) -- 2855(line=169, offs=2)
*/
ATSINSmove(theCounter3_baconjs_statmp24, ats2js_bacon_EStream_scan(theCounter3_baconjs_statmp25, ATSPMVbool_false(), ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_5, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2868(line=172, offs=1) -- 3039(line=178, offs=2)
*/
ATSINSmove(theCounter3_baconjs_statmp28, ats2js_bacon_Property_onValue_method(theCounter3_baconjs_statmp24)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 2868(line=172, offs=1) -- 3039(line=178, offs=2)
*/
ATSINSmove_void(theCounter3_baconjs_statmp27, ATSfunclo_clo(theCounter3_baconjs_statmp28, (atstype_cloptr, atstype_cloptr), atsvoid_t0ype)(theCounter3_baconjs_statmp28, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_6, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3070(line=181, offs=3) -- 3175(line=182, offs=74)
*/
ATSINSmove(theCounter3_baconjs_statmp30, ats2js_bacon_Property_sampledBy_estream_cfun(theCounter3_baconjs_statmp24, theCounter3_baconjs_statmp23, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_7, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3251(line=186, offs=23) -- 3284(line=186, offs=56)
*/
ATSINSmove(theCounter3_baconjs_statmp33, ats2js_bacon_Bacon_interval(ATSPMVi0nt(250), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3202(line=185, offs=3) -- 3285(line=186, offs=57)
*/
ATSINSmove(theCounter3_baconjs_statmp32, ats2js_bacon_Property_sampledBy_estream(theCounter3_baconjs_statmp24, theCounter3_baconjs_statmp33)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3365(line=192, offs=24) -- 3374(line=192, offs=33)
*/

ATSINSmove_con0(theCounter3_baconjs_statmp37, 0) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3346(line=192, offs=5) -- 3390(line=192, offs=49)
*/
ATSINSmove(theCounter3_baconjs_statmp36, ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp5, theCounter3_baconjs_statmp37)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3346(line=192, offs=5) -- 3390(line=192, offs=49)
*/
ATSINSmove(theCounter3_baconjs_statmp35, ATSfunclo_clo(theCounter3_baconjs_statmp36, (atstype_cloptr, atstype_cloptr), atstkind_type(atstype_ptrk))(theCounter3_baconjs_statmp36, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_8, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3415(line=193, offs=25) -- 3424(line=193, offs=34)
*/

ATSINSmove_con0(theCounter3_baconjs_statmp41, 0) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3395(line=193, offs=5) -- 3440(line=193, offs=50)
*/
ATSINSmove(theCounter3_baconjs_statmp40, ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp19, theCounter3_baconjs_statmp41)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3395(line=193, offs=5) -- 3440(line=193, offs=50)
*/
ATSINSmove(theCounter3_baconjs_statmp39, ATSfunclo_clo(theCounter3_baconjs_statmp40, (atstype_cloptr, atstype_cloptr), atstkind_type(atstype_ptrk))(theCounter3_baconjs_statmp40, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_9, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3313(line=189, offs=3) -- 3444(line=194, offs=4)
*/
ATSINSmove(theCounter3_baconjs_statmp34, ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp23, theCounter3_baconjs_statmp35, theCounter3_baconjs_statmp39)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3510(line=195, offs=66) -- 3514(line=195, offs=70)
*/

ATSINSmove_con0(theCounter3_baconjs_statmp44, 7) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3469(line=195, offs=25) -- 3515(line=195, offs=71)
*/
ATSINSmove(theCounter3_baconjs_statmp43, ats2js_bacon_EStream_toProperty_init(theCounter3_baconjs_statmp34, theCounter3_baconjs_statmp44)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 3547(line=198, offs=3) -- 3654(line=199, offs=76)
*/
ATSINSmove(theCounter3_baconjs_statmp45, ats2js_bacon_Property_sampledBy_estream_cfun(theCounter3_baconjs_statmp43, theCounter3_baconjs_statmp32, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_10, ()))) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4100(line=231, offs=1) -- 4169(line=235, offs=2)
*/
ATSINSmove(theCounter3_baconjs_statmp48, ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp19, theCounter3_baconjs_statmp30, theCounter3_baconjs_statmp45)) ;

/* in of [local] */
/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4238(line=239, offs=10) -- 4295(line=239, offs=67)
*/
ATSINSmove(theCounter3_baconjs_statmp50, ats2js_bacon_EStream_onValue_method(theCounter3_baconjs_statmp48)) ;

/*
emit_instr: loc0 = /tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4238(line=239, offs=10) -- 4295(line=239, offs=67)
*/
ATSINSmove_void(theCounter3_baconjs_statmp49, ATSfunclo_clo(theCounter3_baconjs_statmp50, (atstype_cloptr, atstype_cloptr), atsvoid_t0ype)(theCounter3_baconjs_statmp50, ATSPMVcfunlab(-1, theCounter3_baconjs_patsfun_12, ()))) ;

/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */
ATSextern()
atsvoid_t0ype
theCounter3_baconjs_initize()
{
ATSfunbody_beg()
ATSINSmove_void(tmpret_void, _057_tmp_057_assigns_057_09_057_Wormlike_057_MySolution_057_DATS_JS_057_theCounter3_baconjs_056_dats__dynload()) ;
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} // end-of-dynload-alias
/*
/tmp/assigns/09/Wormlike/MySolution/DATS_JS/theCounter3_baconjs.dats: 4963(line=285, offs=1) -- 5004(line=289, offs=3)
*/
ATSextcode_beg()
//
theCounter3_baconjs_start();
//
ATSextcode_end()

/* ****** ****** */

/* end-of-compilation-unit */
