/*
**
** The C code is generated by [ATS/Postiats-0-3-5]
** The starting compilation time is: 2017-5-1:  2h: 6m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/root/ATS-Postiats/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 15552(line=879, offs=1) -- 15589(line=880, offs=30)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gdk.sats: 1178(line=39, offs=1) -- 1213(line=41, offs=3)
*/

#include "GTK/CATS/gdk.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gdk.sats: 1418(line=52, offs=1) -- 1457(line=52, offs=40)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gdk.sats: 1458(line=53, offs=1) -- 1507(line=53, offs=50)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1182(line=39, offs=1) -- 1226(line=41, offs=3)
*/

#include "glib/CATS/glib-object.cats"
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1394(line=50, offs=1) -- 1422(line=50, offs=29)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gtk.sats: 1178(line=39, offs=1) -- 1213(line=41, offs=3)
*/

#include "GTK/CATS/gtk.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gtk.sats: 1418(line=52, offs=1) -- 1457(line=52, offs=40)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gtk.sats: 1458(line=53, offs=1) -- 1507(line=53, offs=50)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1182(line=39, offs=1) -- 1226(line=41, offs=3)
*/

#include "glib/CATS/glib-object.cats"
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1394(line=50, offs=1) -- 1422(line=50, offs=29)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gtk.sats: 2292(line=95, offs=1) -- 2312(line=95, offs=21)
*/
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gdk.sats: 1178(line=39, offs=1) -- 1213(line=41, offs=3)
*/

#include "GTK/CATS/gdk.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gdk.sats: 1418(line=52, offs=1) -- 1457(line=52, offs=40)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/GTK/SATS/gdk.sats: 1458(line=53, offs=1) -- 1507(line=53, offs=50)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1182(line=39, offs=1) -- 1226(line=41, offs=3)
*/

#include "glib/CATS/glib-object.cats"
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1394(line=50, offs=1) -- 1422(line=50, offs=29)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1182(line=39, offs=1) -- 1226(line=41, offs=3)
*/

#include "glib/CATS/glib-object.cats"
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib-object.sats: 1394(line=50, offs=1) -- 1422(line=50, offs=29)
*/
/*
/root/ATS-Postiats-contrib/contrib/glib/SATS/glib.sats: 1182(line=39, offs=1) -- 1219(line=41, offs=3)
*/

#include "glib/CATS/glib.cats"
/*
/tmp/assigns/10/Enigma/Enigma.sats: 241(line=20, offs=1) -- 277(line=21, offs=28)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdlib.sats: 1389(line=36, offs=1) -- 1443(line=41, offs=3)
*/

//
#include \
"libats/libc/CATS/stdlib.cats"
//
/*
/root/ATS-Postiats/libats/libc/SATS/stdlib.sats: 1810(line=62, offs=1) -- 1857(line=64, offs=31)
*/
/*
staload-prologues(end)
*/
/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 4326(line=247, offs=1) -- 4360(line=249, offs=3)
*/
ATSextcode_beg()
typedef char **charptrptr ;
ATSextcode_end()
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atscntrb_gtk_widget_destroy0)
ATSdyncst_mac(atscntrb_gtk_main_quit)
ATSdyncst_extfun(TextProcessing__KEYPRESSED__inc, (), atsvoid_t0ype) ;
ATSdyncst_extfun(Enigma__Enigma_create, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atspre_islower_char)
ATSdyncst_mac(atspre_sub_char0_char0)
ATSdyncst_extfun(Enigma__Enigma_encode, (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_int2char0)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_char2int0)
ATSdyncst_mac(atspre_isupper_char)
ATSdyncst_extfun(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_char, (atstkind_t0ype(atstype_char)), atstkind_t0ype(atstype_char)) ;
ATSdyncst_mac(atspre_malloc_gc)
ATSdyncst_mac(atspre_g0uint_lt_size)
ATSdyncst_mac(atspre_add_ptr1_bsz)
ATSdyncst_mac(atspre_add_ptr0_bsz)
ATSdyncst_mac(atspre_g0uint_succ_size)
ATSdyncst_mac(atspre_g1uint_succ_size)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(atspre_strlen)
ATSdyncst_extfun(TextProcessing__TEXTBUF__get, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(gtk_text_buffer_get_start_iter)
ATSdyncst_mac(gtk_text_buffer_get_end_iter)
ATSdyncst_mac(atscntrb_gtk_text_buffer_get_text)
ATSdyncst_extfun(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_initize, (), atsvoid_t0ype) ;
ATSdyncst_extfun(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_string, (atstkind_type(atstype_ptrk)), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atscntrb_gstrptr_free)
ATSdyncst_extfun(TextProcessing__TEXTBUF2__get, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_extfun(TextProcessing__VADJUST__get, (), atstkind_type(atstype_ptrk)) ;
ATSdyncst_mac(atscntrb_gtk_adjustment_get_value)
ATSdyncst_mac(atscntrb_gtk_text_buffer_setall_text)
ATSdyncst_mac(atscntrb_gtk_adjustment_set_value)
ATSdyncst_mac(atscntrb_gtk_adjustment_value_changed)
ATSdyncst_extfun(TextProcessing__KEYPRESSED__reset, (), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_strptr_free)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gt_int)
ATSdyncst_extfun(TextProcessing__KEYPRESSED__get, (), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atscntrb_gtk_window_new)
ATSdyncst_mac(atspre_assert_errmsg_bool1)
ATSdyncst_mac(atspre_gt_ptr1_intz)
ATSdyncst_extfun(TextProcessing__TOPWIN__set, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
ATSdyncst_mac(atscntrb_gtk_window_set_title)
ATSdyncst_mac(atscntrb_g_signal_connect)
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_mac(atscntrb_gtk_window_set_position)
ATSdyncst_mac(atscntrb_gtk_window_set_resizable)
ATSdyncst_mac(atscntrb_gtk_container_set_border_width)
ATSdyncst_mac(atscntrb_gtk_hbox_new)
ATSdyncst_mac(atscntrb_gtk_container_add)
ATSdyncst_mac(atscntrb_gtk_scrolled_window_new_null)
ATSdyncst_mac(atscntrb_gtk_widget_set_size_request)
ATSdyncst_mac(atscntrb_gtk_box_pack_start)
ATSdyncst_mac(atscntrb_gtk_scrolled_window_get_hadjustment)
ATSdyncst_mac(atscntrb_gtk_scrolled_window_get_vadjustment)
ATSdyncst_extfun(TextProcessing__HADJUST__set, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
ATSdyncst_extfun(TextProcessing__VADJUST__set, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
ATSdyncst_mac(atscntrb_gtk_scrolled_window_new)
ATSdyncst_mac(atscntrb_gtk_text_view_new)
ATSdyncst_mac(atscntrb_gtk_text_view_get_buffer)
ATSdyncst_extfun(TextProcessing__TEXTBUF__set, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
ATSdyncst_mac(atscntrb_gtk_text_view_set_editable)
ATSdyncst_mac(atscntrb_gtk_text_view_set_wrap_mode)
ATSdyncst_mac(atscntrb_gtk_widget_show_unref)
ATSdyncst_extfun(TextProcessing__TEXTBUF2__set, (atstkind_type(atstype_ptrk)), atsvoid_t0ype) ;
ATSdyncst_mac(atscntrb_gtk_text_view_set_cursor_visible)
ATSdyncst_mac(atscntrb_g_timeout_add)
ATSdyncst_mac(atscntrb_gtk_main)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmp5, atstkind_type(atstype_ptrk)) ;
ATSstatic()
atsvoid_t0ype
fdestroy_0(atstkind_type(atstype_ptrk)) ;

ATSstatic()
gboolean
fdelete_event_1(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(GdkEvent), atstkind_type(atstype_ptrk)) ;

ATSstatic()
gboolean
on_key_press_event_2(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg1_type(GdkEvent), atstkind_type(atstype_ptrk)) ;

#if(0)
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_initize() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_char)
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_char(atstkind_t0ype(atstype_char)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_string(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_tabulate__fopr__7(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string_tabulate__8(atstkind_t0ype(atstype_size)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atsvoid_t0ype
loop_9__9(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atstkind_t0ype(atstype_size)) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string_tabulate__8__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;

ATSstatic()
atsvoid_t0ype
loop_9__9__1(atstkind_type(atstype_ptrk), atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atstkind_t0ype(atstype_size)) ;

ATSstatic()
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_tabulate__fopr__7__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_get_at_size__14(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_get_at_size__14__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size)) ;

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
ATSLIB_056_prelude_056_unsafe__ptr0_get__17(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude_056_unsafe__ptr0_get__17__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__19(atstkind_type(atstype_ptrk), atstyvar_type(a)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__19__1(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_char)) ;

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__21(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__21__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__19__2(atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_char)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__27(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__27__1(atstkind_type(atstype_ptrk)) ;

ATSstatic()
gboolean
ftimeout_29() ;

ATSstatic()
gboolean
ftimeout2_30() ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__31(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__31__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_argc_argv_0(atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk))) ;
#endif // end of [QUALIFIED]

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 838(line=54, offs=1) -- 1007(line=67, offs=4)
*/
/*
local: 
global: fdestroy_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
fdestroy_0(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
// ATStmpdec_void(tmp1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 838(line=54, offs=1) -- 1007(line=67, offs=4)
*/
ATSINSflab(__patsflab_fdestroy_0):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 881(line=57, offs=12) -- 1007(line=67, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 950(line=63, offs=10) -- 977(line=63, offs=37)
*/
ATSINSmove_void(tmp1, atscntrb_gtk_widget_destroy0(arg0)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 987(line=66, offs=3) -- 1003(line=66, offs=19)
*/
ATSINSmove_void(tmpret0, atscntrb_gtk_main_quit()) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 881(line=57, offs=12) -- 1007(line=67, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [fdestroy_0] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 1058(line=72, offs=1) -- 1254(line=82, offs=4)
*/
/*
local: 
global: fdelete_event_1$0(level=0)
local: 
global: 
*/
ATSstatic()
gboolean
fdelete_event_1(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg1_type(GdkEvent) arg1, atstkind_type(atstype_ptrk) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, gboolean) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1058(line=72, offs=1) -- 1254(line=82, offs=4)
*/
ATSINSflab(__patsflab_fdelete_event_1):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1216(line=81, offs=3) -- 1222(line=81, offs=9)
*/
ATSINSmove(tmpret2, ATSPMVextval(FALSE)) ;
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [fdelete_event_1] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 1309(line=87, offs=1) -- 1448(line=92, offs=48)
*/
/*
local: 
global: on_key_press_event_2$0(level=0)
local: 
global: 
*/
ATSstatic()
gboolean
on_key_press_event_2(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg1_type(GdkEvent) arg1, atstkind_type(atstype_ptrk) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, gboolean) ;
// ATStmpdec_void(tmp4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1309(line=87, offs=1) -- 1448(line=92, offs=48)
*/
ATSINSflab(__patsflab_on_key_press_event_2):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1403(line=92, offs=3) -- 1448(line=92, offs=48)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1416(line=92, offs=16) -- 1434(line=92, offs=34)
*/
ATSINSmove_void(tmp4, TextProcessing__KEYPRESSED__inc()) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1438(line=92, offs=38) -- 1444(line=92, offs=44)
*/
ATSINSmove(tmpret3, ATSPMVextval(FALSE)) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1403(line=92, offs=3) -- 1448(line=92, offs=48)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [on_key_press_event_2] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 1896(line=127, offs=3) -- 1964(line=132, offs=2)
*/
/*
local: 
global: TextProcessing_initize$3$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_initize()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1871(line=126, offs=1) -- 1964(line=132, offs=2)
*/
ATSINSflab(__patsflab_TextProcessing_initize):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1901(line=127, offs=8) -- 1903(line=127, offs=10)
*/
ATSINSmove_void(tmpret6, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret6) ;
} /* end of [_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_initize] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 2046(line=137, offs=21) -- 2408(line=153, offs=2)
*/
/*
local: 
global: TextProcessing_char$4$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_char)
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_char(atstkind_t0ype(atstype_char) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2026(line=137, offs=1) -- 2408(line=153, offs=2)
*/
ATSINSflab(__patsflab_TextProcessing_char):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2054(line=139, offs=1) -- 2373(line=152, offs=11)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2068(line=140, offs=4) -- 2068(line=140, offs=4)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-guard:
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2074(line=140, offs=10) -- 2083(line=140, offs=19)
*/
ATSINSmove(tmp8, atspre_islower_char(arg0)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2074(line=140, offs=10) -- 2083(line=140, offs=19)
*/
ATSifnthen(ATSCKpat_bool(tmp8, ATSPMVbool_true())) { ATSINSgoto(__atstmplab1) ; } ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2088(line=140, offs=24) -- 2197(line=145, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2104(line=141, offs=13) -- 2111(line=141, offs=20)
*/
ATSINSmove(tmp9, atspre_sub_char0_char0(arg0, ATSPMVchar('a'))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2124(line=142, offs=13) -- 2151(line=142, offs=40)
*/
ATSINSmove(tmp10, Enigma__Enigma_encode(statmp5, tmp9)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2172(line=144, offs=16) -- 2186(line=144, offs=30)
*/
ATSINSmove(tmp12, atspre_char2int0(ATSPMVchar('a'))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2172(line=144, offs=16) -- 2190(line=144, offs=34)
*/
ATSINSmove(tmp11, atspre_g0int_add_int(tmp12, tmp10)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2161(line=144, offs=5) -- 2191(line=144, offs=35)
*/
ATSINSmove(tmpret7, atspre_int2char0(tmp11)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2088(line=140, offs=24) -- 2197(line=145, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2217(line=146, offs=4) -- 2217(line=146, offs=4)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-guard:
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2223(line=146, offs=10) -- 2232(line=146, offs=19)
*/
ATSINSmove(tmp13, atspre_isupper_char(arg0)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2223(line=146, offs=10) -- 2232(line=146, offs=19)
*/
ATSifnthen(ATSCKpat_bool(tmp13, ATSPMVbool_true())) { ATSINSgoto(__atstmplab2) ; } ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2237(line=146, offs=24) -- 2346(line=151, offs=6)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2253(line=147, offs=13) -- 2260(line=147, offs=20)
*/
ATSINSmove(tmp14, atspre_sub_char0_char0(arg0, ATSPMVchar('A'))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2273(line=148, offs=13) -- 2300(line=148, offs=40)
*/
ATSINSmove(tmp15, Enigma__Enigma_encode(statmp5, tmp14)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2321(line=150, offs=16) -- 2335(line=150, offs=30)
*/
ATSINSmove(tmp17, atspre_char2int0(ATSPMVchar('A'))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2321(line=150, offs=16) -- 2339(line=150, offs=34)
*/
ATSINSmove(tmp16, atspre_g0int_add_int(tmp17, tmp15)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2310(line=150, offs=5) -- 2340(line=150, offs=35)
*/
ATSINSmove(tmpret7, atspre_int2char0(tmp16)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2237(line=146, offs=24) -- 2346(line=151, offs=6)
*/
/*
INSletpop()
*/
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2366(line=152, offs=4) -- 2366(line=152, offs=4)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2371(line=152, offs=9) -- 2372(line=152, offs=10)
*/
ATSINSmove(tmpret7, arg0) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_char] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 2488(line=161, offs=3) -- 2827(line=183, offs=4)
*/
/*
local: 
global: TextProcessing_string$6$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_string(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp22, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2464(line=160, offs=1) -- 2827(line=183, offs=4)
*/
ATSINSflab(__patsflab_TextProcessing_string):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2496(line=161, offs=11) -- 2827(line=183, offs=4)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/* local */
/* in of [local] */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2712(line=176, offs=30) -- 2722(line=176, offs=40)
*/
ATSINSmove(tmp59, ATSLIB_056_prelude__string1_length__27__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2694(line=176, offs=12) -- 2724(line=176, offs=42)
*/
ATSINSmove(tmp22, ATSLIB_056_prelude__string_tabulate__8__1(ATSPMVcastfn(g1ofg0_string, atstkind_type(atstype_ptrk), arg0), tmp59)) ;

/* end of [local] */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2803(line=182, offs=3) -- 2822(line=182, offs=22)
*/
ATSINSmove(tmpret18, ATSPMVcastfn(strnptr2strptr, atstkind_type(atstype_ptrk), tmp22)) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2496(line=161, offs=11) -- 2827(line=183, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_string] */

#if(0)
/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 2580(line=169, offs=3) -- 2676(line=173, offs=2)
*/
/*
local: 
global: string_tabulate$fopr$7$0(level=1)
local: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_tabulate__fopr__7(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_size) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2555(line=168, offs=1) -- 2676(line=173, offs=2)
*/
ATSINSflab(__patsflab_string_tabulate__fopr):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2586(line=169, offs=9) -- 2676(line=173, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2646(line=172, offs=23) -- 2673(line=172, offs=50)
*/
ATSINSmove(tmp21, PMVtmpltcst(string_get_at_size<>)(env0, ATSPMVcastfn(cast, atstkind_t0ype(atstype_size), arg0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2626(line=172, offs=3) -- 2674(line=172, offs=51)
*/
ATSINSmove(tmp20, _057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_char(tmp21)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2586(line=169, offs=9) -- 2604(line=169, offs=27)
*/
ATSINSmove(tmpret19, ATSPMVcastfn(cast, atstkind_t0ype(atstype_char), tmp20)) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2586(line=169, offs=9) -- 2676(line=173, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [ATSLIB_056_prelude__string_tabulate__fopr__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 18955(line=1075, offs=19) -- 19429(line=1101, offs=4)
*/
/*
local: 
global: string_tabulate$8$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string_tabulate__8(atstkind_t0ype(atstype_size) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp31, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp32) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18937(line=1075, offs=1) -- 19429(line=1101, offs=4)
*/
ATSINSflab(__patsflab_string_tabulate):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18961(line=1075, offs=25) -- 19429(line=1101, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19293(line=1095, offs=10) -- 19299(line=1095, offs=16)
*/
ATSINSmove(tmp30, PMVtmpltcst(g1uint_succ<S2Eextkind(atstype_size)>)(arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19322(line=1096, offs=22) -- 19335(line=1096, offs=35)
*/
ATSINSmove(tmp31, atspre_malloc_gc(tmp30)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19359(line=1097, offs=23) -- 19373(line=1097, offs=37)
*/
ATSINSmove(tmp33, PMVtmpltcst(g1int2uint<S2Eextkind(atstype_int), S2Eextkind(atstype_size)>)(ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19346(line=1097, offs=10) -- 19374(line=1097, offs=38)
*/
ATSINSmove_void(tmp32, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$597(1), flab=loop_9$0(level=1)), (atstkind_type(atstype_ptrk), atstkind_t0ype(atstype_size), atstkind_t0ype(atstype_size)), atsvoid_t0ype)(tmp31, arg0, tmp33)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19383(line=1100, offs=3) -- 19425(line=1100, offs=45)
*/
ATSINSmove(tmpret23, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp31)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18961(line=1075, offs=25) -- 19429(line=1101, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23) ;
} /* end of [ATSLIB_056_prelude__string_tabulate__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 19009(line=1079, offs=5) -- 19263(line=1093, offs=4)
*/
/*
local: loop_9$0(level=1)
global: loop_9$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_9__9(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1, atstkind_t0ype(atstype_size) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmpret24) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_char)) ;
// ATStmpdec_void(tmp27) ;
ATStmpdec(tmp28, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19009(line=1079, offs=5) -- 19263(line=1093, offs=4)
*/
ATSINSflab(__patsflab_loop_9):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19071(line=1084, offs=4) -- 19076(line=1084, offs=9)
*/
ATSINSmove(tmp25, PMVtmpltcst(g0uint_lt<S2Eextkind(atstype_size)>)(arg2, arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19068(line=1084, offs=1) -- 19241(line=1090, offs=31)
*/
ATSif(
tmp25
) ATSthen() {
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19082(line=1084, offs=15) -- 19205(line=1089, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19096(line=1085, offs=11) -- 19119(line=1085, offs=34)
*/
ATSINSmove(tmp26, PMVtmpltcst(string_tabulate$fopr<>)(arg2)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19132(line=1086, offs=12) -- 19157(line=1086, offs=37)
*/
ATSINSmove_void(tmp27, PMVtmpltcst(ptr0_set<S2Ecst(char_t0ype)>)(arg0, tmp26)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19169(line=1088, offs=9) -- 19186(line=1088, offs=26)
*/
ATSINSmove(tmp28, PMVtmpltcst(ptr0_succ<S2Ecst(char_t0ype)>)(arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19192(line=1088, offs=32) -- 19199(line=1088, offs=39)
*/
ATSINSmove(tmp29, PMVtmpltcst(g0uint_succ<S2Eextkind(atstype_size)>)(arg2)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19163(line=1088, offs=3) -- 19201(line=1088, offs=41)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp28) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, tmp29) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_9) ;
ATStailcal_end()

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19082(line=1084, offs=15) -- 19205(line=1089, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19213(line=1090, offs=3) -- 19241(line=1090, offs=31)
*/
ATSINSmove_void(tmpret24, PMVtmpltcst(ptr0_set<S2Ecst(char_t0ype)>)(arg0, ATSPMVchar('\000'))) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret24) ;
} /* end of [loop_9__9] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/string.dats: 18955(line=1075, offs=19) -- 19429(line=1101, offs=4)
*/
/*
local: 
global: string_tabulate$8$1(level=1)
local: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__string_tabulate__8__1(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_size) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp30__1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp31__1, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp32__1) ;
ATStmpdec(tmp33__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18937(line=1075, offs=1) -- 19429(line=1101, offs=4)
*/
ATSINSflab(__patsflab_string_tabulate):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18961(line=1075, offs=25) -- 19429(line=1101, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19293(line=1095, offs=10) -- 19299(line=1095, offs=16)
*/
ATSINSmove(tmp30__1, atspre_g1uint_succ_size(arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19322(line=1096, offs=22) -- 19335(line=1096, offs=35)
*/
ATSINSmove(tmp31__1, atspre_malloc_gc(tmp30__1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19359(line=1097, offs=23) -- 19373(line=1097, offs=37)
*/
ATSINSmove(tmp33__1, atspre_g1int2uint_int_size(ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19346(line=1097, offs=10) -- 19374(line=1097, offs=38)
*/
ATSINSmove_void(tmp32__1, loop_9__9__1(env0, tmp31__1, arg0, tmp33__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19383(line=1100, offs=3) -- 19425(line=1100, offs=45)
*/
ATSINSmove(tmpret23__1, ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp31__1)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 18961(line=1075, offs=25) -- 19429(line=1101, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23__1) ;
} /* end of [ATSLIB_056_prelude__string_tabulate__8__1] */

/*
/root/ATS-Postiats/prelude/DATS/string.dats: 19009(line=1079, offs=5) -- 19263(line=1093, offs=4)
*/
/*
local: loop_9$1(level=2)
global: loop_9$1(level=2)
local: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
atsvoid_t0ype
loop_9__9__1(atstkind_type(atstype_ptrk) env0, atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1, atstkind_t0ype(atstype_size) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_type(atstype_ptrk)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_size)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmpret24__1) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp26__1, atstkind_t0ype(atstype_char)) ;
// ATStmpdec_void(tmp27__1) ;
ATStmpdec(tmp28__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp29__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19009(line=1079, offs=5) -- 19263(line=1093, offs=4)
*/
ATSINSflab(__patsflab_loop_9):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19071(line=1084, offs=4) -- 19076(line=1084, offs=9)
*/
ATSINSmove(tmp25__1, atspre_g0uint_lt_size(arg2, arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19068(line=1084, offs=1) -- 19241(line=1090, offs=31)
*/
ATSif(
tmp25__1
) ATSthen() {
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19082(line=1084, offs=15) -- 19205(line=1089, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19096(line=1085, offs=11) -- 19119(line=1085, offs=34)
*/
ATSINSmove(tmp26__1, ATSLIB_056_prelude__string_tabulate__fopr__7__1(env0, arg2)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19132(line=1086, offs=12) -- 19157(line=1086, offs=37)
*/
ATSINSmove_void(tmp27__1, ATSLIB_056_prelude_056_unsafe__ptr0_set__19__1(arg0, tmp26__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19169(line=1088, offs=9) -- 19186(line=1088, offs=26)
*/
ATSINSmove(tmp28__1, ATSLIB_056_prelude__ptr0_succ__21__1(arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19192(line=1088, offs=32) -- 19199(line=1088, offs=39)
*/
ATSINSmove(tmp29__1, atspre_g0uint_succ_size(arg2)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19163(line=1088, offs=3) -- 19201(line=1088, offs=41)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp28__1) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, tmp29__1) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_9) ;
ATStailcal_end()

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19082(line=1084, offs=15) -- 19205(line=1089, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 19213(line=1090, offs=3) -- 19241(line=1090, offs=31)
*/
ATSINSmove_void(tmpret24__1, ATSLIB_056_prelude_056_unsafe__ptr0_set__19__2(arg0, ATSPMVchar('\000'))) ;

} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret24__1) ;
} /* end of [loop_9__9__1] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 2580(line=169, offs=3) -- 2676(line=173, offs=2)
*/
/*
local: 
global: string_tabulate$fopr$7$1(level=3)
local: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
global: str$4613(1)(HSEapp(HSEcst(atstkind_type); HSEs2exp(S2Eextkind(atstype_ptrk))))
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_tabulate__fopr__7__1(atstkind_type(atstype_ptrk) env0, atstkind_t0ype(atstype_size) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp20__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp21__1, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2555(line=168, offs=1) -- 2676(line=173, offs=2)
*/
ATSINSflab(__patsflab_string_tabulate__fopr):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2586(line=169, offs=9) -- 2676(line=173, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2646(line=172, offs=23) -- 2673(line=172, offs=50)
*/
ATSINSmove(tmp21__1, ATSLIB_056_prelude__string_get_at_size__14__1(env0, ATSPMVcastfn(cast, atstkind_t0ype(atstype_size), arg0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2626(line=172, offs=3) -- 2674(line=172, offs=51)
*/
ATSINSmove(tmp20__1, _057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_char(tmp21__1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2586(line=169, offs=9) -- 2604(line=169, offs=27)
*/
ATSINSmove(tmpret19__1, ATSPMVcastfn(cast, atstkind_t0ype(atstype_char), tmp20__1)) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2586(line=169, offs=9) -- 2676(line=173, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret19__1) ;
} /* end of [ATSLIB_056_prelude__string_tabulate__fopr__7__1] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 3544(line=161, offs=19) -- 3596(line=162, offs=42)
*/
/*
local: 
global: string_get_at_size$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_get_at_size__14(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp49, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 3526(line=161, offs=1) -- 3596(line=162, offs=42)
*/
ATSINSflab(__patsflab_string_get_at_size):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 3578(line=162, offs=24) -- 3595(line=162, offs=41)
*/
ATSINSmove(tmp49, atspre_add_ptr1_bsz(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 3557(line=162, offs=3) -- 3596(line=162, offs=42)
*/
ATSINSmove(tmpret48, PMVtmpltcst(ptr1_get<S2Eexi(c(89); S2Eapp(S2Ecst(<=); S2Eapp(S2Ecst(~); S2Eintinf(128)), S2Evar(c(89))), S2Eapp(S2Ecst(<); S2Evar(c(89)), S2Eintinf(128)), S2Eapp(S2Ecst(!=); S2Evar(c(89)), S2Eintinf(0)); S2Eapp(S2Ecst(char_int_t0ype); S2Evar(c(89))))>)(tmp49)) ;

ATSfunbody_end()
ATSreturn(tmpret48) ;
} /* end of [ATSLIB_056_prelude__string_get_at_size__14] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/string.dats: 3544(line=161, offs=19) -- 3596(line=162, offs=42)
*/
/*
local: 
global: string_get_at_size$14$1(level=4)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude__string_get_at_size__14__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_size) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48__1, atstkind_t0ype(atstype_char)) ;
ATStmpdec(tmp49__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 3526(line=161, offs=1) -- 3596(line=162, offs=42)
*/
ATSINSflab(__patsflab_string_get_at_size):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 3578(line=162, offs=24) -- 3595(line=162, offs=41)
*/
ATSINSmove(tmp49__1, atspre_add_ptr1_bsz(ATSPMVcastfn(string2ptr, atstkind_type(atstype_ptrk), arg0), arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 3557(line=162, offs=3) -- 3596(line=162, offs=42)
*/
ATSINSmove(tmpret48__1, ATSLIB_056_prelude_056_unsafe__ptr0_get__17__1(tmp49__1)) ;

ATSfunbody_end()
ATSreturn(tmpret48__1) ;
} /* end of [ATSLIB_056_prelude__string_get_at_size__14__1] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1763(line=60, offs=3) -- 1976(line=68, offs=2)
*/
/*
local: 
global: ptr0_get$17$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(5731)
tmparg = S2Evar(a(5731))
tmpsub = None()
*/
atstyvar_type(a)
ATSLIB_056_prelude_056_unsafe__ptr0_get__17(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1752(line=59, offs=1) -- 1976(line=68, offs=2)
*/
ATSINSflab(__patsflab_ptr0_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1950(line=66, offs=11) -- 1952(line=66, offs=13)
*/
ATSINSmove(tmpret52, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a))) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret52) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_get__17] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1763(line=60, offs=3) -- 1976(line=68, offs=2)
*/
/*
local: 
global: ptr0_get$17$1(level=5)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5731)
tmparg = S2Evar(a(5731))
tmpsub = Some(a(5731) -> S2Eexi(c$10855(17268); S2Eapp(S2Ecst(<=); S2Eapp(S2Ecst(~); S2Eintinf(128)), S2Evar(c$10855(17268))), S2Eapp(S2Ecst(<); S2Evar(c$10855(17268)), S2Eintinf(128)), S2Eapp(S2Ecst(!=); S2Evar(c$10855(17268)), S2Eintinf(0)); S2Eapp(S2Ecst(char_int_t0ype); S2Evar(c$10855(17268)))))
*/
atstkind_t0ype(atstype_char)
ATSLIB_056_prelude_056_unsafe__ptr0_get__17__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret52__1, atstkind_t0ype(atstype_char)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1752(line=59, offs=1) -- 1976(line=68, offs=2)
*/
ATSINSflab(__patsflab_ptr0_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1950(line=66, offs=11) -- 1952(line=66, offs=13)
*/
ATSINSmove(tmpret52__1, ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char))) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 1769(line=60, offs=9) -- 1976(line=68, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret52__1) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_get__17__1] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 2089(line=77, offs=3) -- 2312(line=85, offs=2)
*/
/*
local: 
global: ptr0_set$19$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(5734)
tmparg = S2Evar(a(5734))
tmpsub = None()
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__19(atstkind_type(atstype_ptrk) arg0, atstyvar_type(a) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret54) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2078(line=76, offs=1) -- 2312(line=85, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2098(line=77, offs=12) -- 2312(line=85, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2281(line=83, offs=12) -- 2288(line=83, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstyvar_type(a)), arg1) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2281(line=83, offs=12) -- 2288(line=83, offs=19)
*/
ATSINSmove_void(tmpret54, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2098(line=77, offs=12) -- 2312(line=85, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret54) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__19] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 2089(line=77, offs=3) -- 2312(line=85, offs=2)
*/
/*
local: 
global: ptr0_set$19$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5734)
tmparg = S2Evar(a(5734))
tmpsub = Some(a(5734) -> S2Ecst(char_t0ype))
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__19__1(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_char) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret54__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2078(line=76, offs=1) -- 2312(line=85, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2098(line=77, offs=12) -- 2312(line=85, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2281(line=83, offs=12) -- 2288(line=83, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char)), arg1) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2281(line=83, offs=12) -- 2288(line=83, offs=19)
*/
ATSINSmove_void(tmpret54__1, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2098(line=77, offs=12) -- 2312(line=85, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret54__1) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__19__1] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/pointer.dats: 1811(line=62, offs=10) -- 1842(line=62, offs=41)
*/
/*
local: 
global: ptr0_succ$21$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(4697)
tmparg = S2Evar(a(4697))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__21(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret56, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1802(line=62, offs=1) -- 1842(line=62, offs=41)
*/
ATSINSflab(__patsflab_ptr0_succ):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1817(line=62, offs=16) -- 1842(line=62, offs=41)
*/
ATSINSmove(tmpret56, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstyvar_type(a)))) ;

ATSfunbody_end()
ATSreturn(tmpret56) ;
} /* end of [ATSLIB_056_prelude__ptr0_succ__21] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/pointer.dats: 1811(line=62, offs=10) -- 1842(line=62, offs=41)
*/
/*
local: 
global: ptr0_succ$21$1(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(4697)
tmparg = S2Evar(a(4697))
tmpsub = Some(a(4697) -> S2Ecst(char_t0ype))
*/
atstkind_type(atstype_ptrk)
ATSLIB_056_prelude__ptr0_succ__21__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret56__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1802(line=62, offs=1) -- 1842(line=62, offs=41)
*/
ATSINSflab(__patsflab_ptr0_succ):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/pointer.dats({$PATSPRE}/DATS/pointer.dats): 1817(line=62, offs=16) -- 1842(line=62, offs=41)
*/
ATSINSmove(tmpret56__1, atspre_add_ptr0_bsz(arg0, ATSPMVsizeof(atstkind_t0ype(atstype_char)))) ;

ATSfunbody_end()
ATSreturn(tmpret56__1) ;
} /* end of [ATSLIB_056_prelude__ptr0_succ__21__1] */

/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 2089(line=77, offs=3) -- 2312(line=85, offs=2)
*/
/*
local: 
global: ptr0_set$19$2(level=3)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(5734)
tmparg = S2Evar(a(5734))
tmpsub = Some(a(5734) -> S2Ecst(char_t0ype))
*/
atsvoid_t0ype
ATSLIB_056_prelude_056_unsafe__ptr0_set__19__2(atstkind_type(atstype_ptrk) arg0, atstkind_t0ype(atstype_char) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret54__2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2078(line=76, offs=1) -- 2312(line=85, offs=2)
*/
ATSINSflab(__patsflab_ptr0_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2098(line=77, offs=12) -- 2312(line=85, offs=2)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2281(line=83, offs=12) -- 2288(line=83, offs=19)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(g1ofg0_ptr, atstkind_type(atstype_ptrk), arg0), atstkind_t0ype(atstype_char)), arg1) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2281(line=83, offs=12) -- 2288(line=83, offs=19)
*/
ATSINSmove_void(tmpret54__2, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/unsafe.dats: 2098(line=77, offs=12) -- 2312(line=85, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret54__2) ;
} /* end of [ATSLIB_056_prelude_056_unsafe__ptr0_set__19__2] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 11281(line=622, offs=6) -- 11388(line=628, offs=2)
*/
/*
local: 
global: string1_length$27$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = 
tmpsub = None()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__27(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret60, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11261(line=621, offs=1) -- 11388(line=628, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11291(line=623, offs=3) -- 11388(line=628, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11291(line=623, offs=3) -- 11304(line=623, offs=16)
*/
ATSINSmove(tmpret60, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11291(line=623, offs=3) -- 11388(line=628, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret60) ;
} /* end of [ATSLIB_056_prelude__string1_length__27] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/string.dats: 11281(line=622, offs=6) -- 11388(line=628, offs=2)
*/
/*
local: 
global: string1_length$27$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = 
tmpsub = Some()
*/
atstkind_t0ype(atstype_size)
ATSLIB_056_prelude__string1_length__27__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret60__1, atstkind_t0ype(atstype_size)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11261(line=621, offs=1) -- 11388(line=628, offs=2)
*/
ATSINSflab(__patsflab_string1_length):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11291(line=623, offs=3) -- 11388(line=628, offs=2)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11291(line=623, offs=3) -- 11304(line=623, offs=16)
*/
ATSINSmove(tmpret60__1, atspre_strlen(arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/string.dats({$PATSPRE}/DATS/string.dats): 11291(line=623, offs=3) -- 11388(line=628, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret60__1) ;
} /* end of [ATSLIB_056_prelude__string1_length__27__1] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 2888(line=188, offs=1) -- 4166(line=237, offs=4)
*/
/*
local: 
global: ftimeout_29$0(level=0)
local: 
global: 
*/
ATSstatic()
gboolean
ftimeout_29()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret62, gboolean) ;
ATStmpdec(tmp63, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmpref64, GtkTextIter) ;
ATStmpdec(tmpref65, GtkTextIter) ;
// ATStmpdec_void(tmp66) ;
// ATStmpdec_void(tmp67) ;
ATStmpdec(tmp68, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp69) ;
ATStmpdec(tmp70, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp71) ;
ATStmpdec(tmp72, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp73, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp74, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp75, gdouble) ;
ATStmpdec(tmp76, gdouble) ;
// ATStmpdec_void(tmp77) ;
// ATStmpdec_void(tmp78) ;
// ATStmpdec_void(tmp79) ;
// ATStmpdec_void(tmp80) ;
// ATStmpdec_void(tmp81) ;
// ATStmpdec_void(tmp82) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2888(line=188, offs=1) -- 4166(line=237, offs=4)
*/
ATSINSflab(__patsflab_ftimeout_29):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2914(line=189, offs=18) -- 4166(line=237, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2930(line=191, offs=10) -- 2945(line=191, offs=25)
*/
ATSINSmove(tmp63, TextProcessing__TEXTBUF__get()) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2996(line=194, offs=5) -- 3004(line=194, offs=13)
*/
/*
ATSINStmpdec(tmpref64) ;
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3023(line=195, offs=5) -- 3031(line=195, offs=13)
*/
/*
ATSINStmpdec(tmpref65) ;
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3060(line=198, offs=3) -- 3104(line=198, offs=47)
*/
ATSINSmove_void(tmp66, gtk_text_buffer_get_start_iter(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp63)), ATSPMVrefarg1(ATSPMVptrof(tmpref64)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3117(line=200, offs=10) -- 3159(line=200, offs=52)
*/
ATSINSmove_void(tmp67, gtk_text_buffer_get_end_iter(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp63)), ATSPMVrefarg1(ATSPMVptrof(tmpref65)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3179(line=203, offs=3) -- 3235(line=203, offs=59)
*/
ATSINSmove(tmp68, atscntrb_gtk_text_buffer_get_text(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp63)), ATSPMVrefarg1(ATSPMVptrof(tmpref64)), ATSPMVrefarg1(ATSPMVptrof(tmpref65)), ATSPMVextval(TRUE))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3245(line=204, offs=10) -- 3278(line=204, offs=43)
*/
ATSINSmove_void(tmp69, _057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_initize()) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3294(line=205, offs=16) -- 3348(line=205, offs=70)
*/
ATSINSmove(tmp70, _057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__TextProcessing_string(ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp68)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3358(line=206, offs=10) -- 3379(line=206, offs=31)
*/
ATSINSmove_void(tmp71, atscntrb_gstrptr_free(tmp68)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3427(line=210, offs=11) -- 3443(line=210, offs=27)
*/
ATSINSmove(tmp72, TextProcessing__TEXTBUF2__get()) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3503(line=213, offs=12) -- 3518(line=213, offs=27)
*/
ATSINSmove(tmp73, TextProcessing__VADJUST__get()) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3577(line=215, offs=12) -- 3592(line=215, offs=27)
*/
ATSINSmove(tmp74, TextProcessing__VADJUST__get()) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3660(line=218, offs=18) -- 3690(line=218, offs=48)
*/
ATSINSmove(tmp75, atscntrb_gtk_adjustment_get_value(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp73)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3709(line=219, offs=18) -- 3739(line=219, offs=48)
*/
ATSINSmove(tmp76, atscntrb_gtk_adjustment_get_value(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp74)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3753(line=221, offs=10) -- 3820(line=221, offs=77)
*/
ATSINSmove_void(tmp77, atscntrb_gtk_text_buffer_setall_text(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp72)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp70)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3833(line=223, offs=10) -- 3876(line=223, offs=53)
*/
ATSINSmove_void(tmp78, atscntrb_gtk_adjustment_set_value(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp73)), tmp75)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3886(line=224, offs=10) -- 3929(line=224, offs=53)
*/
ATSINSmove_void(tmp79, atscntrb_gtk_adjustment_set_value(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp74)), tmp76)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3939(line=225, offs=10) -- 3973(line=225, offs=44)
*/
ATSINSmove_void(tmp80, atscntrb_gtk_adjustment_value_changed(ATSPMVrefarg0(ATSPMVcastfn(castvwtp0, atstkind_type(atstype_ptrk), tmp74)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 3995(line=227, offs=18) -- 4015(line=227, offs=38)
*/
ATSINSmove_void(tmp81, TextProcessing__KEYPRESSED__reset()) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4126(line=233, offs=10) -- 4147(line=233, offs=31)
*/
ATSINSmove_void(tmp82, atspre_strptr_free(tmp70)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4157(line=236, offs=3) -- 4162(line=236, offs=8)
*/
ATSINSmove(tmpret62, ATSPMVextval(TRUE)) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 2914(line=189, offs=18) -- 4166(line=237, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret62) ;
} /* end of [ftimeout_29] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 4219(line=242, offs=1) -- 4301(line=243, offs=58)
*/
/*
local: ftimeout_29$0(level=0)
global: ftimeout_29$0(level=0), ftimeout2_30$0(level=0)
local: 
global: 
*/
ATSstatic()
gboolean
ftimeout2_30()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret83, gboolean) ;
ATStmpdec(tmp84, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp89, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4219(line=242, offs=1) -- 4301(line=243, offs=58)
*/
ATSINSflab(__patsflab_ftimeout2_30):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4249(line=243, offs=6) -- 4267(line=243, offs=24)
*/
ATSINSmove(tmp89, TextProcessing__KEYPRESSED__get()) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4249(line=243, offs=6) -- 4271(line=243, offs=28)
*/
ATSINSmove(tmp84, ATSLIB_056_prelude__gt_g0int_int__31__1(tmp89, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4246(line=243, offs=3) -- 4301(line=243, offs=58)
*/
ATSif(
tmp84
) ATSthen() {
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4277(line=243, offs=34) -- 4288(line=243, offs=45)
*/
ATSINSmove(tmpret83, ftimeout_29()) ;

} ATSelse() {
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4295(line=243, offs=52) -- 4300(line=243, offs=57)
*/
ATSINSmove(tmpret83, ATSPMVextval(TRUE)) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret83) ;
} /* end of [ftimeout2_30] */

#if(0)
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11834(line=611, offs=3) -- 11873(line=611, offs=42)
*/
/*
local: 
global: gt_g0int_int$31$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4641)
tmparg = S2Evar(tk(4641))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__31(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret85, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp86, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11819(line=610, offs=1) -- 11873(line=611, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11860(line=611, offs=29) -- 11871(line=611, offs=40)
*/
ATSINSmove(tmp86, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4641))>)(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11843(line=611, offs=12) -- 11873(line=611, offs=42)
*/
ATSINSmove(tmpret85, PMVtmpltcst(g0int_gt<S2Evar(tk(4641))>)(arg0, tmp86)) ;

ATSfunbody_end()
ATSreturn(tmpret85) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__31] */
#endif // end of [TEMPLATE]

/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 11834(line=611, offs=3) -- 11873(line=611, offs=42)
*/
/*
local: 
global: gt_g0int_int$31$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4641)
tmparg = S2Evar(tk(4641))
tmpsub = Some(tk(4641) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gt_g0int_int__31__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret85__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp86__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11819(line=610, offs=1) -- 11873(line=611, offs=42)
*/
ATSINSflab(__patsflab_gt_g0int_int):
/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11860(line=611, offs=29) -- 11871(line=611, offs=40)
*/
ATSINSmove(tmp86__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 11843(line=611, offs=12) -- 11873(line=611, offs=42)
*/
ATSINSmove(tmpret85__1, atspre_g0int_gt_int(arg0, tmp86__1)) ;

ATSfunbody_end()
ATSreturn(tmpret85__1) ;
} /* end of [ATSLIB_056_prelude__gt_g0int_int__31__1] */

/*
/tmp/assigns/10/Enigma/TextProcessing.dats: 4505(line=259, offs=7) -- 7500(line=356, offs=2)
*/
/*
local: fdestroy_0$0(level=0), fdelete_event_1$0(level=0), on_key_press_event_2$0(level=0), ftimeout2_30$0(level=0)
global: fdestroy_0$0(level=0), fdelete_event_1$0(level=0), on_key_press_event_2$0(level=0), ftimeout_29$0(level=0), ftimeout2_30$0(level=0), mainats_argc_argv_0$35$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_argc_argv_0(atstkind_t0ype(atstype_int) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret90) ;
ATStmpdec(tmpref91, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpref92, charptrptr) ;
// ATStmpdec_void(tmp93) ;
ATStmpdec(tmp94, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp95) ;
ATStmpdec(tmp96, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp97) ;
// ATStmpdec_void(tmp98) ;
ATStmpdec(tmp99, guint) ;
ATStmpdec(tmp100, guint) ;
// ATStmpdec_void(tmp101) ;
// ATStmpdec_void(tmp102) ;
// ATStmpdec_void(tmp103) ;
ATStmpdec(tmp104, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp105) ;
ATStmpdec(tmp106, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp107) ;
ATStmpdec(tmp108, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp109) ;
ATStmpdec(tmp110, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp111) ;
// ATStmpdec_void(tmp112) ;
ATStmpdec(tmp113, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp114, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp115) ;
// ATStmpdec_void(tmp116) ;
ATStmpdec(tmp117, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp118) ;
ATStmpdec(tmp119, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp120) ;
// ATStmpdec_void(tmp121) ;
ATStmpdec(tmp122, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp123) ;
ATStmpdec(tmp124, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp125, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp126) ;
// ATStmpdec_void(tmp127) ;
// ATStmpdec_void(tmp128) ;
// ATStmpdec_void(tmp129) ;
// ATStmpdec_void(tmp130) ;
ATStmpdec(tmp131, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp132) ;
ATStmpdec(tmp133, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp134, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp135) ;
// ATStmpdec_void(tmp136) ;
// ATStmpdec_void(tmp137) ;
// ATStmpdec_void(tmp138) ;
// ATStmpdec_void(tmp139) ;
// ATStmpdec_void(tmp140) ;
ATStmpdec(tmp141, guint) ;
// ATStmpdec_void(tmp142) ;
// ATStmpdec_void(tmp143) ;
// ATStmpdec_void(tmp144) ;
// ATStmpdec_void(tmp145) ;
ATStmpdec(tmp146, guint) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4499(line=259, offs=1) -- 7500(line=356, offs=2)
*/
ATSINSflab(__patsflab_main_argc_argv_0):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4520(line=259, offs=22) -- 7500(line=356, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4538(line=262, offs=5) -- 4542(line=262, offs=9)
*/
/*
ATSINStmpdec(tmpref91) ;
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4550(line=262, offs=17) -- 4554(line=262, offs=21)
*/
ATSINSmove(tmpref91, arg0) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4559(line=263, offs=5) -- 4563(line=263, offs=9)
*/
/*
ATSINStmpdec(tmpref92) ;
*/
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4578(line=263, offs=24) -- 4608(line=263, offs=54)
*/
ATSINSmove(tmpref92, ATSPMVcastfn(castvwtp1, charptrptr, ATSPMVrefarg0(arg1))) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4622(line=265, offs=10) -- 4676(line=265, offs=64)
*/
ATSINSmove_void(tmp93, ATSextfcall(gtk_init, (ATSPMVptrof(tmpref91), ATSPMVptrof(tmpref92)))) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4695(line=268, offs=3) -- 4730(line=268, offs=38)
*/
ATSINSmove(tmp94, atscntrb_gtk_window_new(ATSPMVextval(GTK_WINDOW_TOPLEVEL))) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4772(line=270, offs=10) -- 4796(line=270, offs=34)
*/
ATSINSmove(tmp96, atspre_gt_ptr1_intz(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp94)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4772(line=270, offs=10) -- 4796(line=270, offs=34)
*/
ATSINSmove_void(tmp95, atspre_assert_errmsg_bool1(tmp96, ATSCSTSPmyloc("/tmp/assigns/10/Enigma/TextProcessing.dats: 4772(line=270, offs=10) -- 4796(line=270, offs=34)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4806(line=271, offs=10) -- 4827(line=271, offs=31)
*/
ATSINSmove_void(tmp97, TextProcessing__TOPWIN__set(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp94)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4838(line=272, offs=10) -- 4894(line=272, offs=66)
*/
ATSINSmove_void(tmp98, atscntrb_gtk_window_set_title(ATSPMVrefarg0(tmp94), ATSPMVcastfn(gstring_of_string, atstkind_type(atstype_ptrk), ATSPMVstring("TextProcessing")))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4906(line=273, offs=12) -- 4993(line=276, offs=2)
*/
ATSINSmove(tmp99, atscntrb_g_signal_connect(ATSPMVrefarg0(tmp94), ATSPMVcastfn(gsignal, atstkind_type(atstype_ptrk), ATSPMVstring("destroy")), ATSPMVcastfn(G_CALLBACK, atstkind_type(atstype_ptrk), ATSPMVfunlab(fdestroy_0)), ATSPMVcastfn(gpointer_of_ptr, atstkind_type(atstype_ptrk), the_atsptr_null))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5021(line=277, offs=12) -- 5118(line=280, offs=2)
*/
ATSINSmove(tmp100, atscntrb_g_signal_connect(ATSPMVrefarg0(tmp94), ATSPMVcastfn(gsignal, atstkind_type(atstype_ptrk), ATSPMVstring("delete_event")), ATSPMVcastfn(G_CALLBACK, atstkind_type(atstype_ptrk), ATSPMVfunlab(fdelete_event_1)), ATSPMVcastfn(gpointer_of_ptr, atstkind_type(atstype_ptrk), the_atsptr_null))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5147(line=283, offs=1) -- 5199(line=283, offs=53)
*/
ATSINSmove_void(tmp101, atscntrb_gtk_window_set_position(ATSPMVrefarg0(tmp94), ATSPMVextval(GTK_WIN_POS_CENTER))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5209(line=284, offs=10) -- 5249(line=284, offs=50)
*/
ATSINSmove_void(tmp102, atscntrb_gtk_window_set_resizable(ATSPMVrefarg0(tmp94), ATSPMVextval(TRUE))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5259(line=285, offs=10) -- 5309(line=285, offs=60)
*/
ATSINSmove_void(tmp103, atscntrb_gtk_container_set_border_width(ATSPMVrefarg0(tmp94), ATSPMVcastfn(guint_of_int, guint, ATSPMVi0nt(10)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5324(line=288, offs=1) -- 5354(line=288, offs=31)
*/
ATSINSmove(tmp104, atscntrb_gtk_hbox_new(ATSPMVextval(FALSE), ATSPMVcastfn(gint_of_int, gint, ATSPMVi0nt(0)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5364(line=289, offs=10) -- 5393(line=289, offs=39)
*/
ATSINSmove(tmp106, atspre_gt_ptr1_intz(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp104)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5364(line=289, offs=10) -- 5393(line=289, offs=39)
*/
ATSINSmove_void(tmp105, atspre_assert_errmsg_bool1(tmp106, ATSCSTSPmyloc("/tmp/assigns/10/Enigma/TextProcessing.dats: 5364(line=289, offs=10) -- 5393(line=289, offs=39)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5403(line=290, offs=10) -- 5435(line=290, offs=42)
*/
ATSINSmove_void(tmp107, atscntrb_gtk_container_add(ATSPMVrefarg0(tmp94), ATSPMVrefarg0(tmp104))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5450(line=293, offs=1) -- 5489(line=293, offs=40)
*/
ATSINSmove(tmp108, atscntrb_gtk_scrolled_window_new_null()) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5499(line=294, offs=10) -- 5528(line=294, offs=39)
*/
ATSINSmove(tmp110, atspre_gt_ptr1_intz(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp108)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5499(line=294, offs=10) -- 5528(line=294, offs=39)
*/
ATSINSmove_void(tmp109, atspre_assert_errmsg_bool1(tmp110, ATSCSTSPmyloc("/tmp/assigns/10/Enigma/TextProcessing.dats: 5499(line=294, offs=10) -- 5528(line=294, offs=39)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5538(line=295, offs=10) -- 5594(line=295, offs=66)
*/
ATSINSmove_void(tmp111, atscntrb_gtk_widget_set_size_request(ATSPMVrefarg0(tmp108), ATSPMVcastfn(gint_of_int, gint, ATSPMVi0nt(320)), ATSPMVcastfn(gint_of_int, gint, ATSPMVi0nt(200)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5604(line=296, offs=10) -- 5659(line=296, offs=65)
*/
ATSINSmove_void(tmp112, atscntrb_gtk_box_pack_start(ATSPMVrefarg0(tmp104), ATSPMVrefarg0(tmp108), ATSPMVextval(TRUE), ATSPMVextval(TRUE), ATSPMVcastfn(guint_of_int, guint, ATSPMVi0nt(4)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5687(line=298, offs=25) -- 5728(line=298, offs=66)
*/
ATSINSmove(tmp113, atscntrb_gtk_scrolled_window_get_hadjustment(ATSPMVrefarg0(tmp108))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5754(line=299, offs=25) -- 5795(line=299, offs=66)
*/
ATSINSmove(tmp114, atscntrb_gtk_scrolled_window_get_vadjustment(ATSPMVrefarg0(tmp108))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5809(line=301, offs=10) -- 5837(line=301, offs=38)
*/
ATSINSmove_void(tmp115, TextProcessing__HADJUST__set(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp113)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5847(line=301, offs=48) -- 5875(line=301, offs=76)
*/
ATSINSmove_void(tmp116, TextProcessing__VADJUST__set(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp114)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5891(line=304, offs=1) -- 5927(line=304, offs=37)
*/
ATSINSmove(tmp117, atscntrb_gtk_scrolled_window_new(ATSPMVrefarg0(tmp113), ATSPMVrefarg0(tmp114))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5937(line=305, offs=10) -- 5967(line=305, offs=40)
*/
ATSINSmove(tmp119, atspre_gt_ptr1_intz(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp117)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5937(line=305, offs=10) -- 5967(line=305, offs=40)
*/
ATSINSmove_void(tmp118, atspre_assert_errmsg_bool1(tmp119, ATSCSTSPmyloc("/tmp/assigns/10/Enigma/TextProcessing.dats: 5937(line=305, offs=10) -- 5967(line=305, offs=40)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 5977(line=306, offs=10) -- 6034(line=306, offs=67)
*/
ATSINSmove_void(tmp120, atscntrb_gtk_widget_set_size_request(ATSPMVrefarg0(tmp117), ATSPMVcastfn(gint_of_int, gint, ATSPMVi0nt(320)), ATSPMVcastfn(gint_of_int, gint, ATSPMVi0nt(200)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6044(line=307, offs=10) -- 6100(line=307, offs=66)
*/
ATSINSmove_void(tmp121, atscntrb_gtk_box_pack_start(ATSPMVrefarg0(tmp104), ATSPMVrefarg0(tmp117), ATSPMVextval(TRUE), ATSPMVextval(TRUE), ATSPMVcastfn(guint_of_int, guint, ATSPMVi0nt(4)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6214(line=312, offs=10) -- 6234(line=312, offs=30)
*/
ATSINSmove(tmp122, atscntrb_gtk_text_view_new()) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6267(line=314, offs=10) -- 6287(line=314, offs=30)
*/
ATSINSmove(tmp124, atspre_gt_ptr1_intz(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp122)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6267(line=314, offs=10) -- 6287(line=314, offs=30)
*/
ATSINSmove_void(tmp123, atspre_assert_errmsg_bool1(tmp124, ATSCSTSPmyloc("/tmp/assigns/10/Enigma/TextProcessing.dats: 6267(line=314, offs=10) -- 6287(line=314, offs=30)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6310(line=317, offs=3) -- 6338(line=317, offs=31)
*/
ATSINSmove(tmp125, atscntrb_gtk_text_view_get_buffer(ATSPMVrefarg0(tmp122))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6349(line=318, offs=10) -- 6375(line=318, offs=36)
*/
ATSINSmove_void(tmp126, TextProcessing__TEXTBUF__set(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp125)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6428(line=321, offs=10) -- 6456(line=321, offs=38)
*/
ATSINSmove_void(tmp127, atscntrb_gtk_container_add(ATSPMVrefarg0(tmp108), ATSPMVrefarg0(tmp122))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6466(line=322, offs=10) -- 6504(line=322, offs=48)
*/
ATSINSmove_void(tmp128, atscntrb_gtk_text_view_set_editable(ATSPMVrefarg0(tmp122), ATSPMVextval(TRUE))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6514(line=323, offs=10) -- 6561(line=323, offs=57)
*/
ATSINSmove_void(tmp129, atscntrb_gtk_text_view_set_wrap_mode(ATSPMVrefarg0(tmp122), ATSPMVextval(GTK_WRAP_WORD))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6571(line=324, offs=10) -- 6596(line=324, offs=35)
*/
ATSINSmove_void(tmp130, atscntrb_gtk_widget_show_unref(tmp122)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6611(line=326, offs=11) -- 6631(line=326, offs=31)
*/
ATSINSmove(tmp131, atscntrb_gtk_text_view_new()) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6666(line=328, offs=10) -- 6687(line=328, offs=31)
*/
ATSINSmove(tmp133, atspre_gt_ptr1_intz(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp131)), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6666(line=328, offs=10) -- 6687(line=328, offs=31)
*/
ATSINSmove_void(tmp132, atspre_assert_errmsg_bool1(tmp133, ATSCSTSPmyloc("/tmp/assigns/10/Enigma/TextProcessing.dats: 6666(line=328, offs=10) -- 6687(line=328, offs=31)"))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6711(line=331, offs=3) -- 6740(line=331, offs=32)
*/
ATSINSmove(tmp134, atscntrb_gtk_text_view_get_buffer(ATSPMVrefarg0(tmp131))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6751(line=332, offs=10) -- 6779(line=332, offs=38)
*/
ATSINSmove_void(tmp135, TextProcessing__TEXTBUF2__set(ATSPMVcastfn(gobjref2ptr, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp134)))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6834(line=335, offs=10) -- 6864(line=335, offs=40)
*/
ATSINSmove_void(tmp136, atscntrb_gtk_container_add(ATSPMVrefarg0(tmp117), ATSPMVrefarg0(tmp131))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6874(line=336, offs=10) -- 6914(line=336, offs=50)
*/
ATSINSmove_void(tmp137, atscntrb_gtk_text_view_set_editable(ATSPMVrefarg0(tmp131), ATSPMVextval(FALSE))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6924(line=337, offs=10) -- 6970(line=337, offs=56)
*/
ATSINSmove_void(tmp138, atscntrb_gtk_text_view_set_cursor_visible(ATSPMVrefarg0(tmp131), ATSPMVextval(FALSE))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 6980(line=338, offs=10) -- 7028(line=338, offs=58)
*/
ATSINSmove_void(tmp139, atscntrb_gtk_text_view_set_wrap_mode(ATSPMVrefarg0(tmp131), ATSPMVextval(GTK_WRAP_WORD))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7038(line=339, offs=10) -- 7064(line=339, offs=36)
*/
ATSINSmove_void(tmp140, atscntrb_gtk_widget_show_unref(tmp131)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7080(line=341, offs=12) -- 7185(line=344, offs=2)
*/
ATSINSmove(tmp141, atscntrb_g_signal_connect(ATSPMVrefarg0(tmp94), ATSPMVcastfn(gsignal, atstkind_type(atstype_ptrk), ATSPMVstring("key-press-event")), ATSPMVcastfn(G_CALLBACK, atstkind_type(atstype_ptrk), ATSPMVfunlab(on_key_press_event_2)), ATSPMVcastfn(gpointer_of_ptr, atstkind_type(atstype_ptrk), the_atsptr_null))) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7198(line=346, offs=10) -- 7225(line=346, offs=37)
*/
ATSINSmove_void(tmp142, atscntrb_gtk_widget_show_unref(tmp108)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7236(line=347, offs=10) -- 7264(line=347, offs=38)
*/
ATSINSmove_void(tmp143, atscntrb_gtk_widget_show_unref(tmp117)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7275(line=348, offs=10) -- 7302(line=348, offs=37)
*/
ATSINSmove_void(tmp144, atscntrb_gtk_widget_show_unref(tmp104)) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7313(line=349, offs=10) -- 7342(line=349, offs=39)
*/
ATSINSmove_void(tmp145, atscntrb_gtk_widget_show_unref(tmp94)) ;

/* (*nothing*) */
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7397(line=352, offs=12) -- 7463(line=352, offs=78)
*/
ATSINSmove(tmp146, atscntrb_g_timeout_add(ATSPMVcastfn(guint_of_uint, guint, ATSPMVi0nt(100U)), ATSPMVcastfn(GSourceFunc, atstkind_type(atstype_ptrk), ATSPMVfunlab(ftimeout2_30)), ATSPMVcastfn(gpointer_of_ptr, atstkind_type(atstype_ptrk), the_atsptr_null))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 7476(line=354, offs=10) -- 7495(line=354, offs=29)
*/
ATSINSmove_void(tmpret90, atscntrb_gtk_main()) ;

/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 4520(line=259, offs=22) -- 7500(line=356, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret90) ;
} /* end of [mainats_argc_argv_0] */

ATSdynloadflag_init(_057_tmp_057_assigns_057_10_057_Enigma_057_Enigma_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_10_057_Enigma_057_Enigma_056_dats__dynload(/*void*/) ;
ATSdynloadflag_init(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynload(/*void*/) ;
/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
ATSdynloadfcall(_057_tmp_057_assigns_057_10_057_Enigma_057_Enigma_056_dats__dynload) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing.dats: 1781(line=117, offs=13) -- 1797(line=117, offs=29)
*/
ATSINSmove(statmp5, Enigma__Enigma_create()) ;

/* in of [local] */
/* end of [local] */
ATSdynloadfcall(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynload) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_056_dats__dynload() ;
ATSmainats_argc_argv_0(argc, argv, err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
