/*
**
** The C code is generated by [ATS/Postiats-0-3-5]
** The starting compilation time is: 2017-5-1:  2h: 6m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/root/ATS-Postiats/prelude/DATS/basics.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_long.dats: 1602(line=49, offs=1) -- 1641(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_size.dats: 1597(line=49, offs=1) -- 1636(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_short.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/char.dats: 1610(line=48, offs=1) -- 1649(line=48, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/float.dats: 1636(line=50, offs=1) -- 1675(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/string.dats: 1631(line=50, offs=1) -- 1670(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/strptr.dats: 1629(line=50, offs=1) -- 1668(line=50, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/strptr.dats: 1691(line=54, offs=1) -- 1738(line=54, offs=48)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_ptr.dats: 1601(line=49, offs=1) -- 1640(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer_fixed.dats: 1603(line=49, offs=1) -- 1642(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1613(line=49, offs=1) -- 1652(line=50, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1675(line=54, offs=1) -- 1721(line=55, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/integer.dats: 1596(line=49, offs=1) -- 1635(line=49, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1744(line=59, offs=1) -- 1789(line=60, offs=38)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 1871(line=66, offs=1) -- 1918(line=66, offs=48)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/sys/stat.sats: 1756(line=58, offs=1) -- 1805(line=60, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/filebas.dats: 15552(line=879, offs=1) -- 15589(line=880, offs=30)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/root/ATS-Postiats/libats/libc/SATS/stdio.sats: 1950(line=69, offs=1) -- 1999(line=71, offs=34)
*/
/*
/root/ATS-Postiats/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/root/ATS-Postiats/prelude/DATS/list.dats: 1529(line=44, offs=1) -- 1568(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/list.dats: 1569(line=46, offs=1) -- 1615(line=47, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/list_vt.dats: 1538(line=44, offs=1) -- 1577(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/list_vt.dats: 1578(line=46, offs=1) -- 1624(line=47, offs=39)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/SHARE/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/stream.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/stream_vt.dats: 1523(line=44, offs=1) -- 1562(line=44, offs=40)
*/
/*
/root/ATS-Postiats/prelude/DATS/tostring.dats: 1528(line=44, offs=1) -- 1567(line=45, offs=32)
*/
/*
/root/ATS-Postiats/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/root/ATS-Postiats/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(the_atsptr_null)
ATSdyncst_mac(atspre_g0int_add_int)
ATSdyncst_mac(atspre_g0int_sub_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
ATSstatmpdec(statmpref1, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(statmp2) ;
ATSstatmpdec(statmpref6, atstkind_t0ype(atstype_int)) ;
ATSstatmpdec(statmpref28, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(statmp29) ;
ATSstatmpdec(statmpref34, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(statmp35) ;
ATSstatmpdec(statmpref40, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(statmp41) ;
ATSstatmpdec(statmpref46, atstkind_type(atstype_ptrk)) ;
// ATSstatmpdec_void(statmp47) ;
ATSstatic()
atsvoid_t0ype
initize_0(atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TOPWIN__get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__TOPWIN__set(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TOPWIN__getref() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
TextProcessing__KEYPRESSED__get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__set(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__inc() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__dec() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__reset() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__incby(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__decby(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
TextProcessing__KEYPRESSED__getinc() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
TextProcessing__KEYPRESSED__decget() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
initize_15(atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__HADJUST__get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__HADJUST__set(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__HADJUST__getref() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
initize_19(atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__VADJUST__get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__VADJUST__set(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__VADJUST__getref() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
initize_23(atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF__get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__TEXTBUF__set(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF__getref() ;
#endif // end of [QUALIFIED]

ATSstatic()
atsvoid_t0ype
initize_27(atsrefarg1_type(atstkind_type(atstype_ptrk))) ;

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF2__get() ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atsvoid_t0ype
TextProcessing__TEXTBUF2__set(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]

#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF2__getref() ;
#endif // end of [QUALIFIED]

/*
/tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 355(line=29, offs=1) -- 402(line=30, offs=40)
*/
/*
local: 
global: initize_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
initize_0(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 355(line=29, offs=1) -- 402(line=30, offs=40)
*/
ATSINSflab(__patsflab_initize_0):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 385(line=30, offs=23) -- 402(line=30, offs=40)
*/
ATSINSstore(ATSderef(arg0, atstkind_type(atstype_ptrk)), the_atsptr_null) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 385(line=30, offs=23) -- 402(line=30, offs=40)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [initize_0] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1904(line=56, offs=15) -- 1915(line=56, offs=26)
*/
/*
local: 
global: get$1$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TOPWIN__get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1900(line=56, offs=11) -- 1915(line=56, offs=26)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1909(line=56, offs=20) -- 1915(line=56, offs=26)
*/
ATSINSmove(tmpret3, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref1)), atstkind_type(atstype_ptrk))) ;
ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [TextProcessing__TOPWIN__get] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1930(line=57, offs=15) -- 1947(line=57, offs=32)
*/
/*
local: 
global: set$2$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__TOPWIN__set(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret4) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1926(line=57, offs=11) -- 1947(line=57, offs=32)
*/
ATSINSflab(__patsflab_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref1)), atstkind_type(atstype_ptrk)), arg0) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSmove_void(tmpret4, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret4) ;
} /* end of [TextProcessing__TOPWIN__set] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1987(line=62, offs=8) -- 2130(line=73, offs=4)
*/
/*
local: 
global: getref$3$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TOPWIN__getref()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret5, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1980(line=62, offs=1) -- 2130(line=73, offs=4)
*/
ATSINSflab(__patsflab_getref):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 2120(line=72, offs=14) -- 2125(line=72, offs=19)
*/
ATSINSmove(tmpret5, ATSPMVptrof(statmpref1)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret5) ;
} /* end of [TextProcessing__TOPWIN__getref] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2032(line=61, offs=15) -- 2043(line=61, offs=26)
*/
/*
local: 
global: get$4$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
TextProcessing__KEYPRESSED__get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2028(line=61, offs=11) -- 2043(line=61, offs=26)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2037(line=61, offs=20) -- 2043(line=61, offs=26)
*/
ATSINSmove(tmpret7, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int))) ;
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [TextProcessing__KEYPRESSED__get] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2058(line=62, offs=15) -- 2075(line=62, offs=32)
*/
/*
local: 
global: set$5$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__set(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret8) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2054(line=62, offs=11) -- 2075(line=62, offs=32)
*/
ATSINSflab(__patsflab_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2064(line=62, offs=21) -- 2075(line=62, offs=32)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), arg0) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2064(line=62, offs=21) -- 2075(line=62, offs=32)
*/
ATSINSmove_void(tmpret8, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret8) ;
} /* end of [TextProcessing__KEYPRESSED__set] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2112(line=66, offs=15) -- 2160(line=67, offs=44)
*/
/*
local: 
global: inc$6$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__inc()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret9) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2108(line=66, offs=11) -- 2160(line=67, offs=44)
*/
ATSINSflab(__patsflab_inc):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2119(line=67, offs=3) -- 2160(line=67, offs=44)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2131(line=67, offs=15) -- 2137(line=67, offs=21)
*/
ATSINSmove(tmp10, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2151(line=67, offs=35) -- 2156(line=67, offs=40)
*/
ATSINSmove(tmp11, atspre_g0int_add_int(tmp10, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2141(line=67, offs=25) -- 2156(line=67, offs=40)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), tmp11) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2141(line=67, offs=25) -- 2156(line=67, offs=40)
*/
ATSINSmove_void(tmpret9, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2119(line=67, offs=3) -- 2160(line=67, offs=44)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret9) ;
} /* end of [TextProcessing__KEYPRESSED__inc] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2192(line=70, offs=15) -- 2240(line=71, offs=44)
*/
/*
local: 
global: dec$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__dec()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret12) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2188(line=70, offs=11) -- 2240(line=71, offs=44)
*/
ATSINSflab(__patsflab_dec):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2199(line=71, offs=3) -- 2240(line=71, offs=44)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2211(line=71, offs=15) -- 2217(line=71, offs=21)
*/
ATSINSmove(tmp13, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2231(line=71, offs=35) -- 2236(line=71, offs=40)
*/
ATSINSmove(tmp14, atspre_g0int_sub_int(tmp13, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2221(line=71, offs=25) -- 2236(line=71, offs=40)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), tmp14) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2221(line=71, offs=25) -- 2236(line=71, offs=40)
*/
ATSINSmove_void(tmpret12, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2199(line=71, offs=3) -- 2240(line=71, offs=44)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret12) ;
} /* end of [TextProcessing__KEYPRESSED__dec] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2295(line=76, offs=17) -- 2311(line=76, offs=33)
*/
/*
local: 
global: reset$10$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__reset()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret15) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2289(line=76, offs=11) -- 2311(line=76, offs=33)
*/
ATSINSflab(__patsflab_reset):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2300(line=76, offs=22) -- 2311(line=76, offs=33)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), ATSPMVi0nt(0)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2300(line=76, offs=22) -- 2311(line=76, offs=33)
*/
ATSINSmove_void(tmpret15, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret15) ;
} /* end of [TextProcessing__KEYPRESSED__reset] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2350(line=80, offs=17) -- 2399(line=81, offs=44)
*/
/*
local: 
global: incby$11$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__incby(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret16) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2344(line=80, offs=11) -- 2399(line=81, offs=44)
*/
ATSINSflab(__patsflab_incby):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2358(line=81, offs=3) -- 2399(line=81, offs=44)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2370(line=81, offs=15) -- 2376(line=81, offs=21)
*/
ATSINSmove(tmp17, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2390(line=81, offs=35) -- 2395(line=81, offs=40)
*/
ATSINSmove(tmp18, atspre_g0int_add_int(tmp17, arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2380(line=81, offs=25) -- 2395(line=81, offs=40)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), tmp18) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2380(line=81, offs=25) -- 2395(line=81, offs=40)
*/
ATSINSmove_void(tmpret16, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2358(line=81, offs=3) -- 2399(line=81, offs=44)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret16) ;
} /* end of [TextProcessing__KEYPRESSED__incby] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2435(line=84, offs=17) -- 2484(line=85, offs=44)
*/
/*
local: 
global: decby$12$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__KEYPRESSED__decby(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret19) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2429(line=84, offs=11) -- 2484(line=85, offs=44)
*/
ATSINSflab(__patsflab_decby):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2443(line=85, offs=3) -- 2484(line=85, offs=44)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2455(line=85, offs=15) -- 2461(line=85, offs=21)
*/
ATSINSmove(tmp20, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2475(line=85, offs=35) -- 2480(line=85, offs=40)
*/
ATSINSmove(tmp21, atspre_g0int_sub_int(tmp20, arg0)) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2465(line=85, offs=25) -- 2480(line=85, offs=40)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), tmp21) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2465(line=85, offs=25) -- 2480(line=85, offs=40)
*/
ATSINSmove_void(tmpret19, ATSPMVempty()) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2443(line=85, offs=3) -- 2484(line=85, offs=44)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret19) ;
} /* end of [TextProcessing__KEYPRESSED__decby] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2542(line=90, offs=18) -- 2595(line=91, offs=49)
*/
/*
local: 
global: getinc$13$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
TextProcessing__KEYPRESSED__getinc()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2535(line=90, offs=11) -- 2595(line=91, offs=49)
*/
ATSINSflab(__patsflab_getinc):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2549(line=91, offs=3) -- 2595(line=91, offs=49)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2561(line=91, offs=15) -- 2567(line=91, offs=21)
*/
ATSINSmove(tmp23, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2581(line=91, offs=35) -- 2586(line=91, offs=40)
*/
ATSINSmove(tmp24, atspre_g0int_add_int(tmp23, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2571(line=91, offs=25) -- 2586(line=91, offs=40)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), tmp24) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2589(line=91, offs=43) -- 2590(line=91, offs=44)
*/
ATSINSmove(tmpret22, tmp23) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2549(line=91, offs=3) -- 2595(line=91, offs=49)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret22) ;
} /* end of [TextProcessing__KEYPRESSED__getinc] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2633(line=94, offs=18) -- 2689(line=95, offs=52)
*/
/*
local: 
global: decget$14$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
TextProcessing__KEYPRESSED__decget()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2626(line=94, offs=11) -- 2689(line=95, offs=52)
*/
ATSINSflab(__patsflab_decget):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2640(line=95, offs=3) -- 2689(line=95, offs=52)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2653(line=95, offs=16) -- 2663(line=95, offs=26)
*/
ATSINSmove(tmp26, atspre_g0int_sub_int(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), ATSPMVi0nt(1))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2667(line=95, offs=30) -- 2679(line=95, offs=42)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref6)), atstkind_t0ype(atstype_int)), tmp26) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2682(line=95, offs=45) -- 2684(line=95, offs=47)
*/
ATSINSmove(tmpret25, tmp26) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 2640(line=95, offs=3) -- 2689(line=95, offs=52)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret25) ;
} /* end of [TextProcessing__KEYPRESSED__decget] */

/*
/tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 765(line=59, offs=1) -- 812(line=60, offs=40)
*/
/*
local: 
global: initize_15$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
initize_15(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret27) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 765(line=59, offs=1) -- 812(line=60, offs=40)
*/
ATSINSflab(__patsflab_initize_15):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 795(line=60, offs=23) -- 812(line=60, offs=40)
*/
ATSINSstore(ATSderef(arg0, atstkind_type(atstype_ptrk)), the_atsptr_null) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 795(line=60, offs=23) -- 812(line=60, offs=40)
*/
ATSINSmove_void(tmpret27, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret27) ;
} /* end of [initize_15] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1904(line=56, offs=15) -- 1915(line=56, offs=26)
*/
/*
local: 
global: get$16$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__HADJUST__get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1900(line=56, offs=11) -- 1915(line=56, offs=26)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1909(line=56, offs=20) -- 1915(line=56, offs=26)
*/
ATSINSmove(tmpret30, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref28)), atstkind_type(atstype_ptrk))) ;
ATSfunbody_end()
ATSreturn(tmpret30) ;
} /* end of [TextProcessing__HADJUST__get] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1930(line=57, offs=15) -- 1947(line=57, offs=32)
*/
/*
local: 
global: set$17$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__HADJUST__set(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret31) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1926(line=57, offs=11) -- 1947(line=57, offs=32)
*/
ATSINSflab(__patsflab_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref28)), atstkind_type(atstype_ptrk)), arg0) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSmove_void(tmpret31, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret31) ;
} /* end of [TextProcessing__HADJUST__set] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1987(line=62, offs=8) -- 2130(line=73, offs=4)
*/
/*
local: 
global: getref$18$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__HADJUST__getref()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret32, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1980(line=62, offs=1) -- 2130(line=73, offs=4)
*/
ATSINSflab(__patsflab_getref):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 2120(line=72, offs=14) -- 2125(line=72, offs=19)
*/
ATSINSmove(tmpret32, ATSPMVptrof(statmpref28)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret32) ;
} /* end of [TextProcessing__HADJUST__getref] */

/*
/tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1005(line=77, offs=1) -- 1052(line=78, offs=40)
*/
/*
local: 
global: initize_19$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
initize_19(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret33) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1005(line=77, offs=1) -- 1052(line=78, offs=40)
*/
ATSINSflab(__patsflab_initize_19):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1035(line=78, offs=23) -- 1052(line=78, offs=40)
*/
ATSINSstore(ATSderef(arg0, atstkind_type(atstype_ptrk)), the_atsptr_null) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1035(line=78, offs=23) -- 1052(line=78, offs=40)
*/
ATSINSmove_void(tmpret33, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret33) ;
} /* end of [initize_19] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1904(line=56, offs=15) -- 1915(line=56, offs=26)
*/
/*
local: 
global: get$20$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__VADJUST__get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1900(line=56, offs=11) -- 1915(line=56, offs=26)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1909(line=56, offs=20) -- 1915(line=56, offs=26)
*/
ATSINSmove(tmpret36, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref34)), atstkind_type(atstype_ptrk))) ;
ATSfunbody_end()
ATSreturn(tmpret36) ;
} /* end of [TextProcessing__VADJUST__get] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1930(line=57, offs=15) -- 1947(line=57, offs=32)
*/
/*
local: 
global: set$21$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__VADJUST__set(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret37) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1926(line=57, offs=11) -- 1947(line=57, offs=32)
*/
ATSINSflab(__patsflab_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref34)), atstkind_type(atstype_ptrk)), arg0) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSmove_void(tmpret37, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret37) ;
} /* end of [TextProcessing__VADJUST__set] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1987(line=62, offs=8) -- 2130(line=73, offs=4)
*/
/*
local: 
global: getref$22$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__VADJUST__getref()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret38, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1980(line=62, offs=1) -- 2130(line=73, offs=4)
*/
ATSINSflab(__patsflab_getref):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 2120(line=72, offs=14) -- 2125(line=72, offs=19)
*/
ATSINSmove(tmpret38, ATSPMVptrof(statmpref34)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret38) ;
} /* end of [TextProcessing__VADJUST__getref] */

/*
/tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1245(line=95, offs=1) -- 1292(line=96, offs=40)
*/
/*
local: 
global: initize_23$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
initize_23(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret39) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1245(line=95, offs=1) -- 1292(line=96, offs=40)
*/
ATSINSflab(__patsflab_initize_23):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1275(line=96, offs=23) -- 1292(line=96, offs=40)
*/
ATSINSstore(ATSderef(arg0, atstkind_type(atstype_ptrk)), the_atsptr_null) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1275(line=96, offs=23) -- 1292(line=96, offs=40)
*/
ATSINSmove_void(tmpret39, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret39) ;
} /* end of [initize_23] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1904(line=56, offs=15) -- 1915(line=56, offs=26)
*/
/*
local: 
global: get$24$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF__get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret42, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1900(line=56, offs=11) -- 1915(line=56, offs=26)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1909(line=56, offs=20) -- 1915(line=56, offs=26)
*/
ATSINSmove(tmpret42, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref40)), atstkind_type(atstype_ptrk))) ;
ATSfunbody_end()
ATSreturn(tmpret42) ;
} /* end of [TextProcessing__TEXTBUF__get] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1930(line=57, offs=15) -- 1947(line=57, offs=32)
*/
/*
local: 
global: set$25$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__TEXTBUF__set(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret43) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1926(line=57, offs=11) -- 1947(line=57, offs=32)
*/
ATSINSflab(__patsflab_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref40)), atstkind_type(atstype_ptrk)), arg0) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSmove_void(tmpret43, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret43) ;
} /* end of [TextProcessing__TEXTBUF__set] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1987(line=62, offs=8) -- 2130(line=73, offs=4)
*/
/*
local: 
global: getref$26$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF__getref()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret44, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1980(line=62, offs=1) -- 2130(line=73, offs=4)
*/
ATSINSflab(__patsflab_getref):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 2120(line=72, offs=14) -- 2125(line=72, offs=19)
*/
ATSINSmove(tmpret44, ATSPMVptrof(statmpref40)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret44) ;
} /* end of [TextProcessing__TEXTBUF__getref] */

/*
/tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1486(line=113, offs=1) -- 1533(line=114, offs=40)
*/
/*
local: 
global: initize_27$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
initize_27(atsrefarg1_type(atstkind_type(atstype_ptrk)) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret45) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1486(line=113, offs=1) -- 1533(line=114, offs=40)
*/
ATSINSflab(__patsflab_initize_27):
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1516(line=114, offs=23) -- 1533(line=114, offs=40)
*/
ATSINSstore(ATSderef(arg0, atstkind_type(atstype_ptrk)), the_atsptr_null) ;
/*
emit_instr: loc0 = /tmp/assigns/10/Enigma/TextProcessing_toplevel.dats: 1516(line=114, offs=23) -- 1533(line=114, offs=40)
*/
ATSINSmove_void(tmpret45, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret45) ;
} /* end of [initize_27] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1904(line=56, offs=15) -- 1915(line=56, offs=26)
*/
/*
local: 
global: get$28$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF2__get()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret48, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1900(line=56, offs=11) -- 1915(line=56, offs=26)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1909(line=56, offs=20) -- 1915(line=56, offs=26)
*/
ATSINSmove(tmpret48, ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref46)), atstkind_type(atstype_ptrk))) ;
ATSfunbody_end()
ATSreturn(tmpret48) ;
} /* end of [TextProcessing__TEXTBUF2__get] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1930(line=57, offs=15) -- 1947(line=57, offs=32)
*/
/*
local: 
global: set$29$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
TextProcessing__TEXTBUF2__set(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret49) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1926(line=57, offs=11) -- 1947(line=57, offs=32)
*/
ATSINSflab(__patsflab_set):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSstore(ATSderef(ATSPMVcastfn(ref_make_viewptr, atstkind_type(atstype_ptrk), ATSPMVptrof(statmpref46)), atstkind_type(atstype_ptrk)), arg0) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1936(line=57, offs=21) -- 1947(line=57, offs=32)
*/
ATSINSmove_void(tmpret49, ATSPMVempty()) ;
ATSfunbody_end()
ATSreturn_void(tmpret49) ;
} /* end of [TextProcessing__TEXTBUF2__set] */

/*
/root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1987(line=62, offs=8) -- 2130(line=73, offs=4)
*/
/*
local: 
global: getref$30$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_type(atstype_ptrk)
TextProcessing__TEXTBUF2__getref()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret50, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1980(line=62, offs=1) -- 2130(line=73, offs=4)
*/
ATSINSflab(__patsflab_getref):
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 2120(line=72, offs=14) -- 2125(line=72, offs=19)
*/
ATSINSmove(tmpret50, ATSPMVptrof(statmpref46)) ;
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1992(line=62, offs=13) -- 2130(line=73, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret50) ;
} /* end of [TextProcessing__TEXTBUF2__getref] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_tmp_057_assigns_057_10_057_Enigma_057_TextProcessing_toplevel_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
/* local */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1713(line=45, offs=5) -- 1717(line=45, offs=9)
*/
/*
ATSINStmpdec(statmpref1) ;
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1781(line=48, offs=10) -- 1797(line=48, offs=26)
*/
ATSINSmove_void(statmp2, initize_0(ATSPMVrefarg1(ATSPMVptrof(statmpref1)))) ;

/* (*nothing*) */
/* in of [local] */
/* end of [local] */
/* local */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 1859(line=51, offs=5) -- 1863(line=51, offs=9)
*/
/*
ATSINStmpdec(statmpref6) ;
*/
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/gcount.hats: 1871(line=51, offs=17) -- 1872(line=51, offs=18)
*/
ATSINSmove(statmpref6, ATSPMVi0nt(0)) ;
/* (*nothing*) */
/* (*nothing*) */
/* in of [local] */
/* end of [local] */
/* local */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1713(line=45, offs=5) -- 1717(line=45, offs=9)
*/
/*
ATSINStmpdec(statmpref28) ;
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1781(line=48, offs=10) -- 1797(line=48, offs=26)
*/
ATSINSmove_void(statmp29, initize_15(ATSPMVrefarg1(ATSPMVptrof(statmpref28)))) ;

/* (*nothing*) */
/* in of [local] */
/* end of [local] */
/* local */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1713(line=45, offs=5) -- 1717(line=45, offs=9)
*/
/*
ATSINStmpdec(statmpref34) ;
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1781(line=48, offs=10) -- 1797(line=48, offs=26)
*/
ATSINSmove_void(statmp35, initize_19(ATSPMVrefarg1(ATSPMVptrof(statmpref34)))) ;

/* (*nothing*) */
/* in of [local] */
/* end of [local] */
/* local */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1713(line=45, offs=5) -- 1717(line=45, offs=9)
*/
/*
ATSINStmpdec(statmpref40) ;
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1781(line=48, offs=10) -- 1797(line=48, offs=26)
*/
ATSINSmove_void(statmp41, initize_23(ATSPMVrefarg1(ATSPMVptrof(statmpref40)))) ;

/* (*nothing*) */
/* in of [local] */
/* end of [local] */
/* local */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1713(line=45, offs=5) -- 1717(line=45, offs=9)
*/
/*
ATSINStmpdec(statmpref46) ;
*/
/* (*nothing*) */
/*
emit_instr: loc0 = /root/ATS-Postiats/contrib/atscntrb-hx-globals/HATS/globvar.hats: 1781(line=48, offs=10) -- 1797(line=48, offs=26)
*/
ATSINSmove_void(statmp47, initize_27(ATSPMVrefarg1(ATSPMVptrof(statmpref46)))) ;

/* (*nothing*) */
/* in of [local] */
/* end of [local] */
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
