/*
**
** The JavaScript code is generated by atscc2js
** The starting compilation time is: 2017-4-9: 23h:33m
**
*/

/* ATSextcode_beg() */
//
var
theCanvas =
document.getElementById
("theShowStream-canvas");
var
theCanvas_ctx2d = theCanvas.getContext('2d');
//
var _ = theCanvas_ctx2d.font = "40px Georgia";
//
function
theCanvas_get() { return theCanvas; };
function
theCanvas_ctx2d_get() { return theCanvas_ctx2d; };
//
/* ATSextcode_end() */

var theCounter3_baconjs_statmp0

var theCounter3_baconjs_statmp1

var theCounter3_baconjs_statmp2

var theCounter3_baconjs_statmp3

var theCounter3_baconjs_statmp4

var theCounter3_baconjs_statmp5

var theCounter3_baconjs_statmp6

var theCounter3_baconjs_statmp7

var theCounter3_baconjs_statmp12

var theCounter3_baconjs_statmp13

var theCounter3_baconjs_statmp14

var theCounter3_baconjs_statmp16

var theCounter3_baconjs_statmp17

var theCounter3_baconjs_statmp19

var theCounter3_baconjs_statmp20

var theCounter3_baconjs_statmp22

var theCounter3_baconjs_statmp23

var theCounter3_baconjs_statmp24

var theCounter3_baconjs_statmp26

var theCounter3_baconjs_statmp27

var theCounter3_baconjs_statmp28

var theCounter3_baconjs_statmp30

var theCounter3_baconjs_statmp31

var theCounter3_baconjs_statmp32

var theCounter3_baconjs_statmp35

var theCounter3_baconjs_statmp37

var theCounter3_baconjs_statmp39

var theCounter3_baconjs_statmp40

var theCounter3_baconjs_statmp41

var theCounter3_baconjs_statmp42

var theCounter3_baconjs_statmp43

var theCounter3_baconjs_statmp44

var theCounter3_baconjs_statmp46

var theCounter3_baconjs_statmp47

var theCounter3_baconjs_statmp48

var theCounter3_baconjs_statmp50

var theCounter3_baconjs_statmp51

var theCounter3_baconjs_statmp52

var theCounter3_baconjs_statmp55

var theCounter3_baconjs_statmp57

/* ATSextcode_beg() */
var keydown = 
   $(document).asEventStream("keydown")
   .map(function (x) {return x.keyCode;})
   .filter(function (x) {return x>=37 && x<=40;})
/* ATSextcode_end() */

function
theCounter3_baconjs_patsfun_0__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_0(arg0); }];
}


function
theCounter3_baconjs_patsfun_1__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_1(arg0); }];
}


function
theCounter3_baconjs_patsfun_2__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_2(arg0); }];
}


function
theCounter3_baconjs_patsfun_3__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_3(arg0); }];
}


function
theCounter3_baconjs_patsfun_4__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_4(arg0); }];
}


function
theCounter3_baconjs_patsfun_5__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_5(arg0); }];
}


function
theCounter3_baconjs_patsfun_6__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_6(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_7__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_7(arg0); }];
}


function
theCounter3_baconjs_patsfun_8__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_8(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_9__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_9(arg0); }];
}


function
theCounter3_baconjs_patsfun_10__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_10(arg0); }];
}


function
theCounter3_baconjs_patsfun_11__closurerize()
{
  return [function(cenv, arg0, arg1) { return theCounter3_baconjs_patsfun_11(arg0, arg1); }];
}


function
theCounter3_baconjs_patsfun_13__closurerize()
{
  return [function(cenv, arg0) { return theCounter3_baconjs_patsfun_13(arg0); }];
}


function
theCounter3_baconjs_patsfun_0(arg0)
{
//
// knd = 0
  var tmpret8
  var tmp9
  var tmp10
  var tmp11
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_0
  tmp9 = ats2jspre_eq_int0_int0(arg0, 37);
  if(tmp9) {
    tmpret8 = 3;
  } else {
    tmp10 = ats2jspre_eq_int0_int0(arg0, 38);
    if(tmp10) {
      tmpret8 = 4;
    } else {
      tmp11 = ats2jspre_eq_int0_int0(arg0, 39);
      if(tmp11) {
        tmpret8 = 1;
      } else {
        tmpret8 = 2;
      } // end-of-if
    } // end-of-if
  } // end-of-if
  return tmpret8;
} // end-of-function


function
theCounter3_baconjs_patsfun_1(arg0)
{
//
// knd = 0
  var tmpret15
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_1
  tmpret15 = 0;
  return tmpret15;
} // end-of-function


function
theCounter3_baconjs_patsfun_2(arg0)
{
//
// knd = 0
  var tmpret18
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_2
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab0
      if(!ATSCKpat_con1(arg0, 0)) {
        { tmplab_js = 4; break; }
      } // ifnthen
      case 2: // __atstmplab1
      tmpret18 = 1;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab2
      case 4: // __atstmplab3
      tmpret18 = 2;
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret18;
} // end-of-function


function
theCounter3_baconjs_patsfun_3(arg0)
{
//
// knd = 0
  var tmpret21
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_3
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab4
      if(!ATSCKpat_con1(arg0, 0)) {
        { tmplab_js = 4; break; }
      } // ifnthen
      case 2: // __atstmplab5
      tmpret21 = 3;
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab6
      case 4: // __atstmplab7
      tmpret21 = 4;
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret21;
} // end-of-function


function
theCounter3_baconjs_patsfun_4(arg0)
{
//
// knd = 0
  var tmpret25
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_4
  tmpret25 = 5;
  return tmpret25;
} // end-of-function


function
theCounter3_baconjs_patsfun_5(arg0)
{
//
// knd = 0
  var tmpret29
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_5
  tmpret29 = 6;
  return tmpret29;
} // end-of-function


function
theCounter3_baconjs_patsfun_6(arg0, arg1)
{
//
// knd = 0
  var tmpret33
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_6
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab8
      if(!ATSCKpat_con0(arg1, 0)) {
        { tmplab_js = 3; break; }
      } // ifnthen
      case 2: // __atstmplab9
      tmpret33 = ats2jspre_neg_bool0(arg0);
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab10
      tmpret33 = false;
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return tmpret33;
} // end-of-function


function
theCounter3_baconjs_patsfun_7(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_7
  if(arg0) {
    $("#theAuto_btn").addClass("btn-primary");
  } else {
    $("#theAuto_btn").removeClass("btn-primary");
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_patsfun_8(arg0, arg1)
{
//
// knd = 0
  var tmpret38
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_8
  if(arg0) {
    tmpret38 = 7;
  } else {
    tmpret38 = arg1;
  } // end-of-if
  return tmpret38;
} // end-of-function


function
theCounter3_baconjs_patsfun_9(arg0)
{
//
// knd = 0
  var tmpret45
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_9
  tmpret45 = 7;
  return tmpret45;
} // end-of-function


function
theCounter3_baconjs_patsfun_10(arg0)
{
//
// knd = 0
  var tmpret49
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_10
  tmpret49 = 7;
  return tmpret49;
} // end-of-function


function
theCounter3_baconjs_patsfun_11(arg0, arg1)
{
//
// knd = 0
  var tmpret53
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_11
  if(arg1) {
    tmpret53 = arg0;
  } else {
    tmpret53 = 7;
  } // end-of-if
  return tmpret53;
} // end-of-function


function
theCounter3_baconjs_theAllAct_do_12(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_theAllAct_do_12
  // ATScaseofseq_beg
  tmplab_js = 1;
  while(true) {
    tmplab = tmplab_js; tmplab_js = 0;
    switch(tmplab) {
      // ATSbranchseq_beg
      case 1: // __atstmplab11
      if(!ATSCKpat_con0(arg0, 0)) {
        { tmplab_js = 3; break; }
      } // ifnthen
      case 2: // __atstmplab12
      // ATSINSmove_void
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 3: // __atstmplab13
      if(!ATSCKpat_con0(arg0, 7)) {
        { tmplab_js = 5; break; }
      } // ifnthen
      case 4: // __atstmplab14
      // ATSINSmove_void
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 5: // __atstmplab15
      if(!ATSCKpat_con0(arg0, 1)) {
        { tmplab_js = 7; break; }
      } // ifnthen
      case 6: // __atstmplab16
      theAllAct_Next_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 7: // __atstmplab17
      if(!ATSCKpat_con0(arg0, 3)) {
        { tmplab_js = 9; break; }
      } // ifnthen
      case 8: // __atstmplab18
      theAllAct_Prev_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 9: // __atstmplab19
      if(!ATSCKpat_con0(arg0, 2)) {
        { tmplab_js = 11; break; }
      } // ifnthen
      case 10: // __atstmplab20
      theAllAct_Next2_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 11: // __atstmplab21
      if(!ATSCKpat_con0(arg0, 4)) {
        { tmplab_js = 13; break; }
      } // ifnthen
      case 12: // __atstmplab22
      theAllAct_Prev2_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 13: // __atstmplab23
      if(!ATSCKpat_con0(arg0, 5)) {
        { tmplab_js = 15; break; }
      } // ifnthen
      case 14: // __atstmplab24
      theAllAct_Search_do();
      break;
      // ATSbranchseq_end
      // ATSbranchseq_beg
      case 15: // __atstmplab25
      case 16: // __atstmplab26
      theAllAct_Reset_do();
      break;
      // ATSbranchseq_end
    } // end-of-switch
    if (tmplab_js === 0) break;
  } // endwhile
  // ATScaseofseq_end
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_patsfun_13(arg0)
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_patsfun_13
  theCounter3_baconjs_theAllAct_do_12(arg0);
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_start()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // __patsflab_theCounter3_baconjs_start
  theCounter3_baconjs_initize();
  theAllAct_Reset_do();
  return/*_void*/;
} // end-of-function

// dynloadflag_minit
var _057_tmp_057_HWWU_057_theCounter3_baconjs_056_dats__dynloadflag = 0;

function
_057_tmp_057_HWWU_057_theCounter3_baconjs_056_dats__dynload()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  // ATSdynload()
  // ATSdynloadflag_sta(_057_tmp_057_HWWU_057_theCounter3_baconjs_056_dats__dynloadflag(161))
  if(ATSCKiseqz(_057_tmp_057_HWWU_057_theCounter3_baconjs_056_dats__dynloadflag)) {
    _057_tmp_057_HWWU_057_theCounter3_baconjs_056_dats__dynloadflag = 1 ; // flag is set
    theCounter3_baconjs_statmp0 = $("#theAuto_btn").asEventStream("click");
    theCounter3_baconjs_statmp1 = $("#theNext_btn").asEventStream("click");
    theCounter3_baconjs_statmp2 = $("#thePrev_btn").asEventStream("click");
    theCounter3_baconjs_statmp3 = $("#theSrch_btn").asEventStream("click");
    theCounter3_baconjs_statmp4 = $("#theReset_btn").asEventStream("click");
    theCounter3_baconjs_statmp7 = 0;
    theCounter3_baconjs_statmp6 = ats2js_bacon_EStream_map_method(keydown, theCounter3_baconjs_statmp7);
    theCounter3_baconjs_statmp5 = theCounter3_baconjs_statmp6[0](theCounter3_baconjs_statmp6, theCounter3_baconjs_patsfun_0__closurerize());
    theCounter3_baconjs_statmp14 = 0;
    theCounter3_baconjs_statmp13 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp0, theCounter3_baconjs_statmp14);
    theCounter3_baconjs_statmp12 = theCounter3_baconjs_statmp13[0](theCounter3_baconjs_statmp13, theCounter3_baconjs_patsfun_1__closurerize());
    theCounter3_baconjs_statmp17 = ats2js_bacon_ext_EStream_singpair_trans(theCounter3_baconjs_statmp1, 200);
    theCounter3_baconjs_statmp16 = ats2js_bacon_EStream_map(theCounter3_baconjs_statmp17, theCounter3_baconjs_patsfun_2__closurerize());
    theCounter3_baconjs_statmp20 = ats2js_bacon_ext_EStream_singpair_trans(theCounter3_baconjs_statmp2, 200);
    theCounter3_baconjs_statmp19 = ats2js_bacon_EStream_map(theCounter3_baconjs_statmp20, theCounter3_baconjs_patsfun_3__closurerize());
    theCounter3_baconjs_statmp24 = 0;
    theCounter3_baconjs_statmp23 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp3, theCounter3_baconjs_statmp24);
    theCounter3_baconjs_statmp22 = theCounter3_baconjs_statmp23[0](theCounter3_baconjs_statmp23, theCounter3_baconjs_patsfun_4__closurerize());
    theCounter3_baconjs_statmp28 = 0;
    theCounter3_baconjs_statmp27 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp4, theCounter3_baconjs_statmp28);
    theCounter3_baconjs_statmp26 = theCounter3_baconjs_statmp27[0](theCounter3_baconjs_statmp27, theCounter3_baconjs_patsfun_5__closurerize());
    theCounter3_baconjs_statmp30 = ats2js_bacon_EStream_merge4(theCounter3_baconjs_statmp16, theCounter3_baconjs_statmp19, theCounter3_baconjs_statmp22, theCounter3_baconjs_statmp5);
    theCounter3_baconjs_statmp32 = ats2js_bacon_EStream_merge2(theCounter3_baconjs_statmp12, theCounter3_baconjs_statmp26);
    theCounter3_baconjs_statmp31 = ats2js_bacon_EStream_scan(theCounter3_baconjs_statmp32, false, theCounter3_baconjs_patsfun_6__closurerize());
    theCounter3_baconjs_statmp35 = ats2js_bacon_Property_onValue_method(theCounter3_baconjs_statmp31);
    theCounter3_baconjs_statmp35[0](theCounter3_baconjs_statmp35, theCounter3_baconjs_patsfun_7__closurerize());
    theCounter3_baconjs_statmp37 = ats2js_bacon_Property_sampledBy_estream_cfun(theCounter3_baconjs_statmp31, theCounter3_baconjs_statmp30, theCounter3_baconjs_patsfun_8__closurerize());
    theCounter3_baconjs_statmp40 = ats2js_bacon_Bacon_interval(100, 0);
    theCounter3_baconjs_statmp39 = ats2js_bacon_Property_sampledBy_estream(theCounter3_baconjs_statmp31, theCounter3_baconjs_statmp40);
    theCounter3_baconjs_statmp44 = 0;
    theCounter3_baconjs_statmp43 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp12, theCounter3_baconjs_statmp44);
    theCounter3_baconjs_statmp42 = theCounter3_baconjs_statmp43[0](theCounter3_baconjs_statmp43, theCounter3_baconjs_patsfun_9__closurerize());
    theCounter3_baconjs_statmp48 = 0;
    theCounter3_baconjs_statmp47 = ats2js_bacon_EStream_map_method(theCounter3_baconjs_statmp26, theCounter3_baconjs_statmp48);
    theCounter3_baconjs_statmp46 = theCounter3_baconjs_statmp47[0](theCounter3_baconjs_statmp47, theCounter3_baconjs_patsfun_10__closurerize());
    theCounter3_baconjs_statmp41 = ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp30, theCounter3_baconjs_statmp42, theCounter3_baconjs_statmp46);
    theCounter3_baconjs_statmp51 = 7;
    theCounter3_baconjs_statmp50 = ats2js_bacon_EStream_toProperty_init(theCounter3_baconjs_statmp41, theCounter3_baconjs_statmp51);
    theCounter3_baconjs_statmp52 = ats2js_bacon_Property_sampledBy_estream_cfun(theCounter3_baconjs_statmp50, theCounter3_baconjs_statmp39, theCounter3_baconjs_patsfun_11__closurerize());
    theCounter3_baconjs_statmp55 = ats2js_bacon_EStream_merge3(theCounter3_baconjs_statmp26, theCounter3_baconjs_statmp37, theCounter3_baconjs_statmp52);
    theCounter3_baconjs_statmp57 = ats2js_bacon_EStream_onValue_method(theCounter3_baconjs_statmp55);
    theCounter3_baconjs_statmp57[0](theCounter3_baconjs_statmp57, theCounter3_baconjs_patsfun_13__closurerize());
  } // end-of-if
  return/*_void*/;
} // end-of-function


function
theCounter3_baconjs_initize()
{
//
// knd = 0
  var tmplab, tmplab_js
//
  _057_tmp_057_HWWU_057_theCounter3_baconjs_056_dats__dynload();
  return/*_void*/;
} // end-of-function


/* ATSextcode_beg() */
//
theCounter3_baconjs_start();
//
/* ATSextcode_end() */

/* ****** ****** */

/* end-of-compilation-unit */
